### ISSUE TITLE
Research Summary: FLOAT and the Money Gods

### ISSUE THREAD

**Issue by tina1998612** [smartcontractresearchforum/research_content#101]
- Importance: This article compares the three most popular algorithmic stablecoins: float, RAI, and FEI, highlighting their different approaches to peg, stabilisation mechanisms, risks and trade-offs.
- Link: https://floatprotocol.medium.com/float-and-the-money-gods-5509d41c9b3a

**Comment by cipherix** [comment]
This seems like an interesting paper, great suggestion @tina1998612. Stablecoin coverage on the forum is thin so this looks like a promising start.

**Comment by jamesmcgirk** [comment]
Another interesting one, moved to the ice box in case another researcher wants a look

**Comment by encore9870** [comment]
Interesting suggestion. I'm closing all issues that are not actively being worked on. Reach out to me if you have questions!
