### ISSUE TITLE
Whitepaper Summary: Uniswap v3 Core 

### ISSUE THREAD

**Issue by visavishesh** [smartcontractresearchforum/research_content#102]
Importance: This whitepaper breaks down the technical details of Uniswap v3 which is a groundbreaking new development in how AMMs work.

[Link to whitepaper](https://uniswap.org/whitepaper-v3.pdf)

[Draft](https://docs.google.com/document/d/1E3BZQoUn90fIQ9VzKbHjyUESDVf1SMQbn8VpCcNSdD4/edit)

**Comment by jamesmcgirk** [comment]
assigned myself as engagement coordinator

**Comment by cipherix** [comment]
This was a good start and a fun read. We'll need to add a lot of background on some sections as noted in the review.

**Comment by jamesmcgirk** [comment]
@visavishesh did my first pass, it's almost perfect. Added in some questions from the engagement team (these are separate from the forthcoming Use Case questions)

**Comment by jamesmcgirk** [comment]
@jamesmcgirk working on Use Case, digging up questions from researchers. Socials drafted.

**Comment by jamesmcgirk** [comment]
Use Case in content review. Research Team to post questions in the forum. James to post Use Case in forum, followed by outreach to authors.

**Comment by jamesmcgirk** [comment]
Use Case complete. Backgrounder linking to other summaries scheduled for 5/5.
