### ISSUE TITLE
Research Summary: PLONK: Permutations over Lagrange-bases for Oecumenical Noninteractive arguments of Knowledge

### ISSUE THREAD

**Issue by jamesmcgirk** [smartcontractresearchforum/research_content#103]
Suggested by Lucas as a first research summary. Assigned to Jerry, who needs access to Github and Google Drive.

**Comment by jamesmcgirk** [comment]
The google link should be pasted here and the paper link...

**Comment by jamesmcgirk** [comment]
@29988122 do you still need access to anything else? You should have write access to Github

**Comment by 29988122** [comment]
Yes, I do have access to github now; just need a google drive access for me to put the draft there.

**Comment by jamesmcgirk** [comment]
@29988122 for now maybe you could post a link to your own Google Doc with open edit permissions and then we can move it later

**Comment by 29988122** [comment]
Sure thing, will do!

**Comment by jamesmcgirk** [comment]
@cipherix Jerry gave me an update, he's about three hours in and debating how technical to get on the paper. He estimates that he'll get this one done on 4/9

**Comment by 29988122** [comment]
https://docs.google.com/document/d/1NtUUerwDXnMj6p54DkomUH2xR9K0izgyWh9Wjl3pmWA/edit

This took me [far far far more longer than expected...](https://en.wikipedia.org/wiki/Hofstadter%27s_law)

@cipherix Please take a look into it, and fix/solve the annotations when necessary, thanks!

**Comment by jamesmcgirk** [comment]
@jamesmcgirk assigned for engagement, GtM to be scheduled, potential Aztec connection?

**Comment by jamesmcgirk** [comment]
@29988122 just wanted to check in and see if you need anything

**Comment by 29988122** [comment]
I guess not, thanks for asking; waiting for Lucas to review the plonk article I assume. 
For next step, I already have some papers to be summarized in mind, will probably put them onto SCRF for draft proposal early next week.

**Comment by jamesmcgirk** [comment]
@29988122 LN is all done with it, I did my first pass - I have a few minor questions where I want to make sure that I didn't introduce any errors, please let me know when you're done and I'll do another check (it's such a complex paper I'm sure I missed something :).) Congratulations on nearing the end!

**Comment by jamesmcgirk** [comment]
@29988122 this one is ready for publication - you're welcome to post some of the comments you had into the forum

**Comment by jamesmcgirk** [comment]
Socials posted.
