### ISSUE TITLE
Use Case: Uniswap v3

### ISSUE THREAD

**Issue by jamesmcgirk** [smartcontractresearchforum/research_content#104]
Use Case interview with Uniswap to accompany the research summary. It's a major release and has many potential applications that would be interesting to discuss. James will develop questions with Vishesh and other researchers after the editorial process has been completed. 

[Use Case draft](https://docs.google.com/document/d/1k0zDrLbwYOsb60sI6-kjqcfjXqImEvlFwrd7I2MI-YY/edit)

**Comment by jamesmcgirk** [comment]
@visavishesh I've moved this into Content Review, you might want to have a glance at it / add a few more questions

**Comment by jamesmcgirk** [comment]
@cipherix are you and @visavishesh done looking this over? It might be nice to post this one today (assuming it passes the editorial review!)

**Comment by cipherix** [comment]
looks good from my perspective -- @visavishesh, can you take a look?

**Comment by visavishesh** [comment]
@cipherix @jamesmcgirk I redid the questions. IMO they were all basically just versions of asking whether v3 is more or less gas efficient. LMK what you think.

**Comment by jamesmcgirk** [comment]
@visavishesh thanks a million, I think it's much stronger and I'm sure you're right. I'll do a quick read-through and then post it.

**Comment by jamesmcgirk** [comment]
Posted to the forum. Socials will go out on 4/19. Email following day.

**Comment by jamesmcgirk** [comment]
Pulled per Ops meeting. Adding an introduction and reworking email around questions.

**Comment by jamesmcgirk** [comment]
Use Case posted 4/19.

**Comment by jamesmcgirk** [comment]
Moved to published.
