### ISSUE TITLE
Research Summary: The Challenges of Investigating Cryptocurrencies and Blockchain Related Crime

### ISSUE THREAD

**Issue by cipherix** [smartcontractresearchforum/research_content#105]
Link: https://arxiv.org/pdf/1907.12221.pdf

This paper provides a good framework to understand the problems with on-chain wallet clustering; a technique often used to de-anonymize blockchain entities.

**Comment by lpassos** [comment]
I would be interested in covering this one.

**Comment by jamesmcgirk** [comment]
@lpassos - are you still interested in doing this one?

**Comment by lpassos** [comment]
Yes I am

**Comment by jamesmcgirk** [comment]
Thanks, @lpassos! I'll leave it in the 'idea proposal stage' column

**Comment by twan-dev** [comment]
Closing this for now. Will reopen it when it's ready to start drafting @lpassos.

**Comment by Fizzymidas** [comment]
@twan-dev I am interested in summarizing this after the discussion post I am working on. What is the process of taking over?
