### ISSUE TITLE
Project: Create Research Team Mandate

### ISSUE THREAD

**Issue by jamesmcgirk** [smartcontractresearchforum/research_content#11]
### Project Description

The research mandate is part of the onboarding pack, and it gives cultural context for the research team position.

### Workplan

- [x] first draft
- [x] schedule meeting with RT lead for notes
- [x] second draft
- [x] present to Team
- [x] get Team buy-in
- [x] post to Github repository

### Resources

[Research Team mandate](https://docs.google.com/document/d/1qkpj-aHYQ_uHVRYxZUHrQJJu2T6wvNMJDxHp2xXXygw/edit)

**Comment by ghettodev** [comment]
This is still heavily a WIP. Targeting a dedicated call for the week of Jan 18th. @jamesmcgirk will be leaning on you to help with the presentation.

**Comment by ghettodev** [comment]
Then something interesting happens.

**Comment by ghettodev** [comment]
LGTM @jamesmcgirk can be moved.

**Comment by ghettodev** [comment]
Problems with tone, moving back to draft.

**Comment by jamesmcgirk** [comment]
@cipherix do you have time for a conversation about the research mandate next week? (If you don't, you're welcome to add some info to the doc)

**Comment by jamesmcgirk** [comment]
@ghettodev can you please take a look at this draft and provide some guidance for the Discovery and Outreach sections please

**Comment by jamesmcgirk** [comment]
@jamesmcgirk - you need to convert this to an issue in the format

**Comment by jamesmcgirk** [comment]
@jamesmcgirk reach out to APAC and EU teams to get their input. Ensure people are reading the document before sign-off.

**Comment by jamesmcgirk** [comment]
ready for MD format!

**Comment by jamesmcgirk** [comment]
@jamesmcgirk review for MD

**Comment by eleventh19** [comment]
need to see if this ever got uploaded to hackMD/where this is @jamesmcgirk

**Comment by jamesmcgirk** [comment]
Added to HackMD - https://hackmd.io/@scrf/BkrhjBun_

**Comment by encore9870** [comment]
Closing this as part of cleaning stale tickets in Github
