### ISSUE TITLE
Discussion Post: Upcoming Taproot Activation

### ISSUE THREAD

**Issue by cipherix** [smartcontractresearchforum/research_content#111]
This discussion post is intended to highlight features and activation procedures of the upcoming Bitcoin soft fork.

**Comment by cipherix** [comment]
Draft (WIP):

https://docs.google.com/document/d/1PpwxGJwYYV1sYZC2LwlgPXHibQKiEgvhUd6v_sOh8uU/edit?usp=sharing

Planning on finishing this by EOW.

**Comment by visavishesh** [comment]
Waiting for engagement from BitML team

**Comment by zubepaul** [comment]
Assigned as engagement team

**Comment by zubepaul** [comment]
@jamesmcgirk assigned as engagement team

**Comment by jamesmcgirk** [comment]
Super minor edits here and there. Ready for engagement review once Vishesh's comments are okay'd

**Comment by jamesmcgirk** [comment]
@cipherix looks like this one has been through the editing process -- what would you like to do with it? @ClaraS mentioned she wouldn't mind doing a Taproot-based interview with a researcher she knows

**Comment by cipherix** [comment]
@jamesmcgirk this will likely get a lot of engagement in November so moved it back to drafting.

**Comment by twan-dev** [comment]
@cipherix @jamesmcgirk November is ending

**Comment by twan-dev** [comment]
The author has other plans for this. Closing until we nail down next steps.
