### ISSUE TITLE
Mechanism for multiple data ingestion points for true decentralization in Blockchain based decentralized marketplaces

### ISSUE THREAD

**Issue by dr-chain** [smartcontractresearchforum/research_content#113]
## Steps to completion

- [x] Provide context/background for broader narrative
- [ ] GTM section filled out
- [ ] Editing step completed
- [x] Proposed tags
- [ ] Glossary items captured
- [ ] Post GTM Meeting

---

## Mechanism for multiple data ingestion points for true decentralization in Blockchain-based decentralized marketplaces

Source: https://www.researchgate.net/publication/341413269_Blockchain_Based_Decentralized_Framework_for_Energy_Demand_Response_Marketplace

Research Summary: https://docs.google.com/document/d/17lL2Otl0QfVdCofSzBUqQDGQkn8FDRlRBa_V1Hd9wp0/edit

When using Blockchain as a Service (BaaS), the key problem is data ingestion which is concentrated, in most cases, through a single endpoint, thereby, effectively centralizing the whole process even with the decentralization property of blockchain. This is counterintuitive. The paper proposes complete decentralization by proposing multiple ingestion data points and a mechanism to achieve consensus in such cases. The framework is elaborated in the context of Energy Demand Response (Demand Response, in simple words, means that one gets paid for reducing his/her power consumption during peak demand time).

This would be interesting for SCRF because it deals with a completely different paradigm of application, compared to bit monotonous offering of RS' dealing with the topics of finance and pure blockchain.

**Comment by jamesmcgirk** [comment]
@drvarun here you go (he asked me to ping)

**Comment by encore9870** [comment]
I'm closing all issues that are not actively being worked on. Reach out to me if you have questions!
