### ISSUE TITLE
Discussion post on strategies to mitigate flash loan attacks

### ISSUE THREAD

**Issue by lpassos** [smartcontractresearchforum/research_content#115]
**Idea**

Flash loan attacks are a plague for smart contracts devs and users. There are, however, some strategies in place to mitigate flash loan attacks, although not yet captured in a single place.

Hopefully, we could get that discussion started. Publishing it on SCRF could bring more traction to the forum.

**Why is this important?**
- Flash loan attacks are one of the major causes for attacks in the Defi ecosystem
- Not all devs are aware on how to mitigate these attacks

**Comment by visavishesh** [comment]
@lpassos what's the game plan on this one?

**Comment by lpassos** [comment]
@visavishesh It was on hold for a long time. Back to it this week.

**Comment by cipherix** [comment]
https://docs.google.com/document/d/1z5wWiE0lVJO83WxEZXhCNvexItEgSjS4oHyKqKNimF4/edit

**Comment by cipherix** [comment]
@jamesmcgirk ready for editorial review

**Comment by jamesmcgirk** [comment]
I'll take care of the GtM

**Comment by zubepaul** [comment]
Engagement team review completed.

**Comment by jamesmcgirk** [comment]
Undergoing a final technical check per @lpassos request, once @cipherix approves it can be published

**Comment by zubepaul** [comment]
@cipherix completed the requested technical review for @lpassos and cleared it. This discussion post is ready to be published.
