### ISSUE TITLE
Research Summary: "Tornado Cash"

### ISSUE THREAD

**Issue by 29988122** [smartcontractresearchforum/research_content#117]
https://www.smartcontractresearch.org/c/post-ideas/23
Somehow I cannot post in the Post Ideas section on the SCRF forum - lack of permission I suppose. So I'll put it here at the moment I guess.

Paper: 
https://tornado.cash/Tornado.cash_whitepaper_v1.4.pdf
https://tornado.cash/audits/TornadoCash_cryptographic_review_ABDK.pdf
https://tornado.cash/audits/TornadoCash_circuit_audit_ABDK.pdf

Pitch:
Although it's not strictly a research paper nor a fancy innovative project (zk merkle tree opening/path proofs), it can be a great way for our audience (regular engineers, researchers not belong to zk area) to "enlighten" themselves on mixing/shielded transactions on Blockchains.

Something like: understand the security assumptions, "cautions before use" (we all know that we researchers build the project and expect users to use it "correctly" without learning, which is far from the truth. Hard to build a product that is secure even for reckless users), and in the end, the correct way to use it (tornado cash and alikes, privacy transaction solutions), hopefully.

```
A longer version (also on the forum):
Tornado cash uses zk merkle tree opening/path proofs as its foundation, like zcash.
This post shall introduce tornado cash as a native way to unlink any previous transactions on Ethereum mainnet.

It can be a great way (*popsci*) for people to have a better understanding on how to use mixing/shielded transaction 
solutions *correctly* i.e., without voiding the security benefits that the project provided, on Blockchain.

The usage of such...I can think of one. 
If your legal dept ask your ethereum address to be absolutely clean i.e., without previous transactions - 
because they worried that the funds that were in/out of the address could be illegal or against the tax law - 
you may have a slim chance to persuade your legal dept that: since any transaction out from tornadocash contract are 
(under certain assumptions) unlinkable to any of the input transaction, the funds are *clean* now.

Just an imaginary scenario though.
```

Please be aware that this idea pitch has a 5-minute corresponding video in the follow path:
![圖片](https://user-images.githubusercontent.com/5474709/115963949-77c27280-a554-11eb-9249-7bec89986ab2.png) 
as I cannot attend the monday meeting due to timezone discrepancies.

**Comment by 29988122** [comment]
@jamesmcgirk Please mention this idea and play the video in the monday meeting, and inform me the discussions/outcome. Thanks!

**Comment by jamesmcgirk** [comment]
Of course!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ghettodev** [comment]
I've added you to the Research Team in the forum, you should be able to post there now @29988122

**Comment by 29988122** [comment]
temporarily on halt as suggested by 
![圖片](https://user-images.githubusercontent.com/5474709/116653550-00f50180-a9ba-11eb-86a1-ee2d273970e3.png)
Will be back after we have more interest/paper for mixers.

**Comment by twan-dev** [comment]
Jerry is busy so we're closing this now

**Comment by 29988122** [comment]
For reference: closed atm, but tornado cash is still the best working decentralized politically correct DAO governed on chain mixer (so many title lul) in my humble opinion.

Will reopen it if we have changes in this mixer category e.g., L2 shielded transaction is matured and tornado cash is changing/evolving.
