### ISSUE TITLE
Research Summary: Testbed Design and Performance Analysis for Multilayer Blockchains

### ISSUE THREAD

**Issue by SethAustinHarding** [smartcontractresearchforum/research_content#118]
Comprehensive performance analysis for multilayer blockchains

Will be released to web soon...
Published to IEEE ICBC 2021: https://icbc2021.ieee-icbc.org/program

**Comment by jamesmcgirk** [comment]
@SethAustinHarding same question for this one, did Lucas sign off on it yet?

**Comment by SethAustinHarding** [comment]
Thanks!

**Comment by twan-dev** [comment]
Drafting is currently not in progress. Closing this for now.
