### ISSUE TITLE
Research Summary: Comparison of three papers (see below)

### ISSUE THREAD

**Issue by SethHasi** [smartcontractresearchforum/research_content#119]
Bitcoin: A Peer-to-Peer Electronic Cash System (2008)
vs.
Where Is Current Research on Blockchain Technology?—A Systematic Review (2016)
vs.
A survey of breakthrough in blockchain technology: Adoptions, applications, challenges and future research (2021)

**Comment by jamesmcgirk** [comment]
Moving this one to the Ice Box bc of in activity, @SethAustinHarding let me know if you want me to revive it -- doesn't quite fit a standard model of a summary, could possibly be a discussion post

**Comment by encore9870** [comment]
I'm closing all issues that are not actively being worked on. Reach out to me if you have questions!
