### ISSUE TITLE
Research Summary: "The decentralized financial crisis"

### ISSUE THREAD

**Issue by lpassos** [smartcontractresearchforum/research_content#12]
**What is this paper about?**
This paper discusses the risks of financial loss in the DeFi ecosystem; by abstracting over an attack vector over Maker's governance design, the authors propose a framework to stress test a stylized lending protocol, showing how specific parameters could make the protocol under-collaterized.  

**Why is it important?**
It provides auditors and security minded folks with an analysis framework when inspecting a lending protocol. Also, it aligns with the following SCRF goals: content creation & engagement potential. Draining lending protocols puts users' funds at risk, and therefore, a framework to stress test such possibility is a much needed resource.

PDF at: https://arxiv.org/pdf/2002.08099

**Comment by lpassos** [comment]
Update: this will be delayed to next week, as I was not able to put efforts on this front.

**Comment by lpassos** [comment]
WIP: https://docs.google.com/document/d/1M_oBMmbJ2iHqmcoj3qEF_BS4iy9ilLT3FKnc0xBP9x8/edit?usp=sharing

**Comment by jamesmcgirk** [comment]
@cipherix @lpassos - let me know when this is ready for editorial review

**Comment by jamesmcgirk** [comment]
@lpassos looks really good, I tried making the TLDR a little easier to read, please have a look to make sure I didn't alter the meaning. Other than that it was in good shape, made a few formatting changes

**Comment by ghettodev** [comment]
Summary tweeted: https://twitter.com/SCRForum/status/1375497748972113924

**Comment by zubepaul** [comment]
Go to market implemented. This now moves to routine thread monitoring and maintenance.

**Comment by zubepaul** [comment]
Changed engagement priority to 4
