### ISSUE TITLE
Massimo Bartoletti: Technical Interview

### ISSUE THREAD

**Issue by jamesmcgirk** [smartcontractresearchforum/research_content#120]
We have a series of Bartoletti's papers on the forum - BitML and Bitcoin Covenants. I'd like to solicit some questions from our experts (or perhaps facilitate an interview) and create a standalone 'technical interview' for the Forum.

Think of this as a Use Case without a research summary attached.

**Comment by jamesmcgirk** [comment]
Tooling and languages tag

**Comment by jamesmcgirk** [comment]
Clara is reaching out to Bartoletti on 5/5. If he responds, I'll begin drafting some context for the interview.

**Comment by cipherix** [comment]
Closing this in light of our convo
