### ISSUE TITLE
Research Summary: Blockchain is Watching You: Profiling and Deanonymizing Ethereum Users

### ISSUE THREAD

**Issue by 29988122** [smartcontractresearchforum/research_content#121]
Suggested here:

https://www.smartcontractresearch.org/t/post-idea-tornado-cash/366/7?u=jerry_ho

And I do agree it's worth reading & having a summary for it.

**Comment by 29988122** [comment]
adding on-board ilnk:
https://www.smartcontractresearch.org/t/post-idea-blockchain-is-watching-you-profiling-and-deanonymizing-ethereum-users/391

**Comment by zubepaul** [comment]
Assigned as Engagement Team

**Comment by 29988122** [comment]
@cipherix Ready to be reviewed.

https://docs.google.com/document/d/1jypTBhrXUUiiC-8HzMOrjO7a6IRud-Dx3JySUX9TgTo/edit

**Comment by jamesmcgirk** [comment]
Assigning myself as Engagement

**Comment by jamesmcgirk** [comment]
@29988122 I made some edits if you'd like to review them

**Comment by jamesmcgirk** [comment]
@zubepaul this one is ready for engagement, interview complete, GtM should be ready CoB today
