### ISSUE TITLE
Research Summary: Everlasting Options

### ISSUE THREAD

**Issue by tina1998612** [smartcontractresearchforum/research_content#132]
https://www.paradigm.xyz/2021/05/everlasting-options/

- Google doc: https://docs.google.com/document/d/11Km2dhh5D1pJudBkDQg3nWmLosJ4dOClH8IV3X0SbhU/edit

**Comment by jamesmcgirk** [comment]
moving this into the icebox @tina1998612 feel free to move it back (although I'm sure you're busy at your new job)

**Comment by encore9870** [comment]
I'm closing all issues that are not actively being worked on. Reach out to me if you have questions!
