### ISSUE TITLE
Research Summary: Convergence of Blockchain, IoT, and AI

### ISSUE THREAD

**Issue by SethHasi** [smartcontractresearchforum/research_content#136]

**Comment by zubepaul** [comment]
Assigned as engagement team.

**Comment by Coinproz** [comment]
Link to article:

https://www.frontiersin.org/articles/10.3389/fbloc.2020.522600/full

**Comment by jamesmcgirk** [comment]
How's this one coming along?

**Comment by jamesmcgirk** [comment]
published! https://www.smartcontractresearch.org/t/research-summary-convergence-of-blockchain-iot-and-ai/579 needs a gtm

**Comment by jamesmcgirk** [comment]
I'm creating a document for my edits, @Gearlad you can copy and paste from my doc: [here](https://docs.google.com/document/d/1PT6BIt16qp7dXVDs5fKJId9EN1fxQaUAEhZBWVrTu84/edit)

**Comment by jamesmcgirk** [comment]
Deane had a couple of others to add. Working on GTM
