### ISSUE TITLE
Mini Post: BitML Interview

### ISSUE THREAD

**Issue by cipherix** [smartcontractresearchforum/research_content#137]
https://docs.google.com/document/d/1N7Bc7JPyjm2tjJQdMQ-GXXaRhmXkbb4acnHfvxvva6c/edit?usp=sharing

**Comment by jamesmcgirk** [comment]
@cipherix finished with my review. I made a few wording suggestions, please feel free to revert. Once these are done, this should be ready for publication. Looks great btw!
