### ISSUE TITLE
Mini Post: Sociology and the Blockchain

### ISSUE THREAD

**Issue by jamesmcgirk** [smartcontractresearchforum/research_content#139]
Intending this to be a slight deviation from the regular discussion post, will contain the results of a couple of conversations with prominent blockchain-affiliated anthropologists and sociologists plus links to papers.

**Comment by jamesmcgirk** [comment]
[Draft in progress](https://docs.google.com/document/d/1aQVTkuGG2m3brLlPNYe0Als1ZpHqIuOfecb7sU6-mQk/edit#)

**Comment by jamesmcgirk** [comment]
I've asked Kelsie to peer review this.

**Comment by jamesmcgirk** [comment]
Feels a bit dirty to edit myself... but this one is ready for engagement, will work on a strategy and answer questions

**Comment by jamesmcgirk** [comment]
Need to add an another researcher

**Comment by jamesmcgirk** [comment]
Ready for GtM

**Comment by zubepaul** [comment]
GTM document created and ready for author meeting. We can either do a meeting or you could go to the GTM tracker and add some thoughts on the Social Outreach consideration sections. @jamesmcgirk, please review the top portion of the doc to see if this reflects your intentions.

**Comment by jamesmcgirk** [comment]
Added some socials

**Comment by zubepaul** [comment]
Engagement review completed. Ready to publish.

**Comment by jamesmcgirk** [comment]
Published, closing issue (also reordered the names per Kelsie's suggestion)
