### ISSUE TITLE
Add audit report summary for Teku

### ISSUE THREAD

**Issue by lpassos** [smartcontractresearchforum/research_content#14]
**Goal**
Provide an audit summary for the Teku Eth2 client. 

**Why is this important?**
Eth2 is the next big thing in the Ethereum network, where shards will be introduced with the aim of achieving higher network throughput

Report at: https://certificate.quantstamp.com/full/teku

**Comment by lpassos** [comment]
First summary draft available at: https://docs.google.com/document/d/1aNxX1NPU3iwd63XshZB0gjFoWvLrSTkGwbSaYjj_a1Q/edit?usp=sharing

**Comment by visavishesh** [comment]
We should add key takeaways

**Comment by jamesmcgirk** [comment]
Still missing a TL;DR (do we need one?), fixed a few spacing issues but otherwise flawless. Moving over to Calendaring

**Comment by jamesmcgirk** [comment]
Leo said he'll add a TL;DR, moved this back to Editiing

**Comment by lpassos** [comment]
@jamesmcgirk TLDR added; please take a look again.

**Comment by jamesmcgirk** [comment]
Thanks, @lpassos looks good. I'll move to calendaring

**Comment by lpassos** [comment]
Thanks :)

**Comment by cipherix** [comment]
I like the minimalistic TLDR, @lpassos -- seems like we can use this as an example of an audit summary TLDR that simply restates the audit's finding (as opposed to an analysis-centric TLDR, which as we discussed may open up a can of worms).

**Comment by lpassos** [comment]
@cipherix Sounds good to me :)

**Comment by visavishesh** [comment]
@lpassos good to post

**Comment by lpassos** [comment]
@visavishesh There are some blockers that should be addressed prior to publishing this:
- There are no tags specifically targeting audit summaries (and I cannot add them)
- There are no intro texts for the subcategories under the Audit & Security Page, namely [Audit](https://www.smartcontractresearch.org/c/auditing-and-security/audits/19), [Standards](https://www.smartcontractresearch.org/c/auditing-and-security/standards/18), and [Postmortems](https://www.smartcontractresearch.org/c/auditing-and-security/postmortems/20). I think we did not track these, and they were untouched from the very beginning.
Please advise.

**Comment by lpassos** [comment]
After a few discussions on Discourd (see https://discord.com/channels/784234332617048065/784234333111451670/808043614096719902), this is now posted.
