### ISSUE TITLE
Research Summary: Non-Fungible Token (NFT): Overview, Evaluation, Opportunities and Challenges

### ISSUE THREAD

**Issue by lpassos** [smartcontractresearchforum/research_content#141]
## Steps to completion

- [ ] Provide context/background for broader narrative
- [ ] GTM section filled out
- [ ] Editing step completed
- [ ] Proposed tags
- [ ] Glossary items captured
- [ ] Post GTM Meeting

---

## Title 
Non-Fungible Token (NFT): Overview, Evaluation, Opportunities and Challenges

## Link to source

https://arxiv.org/pdf/2105.07447.pdf

## Assignee

@lpassos 

## Size of task tag (small, medium, large)

Medium

## Description of why this is good for SCRF

This paper attempts to bring a full perspective on NFTs, which is currently a hot topic in the crypto space. This post could be a starting point to those starting on NFTs, as well as those willing to understand a bit more of its cons/pros.

**Comment by twan-dev** [comment]
First draft scheduled to be turned in on May 9, 2022

**Comment by encore9870** [comment]
Reopening when we settle with a new author to take over the draft
