### ISSUE TITLE
Research Summary: MEV-SGX: A sealed bid MEV auction design

### ISSUE THREAD

**Issue by Siemingfong** [smartcontractresearchforum/research_content#142]
Here is my summary:
https://docs.google.com/document/d/1HEE_9jycMtP9nUPE2ssLV120kaLaeLlMR2lnlShm0Wg/edit?usp=sharing

**Comment by jamesmcgirk** [comment]
@Siemingfong are you working on another version of this? Or is the version in post ideas the final version?

**Comment by Siemingfong** [comment]
@jamesmcgirk This is the final version. I'm working on another summary.

**Comment by jamesmcgirk** [comment]
Thanks, @Siemingfong

**Comment by jamesmcgirk** [comment]
@cipherix looks like Sean has completed a draft of this one... let me know if it should go into drafting/peer review

**Comment by jamesmcgirk** [comment]
Moving this one over to peer review

**Comment by jamesmcgirk** [comment]
@Astridchou is this something you'd like to peer review?

**Comment by Astridchou** [comment]
@jamesmcgirk I'd love to do it! Thanks!

**Comment by jamesmcgirk** [comment]
@Siemingfong just checking up on this one -- do you need anything?

**Comment by twan-dev** [comment]
Sean is planning to spin this out into a discussion post. Closing this one and we'll have another ticket that reflects the work of the discussion post.
