### ISSUE TITLE
Research Summary on Arbitrum

### ISSUE THREAD

**Issue by cipherix** [smartcontractresearchforum/research_content#145]

**Comment by jamesmcgirk** [comment]
@Coinproz updated with https://docs.google.com/document/d/1uWeHCyHSC0p1MjRawsws7k6CqhB9iAGE0j2sL3AacDU/edit moving to Drafting

**Comment by cryptohazard** [comment]
first version of the draft done.

**Comment by lw-scrf** [comment]
@cryptohazard, not sure if i'm supposed to take a look at this for 'peer review' or if this is lucas'/others domain...just let me know. either way, i'm looking forward to reading this research summary.

**Comment by jamesmcgirk** [comment]
You’re welcome to take this one as a peer review!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by lw-scrf** [comment]
@jamesmcgirk cool. just didn't want to step on any toes, as a new kid. will take a look.

**Comment by lw-scrf** [comment]
i started doing some proofreading and decided that i should focus on content and leave proofreading for later aka the editorial review step. 

@cryptohazard interesting read so far. look forward to reading the rest and possibly entire paper when/if i have time...

**Comment by jamesmcgirk** [comment]
@flyinglimao would you like to take a look at this one for peer review?

**Comment by jamesmcgirk** [comment]
@cryptohazard would this go in the 'scaling' category? Or mech design?

**Comment by twan-dev** [comment]
This one is has already been published to the forum. Should we move it out of the pipeline?

https://www.smartcontractresearch.org/t/research-summary-arbitrum-fast-scalable-private-smart-contracts/885
