### ISSUE TITLE
Research Summary: A Bytecode-based Approach for Smart Contract Classification

### ISSUE THREAD

**Issue by albert-moos** [smartcontractresearchforum/research_content#149]
With the development of blockchain technologies, the number of smart contracts on blockchain platforms is
growing exponentially, which makes it difficult for users to find desired services by manual screening. Therefore, The automatic classification of smart contracts is urgent, but it also needs to overcome the obstacle that most smart contracts on-chain aren't open source. The author of the paper provides a bytecode-based approach classification that fits the criteria of Novelty.

**Comment by jamesmcgirk** [comment]
@albert-moos this one needs a link to the original article

**Comment by twan-dev** [comment]
Albert doesn't expect to work on this ticket in the near future.
