### ISSUE TITLE
tebogo project

### ISSUE THREAD

**Issue by Coinproz** [smartcontractresearchforum/research_content#150]
project

http://dx.doi.org/10.2139/ssrn.3458877

Draft link:
https://docs.google.com/document/d/12llPOsui73j8E7B41GbVM0yisX34m_7n6F5wokBS5aQ/edit

**Comment by zubepaul** [comment]
GTM questions added to the draft.

**Comment by jamesmcgirk** [comment]
This is looking good! I'll take a glance tomorrow but it's basically ready @Coinproz
