### ISSUE TITLE
Discussion Post - Taming Wildcast Stablecoins

### ISSUE THREAD

**Issue by jamesmcgirk** [smartcontractresearchforum/research_content#151]
The following paper [Taming Wildcat Stablecoins](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3888752 ) has been widely circulated and has been cited by Nobel prize-winning economists. It would be interesting to frame it as a debate with some of the retorts that have been made. The idea would be to refute with citations some of claims made and perhaps begin an informed discussion about the difference between the free banking era and stable coins

**Comment by jamesmcgirk** [comment]
Suggest [Why Central Bankers Invoke Free Banking](https://www.coindesk.com/why-central-bankers-invoke-free-banking-attack-stablecoins) as a retort

**Comment by jamesmcgirk** [comment]
I think Stablecoins vs Central Bank Digital Currency could be an interesting narrative to keep track of

**Comment by Siemingfong** [comment]
Great paper

**Comment by jamesmcgirk** [comment]
@Siemingfong I got the idea for you, I remember you posted it in the forum I think

**Comment by Siemingfong** [comment]
No problem. Coming to learn more

**Comment by Siemingfong** [comment]
I create the draft and co-working with @ Astridchou
https://docs.google.com/document/d/1vLbxxn2jV3RtAXT-5827fuDfXIl3fRfkjsf5e6Exubk/edit?usp=sharing

**Comment by jamesmcgirk** [comment]
Thanks, @Siemingfong I think this will be a great one for co-working with @Astridchou cc'd to @cipherix 
I will take charge of the engagement for this one... do you need access to the discussion post template?

**Comment by Siemingfong** [comment]
Sure, really need discussion post template.

**Comment by jamesmcgirk** [comment]
@Siemingfong https://docs.google.com/document/d/17QZXP1ut3LnFtCbt8Iac7_abULXdGe0k2CEPU1J_sMo/edit (we just added it to HackMD, but just in case you don't have access)

**Comment by Siemingfong** [comment]
@jamesmcgirk Thanks!

**Comment by jamesmcgirk** [comment]
Astrid replaced the above link with this one (which is far more extensive): https://docs.google.com/document/d/1vLbxxn2jV3RtAXT-5827fuDfXIl3fRfkjsf5e6Exubk/edit

**Comment by jamesmcgirk** [comment]
@cipherix - this one is ready for your review, I'm moving it past Peer Review into Content Review because Astrid and Sean peer edited it.

**Comment by jamesmcgirk** [comment]
@Siemingfong can you please transfer this doc into our Google Drive when you get a chance please

**Comment by Siemingfong** [comment]
@jamesmcgirk I transfer the doc content to SCRF Google Drive as original link
https://docs.google.com/document/d/1yoAGZoHKCCZIs0Wry_qPpuUf35qR4r8le7xpXFY_PiM/edit?usp=sharing

**Comment by jamesmcgirk** [comment]
thank you!

**Comment by jamesmcgirk** [comment]
@Siemingfong @astridchou nice work on this one, I made a few edits which you should review with Astrid, I want to make I didn't change the meaning of anything. Should be a controversial article for our forum!

**Comment by jamesmcgirk** [comment]
@astridchou had some questions, I addressed them in the doc and finalized the changes. Answers to engagement questions to come.
