### ISSUE TITLE
Research Summary: Governing Decentralized Complex Queries Through a DAO

### ISSUE THREAD

**Issue by jamesmcgirk** [smartcontractresearchforum/research_content#152]
Description: This was a research pulse suggestion that Astrid Chou has volunteered to write a summary of.

Authors: Mirko Zichichi, Luca Serena, Stefano Ferretti, and Gabriele D’Angelo 

[Link to article](https://arxiv.org/pdf/2107.06790.pdf)

**Comment by Siemingfong** [comment]
I create a new doc that could co-work with @astridchou together
https://docs.google.com/document/d/1QXj-iL2HVk03X6-4JH647-cLf8zKVNrVOxxnF_3fuOA/edit?usp=sharing

**Comment by jamesmcgirk** [comment]
@cipherix ready for peer review, maybe something Kelsie might be interested in?

**Comment by jamesmcgirk** [comment]
@29988122 would you like to do a peer review of this one?

**Comment by 29988122** [comment]
Take a brief look at it - out of my area, and unlikely that I'll be able to review the correctness of the digest given limited learning time.

Better leave it to others this time!

**Comment by jamesmcgirk** [comment]
@SethAustinHarding would you like to do a review of this one?

**Comment by jamesmcgirk** [comment]
@lw-scrf would you like to edit this one as well?

**Comment by lw-scrf** [comment]
> @lw-scrf would you like to edit this one as well?

will give it a look, but also not familiar with this topic...will get back if i think someone else should...

**Comment by jamesmcgirk** [comment]
thanks so much! Much appreciated

**Comment by jamesmcgirk** [comment]
Please refer to the following [card](https://github.com/smartcontractresearchforum/research_team/issues/157)

**Comment by jamesmcgirk** [comment]
@flyinglimao this might be an interesting one to peer review

**Comment by cipherix** [comment]
Change some areas for clarity on hypercube topologies. Overall a very nice job summarizing a complex paper, moved it to editorial review @jamesmcgirk

**Comment by jamesmcgirk** [comment]
@Astridchou added in the GtM questions and completed an edit, I'd like to take another look through it once you've approved the changes (the last few sections were pretty dense, so I want to make sure I haven't missed anything)

**Comment by jamesmcgirk** [comment]
@twan-dev @zubepaul tagging you both for engagement assignment

**Comment by Astridchou** [comment]
I have finished the requirements of @jamesmcgirk 's review (I used yellow highlight to mark my amendment and left a response to a comment) and the GTM questions.

**Comment by jamesmcgirk** [comment]
@Astridchou thank you for fixing those, I'll get the GtM started.

**Comment by jamesmcgirk** [comment]
@Astridchou - we've formalized our citation procedure, so I'm moving your second citation to a further reading section

**Comment by Astridchou** [comment]
@jamesmcgirk Thanks!

**Comment by jamesmcgirk** [comment]
Editorial review complete. GtM in progress.

**Comment by jamesmcgirk** [comment]
GtM complete! @Astridchou do you have time for either a brief interview over Google meet or over Discord to talk about engagement before Thursday?

**Comment by zubepaul** [comment]
@twan-dev @Astridchou Engagement review completed. Can be published no sooner than December 15th, 2021

**Comment by jamesmcgirk** [comment]
@Astridchou see Paul's note above, you're welcome to publish

**Comment by Astridchou** [comment]
@jamesmcgirk Thanks for your reminder. I can't get in the google doc, so I'm asking for its access right now.

**Comment by Astridchou** [comment]
I have published it. Big thanks to everyone who makes this completed.
