### ISSUE TITLE
Discussion Post: Autopsy of RED Wednesday - how AAVE, Chainlink and other protocols fared during the largest single day drop since X

### ISSUE THREAD

**Issue by jamesmcgirk** [smartcontractresearchforum/research_content#154]

**Comment by Siemingfong** [comment]
I think part of this situation is well explained in Liquidity risks in the decentralized finance protocol Aave. 
This paper defines the deflationary spiral and safety model. But it still suffers the liquidity leak from stakeholders.
https://github.com/smartcontractresearchforum/research_content/issues/146

**Comment by jamesmcgirk** [comment]
Assigned to @Siemingfong who found some information and statistics about safety modules in his AAVE liquidity paper -- want to expanding on these ideas related to "Red Wednesday", which will provide some interesting content cc'd to @cipherix

**Comment by jamesmcgirk** [comment]
I'll assign myself as engagement

**Comment by jamesmcgirk** [comment]
Has this ticket been replaced by 146? @Siemingfong are you using https://github.com/smartcontractresearchforum/research_content/issues/146 instead? (If so I'll get rid of this one)

**Comment by Siemingfong** [comment]
@jamesmcgirk I think yes, this topic mention in #146 for the AAVE protocol part. But it was not compared to others protocols.

**Comment by jamesmcgirk** [comment]
Thanks, I'll close this one
