### ISSUE TITLE
Research Summary: Efficient Attribute-Based Smart Contract Access Control Enhanced by Reputation Assessment

### ISSUE THREAD

**Issue by SethHasi** [smartcontractresearchforum/research_content#155]
Paper Link: https://arxiv.org/abs/2107.00679#:~:text=Efficient%20Attribute%2DBased%20Smart%20Contract%20Access%20Control%20Enhanced%20by%20Reputation%20Assessment,-Yang%20Liu%2C%20Terry&text=It%20provides%20basic%20access%20control,to%20cope%20with%20malicious%20behaviors.

Summary Draft: https://docs.google.com/document/d/1jTv_LKLZLKMFlBl3XqXc_jOkAqybouPPInZVdbHSnJE/edit?usp=sharing

**Comment by jamesmcgirk** [comment]
@cryptomarabout - here's a summary you might be interested in summarizing

**Comment by SethAustinHarding** [comment]
@jamesmcgirk We've finished this summary and it's ready for peer review

**Comment by jamesmcgirk** [comment]
Thanks @SethAustinHarding - this one came from the Research Pulse. @cryptomarabout would this be something you'd be interested in peer reviewing?

**Comment by cryptomarabout** [comment]
Ok I will take a look during next week as I am not available during next days.

**Comment by jamesmcgirk** [comment]
@cryptomarabout actually, let me give this one to @Astridchou -- I've assigned you to a couple of other ones

**Comment by Astridchou** [comment]
Doing the peer review now

**Comment by zubepaul** [comment]
Assigned as engagement. @ralphlombreglia @virtualtart

**Comment by Astridchou** [comment]
Peer review has been completed.

https://docs.google.com/document/d/1jTv_LKLZLKMFlBl3XqXc_jOkAqybouPPInZVdbHSnJE/edit#

**Comment by jamesmcgirk** [comment]
@cipherix ready for your review

**Comment by cipherix** [comment]
Hey @SethAustinHarding -- could you please resolve Astrid's comments on the doc? Also, please me an editor of the doc so that I can begin the editing process. Thank you!

**Comment by jamesmcgirk** [comment]
Still needs edits to be accepted @SethAustinHarding please let me know when this is ready for FCR

**Comment by twan-dev** [comment]
@SethAustinHarding is this ready for FCR? It's looking good to me.

**Comment by SethAustinHarding** [comment]
@twan-dev Yep! It's ready.

**Comment by twan-dev** [comment]
- [x] All comments from Peer Reviewers have been discussed and addressed by authors. 
- [x] All suggestions provided by Peer Reviewers have been resolved.

**Comment by cipherix** [comment]
Left some comments there for you @SethAustinHarding

**Comment by cipherix** [comment]
Any updates on this @SethAustinHarding ?

**Comment by SethAustinHarding** [comment]
Hi @cipherix and @twan-dev, Cindy (https://github.com/jyue) is not added to the SCRF Github team but she said she will handle the edits within the next 24 hours. Can she directly post this after finishing addressing your comments?

**Comment by twan-dev** [comment]
@SethAustinHarding yes she can. Doesn't need to be onboarded to Github. Moving back to peer review until the comments are resolved.

**Comment by twan-dev** [comment]
> Can she directly post this after finishing addressing your comments?

no. Sorry for not clarifying this.

**Comment by twan-dev** [comment]
@SethAustinHarding Let us know in the document the intended category and appropriate tags to this summary. Please also review the edits and suggestions. If it looks good to you the draft should be ready for another FCR.

**Comment by twan-dev** [comment]
- [x] All comments from Peer Reviewers have been discussed and addressed by authors. 
- [x] All suggestions provided by Peer Reviewers have been resolved.

**Comment by zubepaul** [comment]
@zubepaul @twan-dev @marvino3 are all assigned as Engagement/GTM for this summary.

**Comment by zubepaul** [comment]
@SethAustinHarding The GTM questions have been added to the top of your summary draft document. As you are working through the review stages, please answer these questions as best as possible to help generate a strategy to engage with the research you are summarizing. Please tag me when you have initially answered them or have questions.

**Comment by cipherix** [comment]
This summary seems ready for Editorial. Thank you for working on the suggested improvements, moving to Editorial Review.

**Comment by jamesmcgirk** [comment]
@SethAustinHarding looks good, a few edits for you to check. Looking forward to the GtM answers but saw your note re: 2/8 date

**Comment by jamesmcgirk** [comment]
@SethAustinHarding any update on the GtM questions?

**Comment by SethAustinHarding** [comment]
@jamesmcgirk yes - only the first question has been answered so far, but Cindy and I will be meeting on the 20th (10 days) to answer the remaining questions.

**Comment by SethAustinHarding** [comment]
> @jamesmcgirk yes - only the first question has been answered so far, but Cindy and I will be meeting on the 20th (10 days) to answer the remaining questions.
This has been delayed by several days - Cindy has a Google interview and her birthday is today, just as her thesis's final copy is being prepared...

**Comment by zubepaul** [comment]
Thanks for completing the GtM questions. I have started the GtM doc and will reach out to @SethAustinHarding to set up the review meeting. @marvino3 This is the stage that you potentially wanted to be part of, correct?

**Comment by zubepaul** [comment]
GtM Complete. Reading to schedule meeting with researchers @SethAustinHarding

**Comment by zubepaul** [comment]
@twan-dev @SethHasi Engagement review completed. During review, a few additional typos were found, but will be corrected prior to publication. Approved for publication on forum no sooner than March 4, 2022
