### ISSUE TITLE
Discussion Post: “A Curated List of Threats to Decentralization”

### ISSUE THREAD

**Issue by cryptomarabout** [smartcontractresearchforum/research_content#161]
https://docs.google.com/document/d/1IKlqUKokuUn3X3DCE3Rv6e1J984nM7GCxk3bq-K44P4/edit

**Comment by jamesmcgirk** [comment]
@cipherix this one should be ready for you

**Comment by jamesmcgirk** [comment]
Deleted my previous comment. Discussion Post will be revised. Moving back to Peer Review.

**Comment by jamesmcgirk** [comment]
Still waiting for the prospectus to be completed.

**Comment by jamesmcgirk** [comment]
Prospectus completed! @cryptomarabout have you made significant changes to this? (Or are you planning on doing them?)
