### ISSUE TITLE
Research Summary: The Rise of Decentralized Autonomous Organizations: Opportunities and Challenges

### ISSUE THREAD

**Issue by Fizzymidas** [smartcontractresearchforum/research_content#163]
As more companies and businesses go fully remote, their coordination could also become internet native. DAOs could disrupt current legally recognized coordination. 

Link to draft: https://docs.google.com/document/d/10odGd-c1L_BdfTtDk-BTkBbc-alcYveewFpOb2ONV2M/edit?usp=sharing

**Comment by jamesmcgirk** [comment]
From a [Dec 20th, 2020 research pulse](https://www.smartcontractresearch.org/t/research-pulse/145/4 )

**Comment by twan-dev** [comment]
Discussed with Faith and she agrees as well that it's not longer the best choice for a research summary.
