### ISSUE TITLE
SoK: Applying Blockchain Technology in Industrial Internet of Things

### ISSUE THREAD

**Issue by albert-moos** [smartcontractresearchforum/research_content#164]
Most existing industrial IoT (IIoT) implementations, however, are still relying on a centralized architecture, which is vulnerable to the single point of failure attack and requires a massive amount of computation at the central entity. By introducing blockchain technology it could address the issues mentioned above.
Therefore, it fits the category of Novelty. That's why we should work on this paper summary.

**Comment by jamesmcgirk** [comment]
Albert asked me to paste this: https://docs.google.com/document/d/1YwWyp7T49vTwPjnpQ2hAKKXKPGx1A09PAlnyqbxqFKs/edit?usp=sharing

**Comment by jamesmcgirk** [comment]
@cipherix another paper suggestion from the AI IoT group for your consideration

@albert-moos who is working on this draft?

**Comment by rjx223** [comment]
Hi @jamesmcgirk 
I have taken full responsibility for this summary and after consulting with Deane, believe it should be ready to move on to the next phase.  According to our AIoT spreadsheet, this article was included in a research pulse.  Thank you!

**Comment by jamesmcgirk** [comment]
Thanks so much, Rachel! I’ll find a peer reviewer for you, unless you have someone in mind

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by rjx223** [comment]
Sounds good, thanks @jamesmcgirk

**Comment by jamesmcgirk** [comment]
@Astridchou here's another one for you to peer review :)

**Comment by Astridchou** [comment]
Great! I'll do it after the peer review of #155! Thanks @jamesmcgirk

**Comment by jamesmcgirk** [comment]
@Astridchou another one for you to peer edit

**Comment by jamesmcgirk** [comment]
@albert-moos @rjx223 can you please open this one up for editing access

**Comment by rjx223** [comment]
@jamesmcgirk should be accessible now. Thanks

**Comment by rjx223** [comment]
@Astridchou Reviewed your suggestions and comments and made some revisions accordingly. Thanks :)

**Comment by jamesmcgirk** [comment]
@cipherix ready for your review!

**Comment by cipherix** [comment]
Excellent job on this one @albert-moos. Made a few changes and added minor comments for clarity. Will move to editorial review.

**Comment by albert-moos** [comment]
Ok thank you

**Comment by rjx223** [comment]
Hi @cipherix 
I appreciate your feedback and encouragement.  With respect, I wanted to clarify that I am the sole author of this summary.  Thanks again!  Kindly, Rachel

**Comment by jamesmcgirk** [comment]
assigned myself for engagement

**Comment by jamesmcgirk** [comment]
Good job! @rjx223  Finished my first edit, I left a couple of things to review and have a couple of minor questions. I also pasted in the GtM questions.

**Comment by jamesmcgirk** [comment]
edits have been made, waiting for engagement questions; interview scheduled for Friday; moved over to engagement

**Comment by twan-dev** [comment]
@jamesmcgirk I talked to Rachel and now she has the GTM questions ready. Would you take a look and make the final edits?

**Comment by twan-dev** [comment]
Humm. Apparently, there were some misunderstandings.

https://www.smartcontractresearch.org/t/research-summary-sok-applying-blockchain-technology-in-industrial-internet-of-things/866
