### ISSUE TITLE
Research Summary: On the Economic Design of Stablecoins

### ISSUE THREAD

**Issue by twan-dev** [smartcontractresearchforum/research_content#166]
Paper Link [Here](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3899499)
Google Docs Link [Here](https://docs.google.com/document/d/1oXTPY0PlBEVX8lE9xZ6OYC-Ty2iB5DlmTfbTono4PpQ/edit?usp=sharing)

This paper proposes shortcomings of the economic designs of stable coins that would bring insight to how to reduce potential risks and gain more mainstream adoption

**Comment by jamesmcgirk** [comment]
@albert-moos would you (and perhaps Jason) like to give some comments to this draft? It's about economics and finance

**Comment by Astridchou** [comment]
Okay. I'll do a peer review of this research summary. I'm interested in the topic, thanks for your invitation.

**Comment by cipherix** [comment]
Great job on this @twan-dev! Left some comments -- will move it to editorial. This is going to be a juicy paper to discuss on the forum.

**Comment by twan-dev** [comment]
@cipherix  Thanks for taking time to read and review the summary! 

I've made the changes to the TLDR. How does this look to you? 

- Stablecoins are at risk of entering a death spiral without reliable backing assets, as the assets will be insufficient to defend the peg and win back market confidence under stressful conditions
- This is especially severe if they are only backed by themselves or other cryptocurrencies
- While fiat-backed stablecoins with appropriate capital buffers have low volatility, only CBDCs have zero risk

**Comment by jamesmcgirk** [comment]
@twan-dev nice work for your first summary! made some suggestions for changes and added some questions from the engagement team for you to answer

**Comment by jamesmcgirk** [comment]
GtM questions completed, @jamesmcgirk to write GtM
