### ISSUE TITLE
Research Summary: Double-Spend Counterattacks: Threat of Retaliation in Proof-of-Work Systems Summary

### ISSUE THREAD

**Issue by albert-moos** [smartcontractresearchforum/research_content#167]
Proof-of-Work mining is intended to provide blockchains with robustness against double-spend attacks. The authors formalize a defense to double-spend attacks.  When the victim can counterattack in the same way as the attacker, this leads to a variation on the classic game-theoretic War of Attrition model. The threat of this kind of counterattack induces a subgame perfect equilibrium in which no attack occurs in the first place.

**Comment by albert-moos** [comment]
https://docs.google.com/document/d/1SY4U4Sw5oBiJCnIecpdMV9p6ysq5vZG6EsIB7YolwIk/edit?usp=sharing
the link to the post idea is above

**Comment by albert-moos** [comment]
Finish drafting and also a fair enough part of the paper ready for peer view

**Comment by jamesmcgirk** [comment]
@Coinproz is this something you'd be interested in peer reviewing?

**Comment by jamesmcgirk** [comment]
@loicdrbx would you like to review this one?

**Comment by jamesmcgirk** [comment]
@loicdrbx @albert-moos did you finish the peer review?

**Comment by loicdrbx** [comment]
I added my suggestions to the doc this morning. I'm meeting with @albert-moos in a couple of hours for a more interactive review.

**Comment by jamesmcgirk** [comment]
Moved this over to final content review @cipherix ready for your review

**Comment by cipherix** [comment]
@albert-moos could you please resolve the comments when you get a chance? thank you!

**Comment by albert-moos** [comment]
No thank u we gonna start editing it based on the advice

**Comment by jamesmcgirk** [comment]
Still waiting for edits to be okayed. @albert-moos let us know when it's ready for FCR

**Comment by twan-dev** [comment]
Shoving to icebox because one of the authors told me that both of them are not interested in working in the draft anymore.   
This summary up for grabs for anyone that wants to continue though!

**Comment by jamesmcgirk** [comment]
@twan-dev I just got a message from Jason - they sent along the following link https://docs.google.com/document/d/1SY4U4Sw5oBiJCnIecpdMV9p6ysq5vZG6EsIB7YolwIk/edit#

**Comment by twan-dev** [comment]
@jamesmcgirk It's the same document as above. 

> https://docs.google.com/document/d/1SY4U4Sw5oBiJCnIecpdMV9p6ysq5vZG6EsIB7YolwIk/edit?usp=sharing
> the link to the post idea is above


> @twan-dev I just got a message from Jason - they sent along the following link https://docs.google.com/document/d/1SY4U4Sw5oBiJCnIecpdMV9p6ysq5vZG6EsIB7YolwIk/edit#

Can you ask them to work with the document pipeline directly as well?

**Comment by twan-dev** [comment]
@jamesmcgirk @albert-moos There's a major update in rules for creating summaries that starts after this month. Please help/let me contact them/you because we don't want them/you to miss important updates that are likely to affect their/your relation with SCRF.

**Comment by encore9870** [comment]
I'm closing all issues that are not actively being worked on. Reach out to me if you have questions!
