### ISSUE TITLE
Research Summary: When Federated Learning Meets Blockchain: A New Distributed Learning Paradigm

### ISSUE THREAD

**Issue by SethHasi** [smartcontractresearchforum/research_content#168]
Paper: https://arxiv.org/abs/2009.09338#:~:text=When%20Federated%20Learning%20Meets%20Blockchain%3A%20A%20New%20Distributed%20Learning%20Paradigm,-Chuan%20Ma%2C%20Jun&text=By%20training%20models%20locally%20at,directly%2C%20thereby%20reducing%20privacy%20leakage.

Research Summary: https://docs.google.com/document/d/1aycAYxylXO4HiIroQljj6rD6gnZAmsbDkoJWO9ouPho/edit

**Comment by jamesmcgirk** [comment]
Is this a research pulse paper?

**Comment by jamesmcgirk** [comment]
I'm moving this back into idea proposal until @cipherix approves
