### ISSUE TITLE
Research Summary: A Comparative Analysis of the Platforms for Decentralized Autonomous Organizations in the Ethereum Blockchain

### ISSUE THREAD

**Issue by Astridchou** [smartcontractresearchforum/research_content#170]
Link to draft:
https://docs.google.com/document/d/1VBL5gUa9DWByxPk29H3h8AbCRRa5HN86B-0EBNRbfM0/edit#

**Comment by jamesmcgirk** [comment]
moved this to drafting stage because it's from the research pipeline

**Comment by jamesmcgirk** [comment]
@twan-dev would you like to review this one?

**Comment by jamesmcgirk** [comment]
@cryptohazard would you be interested in reviewing this one?

**Comment by cryptohazard** [comment]
@jamesmcgirk I can review it!

**Comment by jamesmcgirk** [comment]
@cryptohazard is this one ready for Final Content Review yet?

**Comment by jamesmcgirk** [comment]
Moved this one into FCR @Astridchou please make sure that you leave the editing settings open so @cipherix and I can edit it

**Comment by Astridchou** [comment]
@jamesmcgirk Sorry about the late, I didn't notice this notification. I have finished it and accepted all your recommendations. Thank you!

**Comment by Astridchou** [comment]
@jamesmcgirk Sorry for the late. I have finished it and accepted all your recommendations. Thank you!

**Comment by jamesmcgirk** [comment]
Thanks so much @Astridchou I should have the GtM finished today

**Comment by jamesmcgirk** [comment]
@Astridchou just okay'd the GtM, moved this to Engagement Review. @twan-dev good to publish

**Comment by Astridchou** [comment]
The summary has been published. A big thank you to everyone who helped to make it.
