### ISSUE TITLE
Research Summary: A Decision Model for Decentralized Autonomous Organization Platform Selection: Three Industry Case Studies

### ISSUE THREAD

**Issue by Astridchou** [smartcontractresearchforum/research_content#171]
Link to draft:
https://docs.google.com/document/d/1arJcbnZKINEIaAJlhBfuFhOeqH0iKEVv05Fw5Y70LZQ/edit#

**Comment by jamesmcgirk** [comment]
moving this over bc it's from the research pipeline

**Comment by Astridchou** [comment]
Draft of the summary is finished. So I am going to move this card to the next stage.

**Comment by twan-dev** [comment]
- [x] All fields described in the Template for that content type have been filled out.
- [x] PM has notified Jean and Faith of this draft. At least 2 Peer Reviewers have been briefed about this content.

**Comment by jamesmcgirk** [comment]
@twan-dev @Astridchou I'll begin a peer review today

**Comment by jamesmcgirk** [comment]
@Astridchou I did a peer review pass

**Comment by Astridchou** [comment]
@jamesmcgirk Thank you so much for your review. I have finished it and added some content accordingly.

**Comment by twan-dev** [comment]
@jamesmcgirk @Astridchou  Moving to next stage once the last comment is resolved
- [x] All comments from Peer Reviewers have been discussed and addressed by authors. 
- [ ] All suggestions provided by Peer Reviewers have been resolved.

**Comment by Astridchou** [comment]
I have finished the requirements of @jamesmcgirk 's review (I used yellow highlight to mark my amendment and left a response to a comment) and the GTM questions.

**Comment by jamesmcgirk** [comment]
Thanks so much, @Astridchou -- I'll let you know when the GtM is ready so we can discuss

**Comment by Astridchou** [comment]
> I have finished the requirements of @jamesmcgirk 's review (I used yellow highlight to mark my amendment and left a response to a comment) and the GTM questions.

Oops, I have commented on the wrong place; I tend to make this comment in #152.

**Comment by jamesmcgirk** [comment]
@twan-dev @zubepaul flagging for engagement assignment

**Comment by Astridchou** [comment]
@jamesmcgirk I have finished the GTM questions

**Comment by jamesmcgirk** [comment]
@Astridchou finished my editorial pass, nothing major, just a couple of things for you to review

**Comment by jamesmcgirk** [comment]
@Astridchou don't forget to review my changes when you get a chance

**Comment by Astridchou** [comment]
@jamesmcgirk Thank you so much for your reminder and illuminating review. I have finished it and highlighted the sentences that are corresponding to your comments.

**Comment by zubepaul** [comment]
@twan-dev @Astridchou Engagement Review completed. Can be published no sooner than December 20th, 2021

**Comment by twan-dev** [comment]
@Astridchou Please publish soon!

**Comment by Astridchou** [comment]
Published!
