### ISSUE TITLE
Research Summary: SmartConDetect: Highly Accurate Smart Contract Code Vulnerability Detection Mechanism using BERT

### ISSUE THREAD

**Issue by twan-dev** [smartcontractresearchforum/research_content#173]
From Research Pulse Issue #28 08/30/21

Link to paper [here](http://plpworkshop.com/papers/PLP_7_SmartConDetect_%20Highly%20Accurate%20Smart%20Contract%20Code%20Vulnerability%20Detection%20Mechanism%20using%20BERT%20-%20Sowon%20Jeon.pdf)

Link to Google docs [here](https://docs.google.com/document/d/1tB2DwGZf5xHeLas4ytAvRgBPpFsLZRWSjxCqNBRr0SQ/edit)

**Comment by twan-dev** [comment]
Pausing, for now, to see if the AIOT group would like to add this paper into their list of papers to summarize, as Seth just told me that this paper fits into their scope. 

I've already done a quick survey of the paper, and have written short summaries, which could be helpful for anyone who would like to finish it. They are all available in Google docs.

**Comment by twan-dev** [comment]
The AIOT group doesn't have immediate plans in adding this paper into their scope, and they also need to take time to finish the summaries on the existing list first. So I'm picking this up again, as it is an interesting read and would be great to add to the forum.

**Comment by jamesmcgirk** [comment]
I just read about BERT in a paper about democratizing machine learning... should be interesting... adding a tag

**Comment by jamesmcgirk** [comment]
@loicdrbx this one has some interesting AI and NLP angles if you're interested in peer reviewing

**Comment by twan-dev** [comment]
@cipherix Thanks for taking time with my summary. I have made changes based on your review. It's ready for another look.

**Comment by cipherix** [comment]
Thank you for the improvements. Seems like one area under Applicability needs a bit more context for clarity, but overall this looks good to go. WIll move it to editorial review @jamesmcgirk

**Comment by jamesmcgirk** [comment]
posted GtM questions @zubepaul @twan-dev flagging you both for engagement assignment, beginning editorial review

**Comment by jamesmcgirk** [comment]
@twan-dev editorial review complete -- really clean copy! Just waiting for your GtM questions

**Comment by twan-dev** [comment]
@jamesmcgirk They're ready!

**Comment by jamesmcgirk** [comment]
Editorial review complete, waiting for GtM

**Comment by zubepaul** [comment]
GtM Questions completed, GtM nearly completed, scheduling GtM interview with @twan-dev

**Comment by twan-dev** [comment]
GTM interview completed about a week ago, but a researcher has reason to believe that this paper is not perfect for SCRF. Moving to icebox and will revisit once we have time to revisit.
