### ISSUE TITLE
A small correlation study using the opensea api

### ISSUE THREAD

**Issue by jamesmcgirk** [smartcontractresearchforum/research_content#177]
Suggested by Barry

> Anyone looking into what NFTs mean as a new category of research? It seems for the first time there is an opportunity to quantify the art and collectibles market which have historically been opaque markets. What's interesting about these markets is they are expressions of culture, so it presents an opportunity to model culture with large and transparent datasets. I would imagine anthropologists would be highly engaged with such data.

> If no one else is up for it I would be interested in doing a small correlation study using the opensea api. I don't have the bandwidth to do an indepth study, but perhaps a quick interactive notebook to start a conversation and get others interested in drilling down deeper.

**Comment by jamesmcgirk** [comment]
@bgits feel free to add to this, I just copied your description from Discord and pasted it in

**Comment by bgits** [comment]
I put together an initial notebook that pulls in data from Opensea for a given collection. The notebook is on Google Collab, if anyone wants access please get in touch on discord.

So far I have pulled in a few of the more popular collections and fitted distributions to their distribution of features.

I find it interesting that the collections are all non-normally distributed and long tailed. The "Bored Ape Yacht Club" collection best fit the Log-Laplace distribution while the other two both fit a Mielke distribution.

Possible avenues for further exploration is defining rarity of individual NFTs in a collections and mapping them with marketplace activity metrics in a collection.

![](https://cdn.discordapp.com/attachments/796496209736630303/890976956521283664/Screen_Shot_2021-09-24_at_11.04.10_AM.png)

![](https://cdn.discordapp.com/attachments/796496209736630303/890977008836804628/Screen_Shot_2021-09-24_at_11.04.27_AM.png)

![](https://cdn.discordapp.com/attachments/796496209736630303/890977109361700965/Screen_Shot_2021-09-24_at_11.04.51_AM.png)

**Comment by jamesmcgirk** [comment]
@cipherix would love to get your opinion on this project

**Comment by Coinproz** [comment]
Discussion post might be a good format for this type of primary research.  It allows for multiple resources to be referenced, while allowing the discussion to go beyond the primary research if necessary.  A "mini-post" might also work for this if there is a narrative that makes the data relevant or useful and not just arbitrary data capture and analysis.

**Comment by cipherix** [comment]
I think this could be a good discussion post @bgits. Are you still working on this?

**Comment by twan-dev** [comment]
This is indeed an interesting post. I'll move it to icebox until the right timing to start the project.
