### ISSUE TITLE
Research Summary: Federated Learning Meets Blockchain in Edge Computing: Opportunities and Challenges

### ISSUE THREAD

**Issue by SethAustinHarding** [smartcontractresearchforum/research_content#178]
This is a quintessential example of AIoT Blockchain!
Paper Link: https://arxiv.org/abs/2104.01776
Paper Summary: https://docs.google.com/document/d/1F3uY-unn2cYVAIlIeaIXicl8IpVGdN3qhg4UCSUz8IY/edit?usp=sharing

**Comment by jamesmcgirk** [comment]
Did you get Lucas' signoff on this one @SethAustinHarding ?

**Comment by SethAustinHarding** [comment]
@jamesmcgirk Not yet

**Comment by jamesmcgirk** [comment]
I'm going to scoot this one back into Idea Proposal... Hopefully @cipherix  can take a look at it soon

**Comment by twan-dev** [comment]
Closing this for now as Seth is busy with other summaries.
