### ISSUE TITLE
Research Summary: Decentralized & Collaborative AI on Blockchain

### ISSUE THREAD

**Issue by SethAustinHarding** [smartcontractresearchforum/research_content#179]
Paper: https://arxiv.org/pdf/1907.07247.pdf
Research Summary: https://docs.google.com/document/d/1BgMxWeMghcUVU26KIzIj1WmBAMkla-O44UsQSXz5H-I/edit

**Comment by jamesmcgirk** [comment]
@SethAustinHarding did you get this one from research pulse?

**Comment by SethAustinHarding** [comment]
@jamesmcgirk I got this from the "Leveraging Blockchain for Greater Accessibility of Machine Learning Models" article, which is essentially a condensed version of this paper. This would be a highly beneficial paper for the AIoT Blockchain paper. However, on second thought, I'd prefer to just reference the article summary and paper directly instead. Closing.

**Comment by SethAustinHarding** [comment]
@jamesmcgirk  I got this from the "Leveraging Blockchain for Greater Accessibility of Machine Learning Models" article, which is essentially a condensed version of this paper. This would be a highly beneficial paper for the AIoT Blockchain paper. However, on second thought, I'd prefer to just reference the article summary and paper directly instead. Closing.
