### ISSUE TITLE
Research Summary: I Told You Tomorrow: Practical Time-Locked Secrets using Smart Contracts

### ISSUE THREAD

**Issue by twan-dev** [smartcontractresearchforum/research_content#181]
This comes from Research Pulse Issue #27

Paper link [here](https://dl.acm.org/doi/fullHtml/10.1145/3465481.3465765)
Google docs [here](https://docs.google.com/document/d/1ej8OgGAv9dBSaJr0FiFGO2IUaso8gmbo/edit#)

**Comment by jamesmcgirk** [comment]
Nice work! Looking forward to seeing how this turns out

**Comment by jamesmcgirk** [comment]
@Astridchou here's another one you might enjoy!

**Comment by Astridchou** [comment]
@jamesmcgirk Thanks! I'll do it tomorrow.

**Comment by Astridchou** [comment]
I’ve finished the peer review. @twan-dev Great summary! I really enjoyed it and left some comments for you.

**Comment by zubepaul** [comment]
@twan-dev GtM is created and ready for your review.

**Comment by zubepaul** [comment]
@twan-dev Engagement review completed

**Comment by twan-dev** [comment]
Thanks Paul. Thank you everyone for making this happen.
