### ISSUE TITLE
Research Summary: Cost-Effective Blockchain-based IoT Data Marketplaces with a Credit Invariant

### ISSUE THREAD

**Issue by SethHasi** [smartcontractresearchforum/research_content#182]
Paper: https://ieeexplore.ieee.org/document/9461127/
Summary: https://docs.google.com/document/d/1SlwyVg295KHZ5pnrrYR5NTw26EKG-LxXSu_fZ0KtvTE/edit

The Chinese version of the summary has been completed.

**Comment by jamesmcgirk** [comment]
Nice work! Don't forget to describe why the paper is important and please include some potential tags if you can find any pertinent ones

**Comment by jamesmcgirk** [comment]
@cipherix should this one go on to drafting?

@SethAustinHarding who has been working on this one?

**Comment by SethAustinHarding** [comment]
This is one of the proposed summaries for the AIoT Blockchain project. Cindy has actually already finished the Chinese version of this summary and I was going to translate it to English.

**Comment by jamesmcgirk** [comment]
@cipherix another one for your consideration... this one is part of the AI, IoT, blockchain group's output... please see the note above about Cindy having already finished a version of this
