### ISSUE TITLE
Research Pulse Quarterly breakdown/indexing additions

### ISSUE THREAD

**Issue by Coinproz** [smartcontractresearchforum/research_content#187]
The idea is to create focused snapshots of research within the RP context to have regional or industry-specific repositories of articles from which researchers can do summaries.  This should reduce the time for searching for articles during the summary process.

Should follow Lucas' methodology at every step.

(Pilot with Tebogo for Pan-African Grants articles)

Regional research pulse:  African Research Pulse, Latin American Research Pulse, APAC research pulse

**Comment by jamesmcgirk** [comment]
@Coinproz do you think this could be a new content type? We might want to move it to the Project board

**Comment by Coinproz** [comment]
*research pulse mining

**Comment by twan-dev** [comment]
Doesn't belong to the content pipeline. Will discuss more in Discord/meetings if needed.
