### ISSUE TITLE
Research Summary: Towards Understanding and Demystifying Bitcoin Mixing Services

### ISSUE THREAD

**Issue by Siemingfong** [smartcontractresearchforum/research_content#189]
Following international AML/KYC regulation, this paper gives a notable work to identify bitcoin mixer service patterns and published the dataset on github: https://github.com/blocksecteam/bitcoinmixing

Current Survey paper list: https://docs.google.com/spreadsheets/d/1euZi9B8cK74N62ruOvJ9dKhppFontgQD37Heq_gMDqU/edit?usp=sharing

**Comment by jamesmcgirk** [comment]
@cipherix this paper is something that Sean is an expert on, and is of particular interest  because of how few people understood FTX's explanation for UTXO transactions

**Comment by Siemingfong** [comment]
Draft version
https://docs.google.com/document/d/1a9GvkttgtxNiKCyBvzPMTGuD5cDJZv_1-mj5wUG-1xQ/edit?usp=sharing

**Comment by twan-dev** [comment]
Closing this because Sean is busy with other summaries.
