### ISSUE TITLE
Mini-Post comparing the feature differences between SNARKS platforms (DARKs, HALOs, RAPs, etc)

### ISSUE THREAD

**Issue by jamesmcgirk** [smartcontractresearchforum/research_content#190]
Mini-Post comparing the feature differences between SNARKS platforms (DARKs, HALOs, RAPs, etc)

**Comment by 29988122** [comment]
For reference: this should be done further down the road as a complete series for zk/cryptography articles(layer 2 is top3 most important things in the next 3 years), where the well-curared post series is *no where to be seen on the internet* i.e., worth writing for. 

However this is our of hand for the cryptography researchers/students in SCRF currently(number wise and academic capability wise). Could be reopened when SCRF researchers's ready for it. At least I'll remember this ticket.
