### ISSUE TITLE
SCRF Interview: PlonK and SNARKS with Ariel Gabizon and Lucas Nuzzi

### ISSUE THREAD

**Issue by lw-scrf** [smartcontractresearchforum/research_content#191]
- Right now there is only a link to this, in #privacy. Think it should be broken out as a separate post under #cryptography. 

- Don't think this falls under any of the formatting templates I see, so intent is to follow Eugene's post for the Privacy and SNARKs panel: [https://www.smartcontractresearch.org/t/smart-contract-summit-2021-privacy-and-snarks-panel/622](url)
   About the SCRF Interview: PlonK and SNARKS with Ariel Gabizon and Lucas Nuzzi
   Participant Bio and Relevant Works
   Key Questions

- Bio blurb for Lucas?

**Comment by lw-scrf** [comment]
@jamesmcgirk I wanted to assign myself, but wasn't able to, is that a permissions thing?

**Comment by jamesmcgirk** [comment]
Must be! I’ll look into it

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by lw-scrf** [comment]
@jamesmcgirk no worries, just don't want to create work for someone else, if i can do it myself :)

**Comment by jamesmcgirk** [comment]
I think this might be in the wrong repository, let me dupe this card for you in the document pipeline

**Comment by lw-scrf** [comment]
oooooh, thanks...probably need to do that for the other one i just created too. oops and thanks.

**Comment by lw-scrf** [comment]
@cipherix do you have a bio blurb i can use for this breakout post of the interview with you and ariel? thanks.
