### ISSUE TITLE
SCRF Interview: PlonK and SNARKS with Ariel Gabizon and Lucas Nuzzi

### ISSUE THREAD

**Issue by jamesmcgirk** [smartcontractresearchforum/research_content#193]
Via @lw-scrf (who still needs access)

- Right now there is only a link to this, in #privacy. Think it should be broken out as a separate post under #cryptography.

- Don't think this falls under any of the formatting templates I see, so intent is to follow Eugene's post for the Privacy and SNARKs panel: https://www.smartcontractresearch.org/t/smart-contract-summit-2021-privacy-and-snarks-panel/622
About the SCRF Interview: PlonK and SNARKS with Ariel Gabizon and Lucas Nuzzi
Participant Bio and Relevant Works
Key Questions

- Bio blurb for Lucas?

**Comment by lw-scrf** [comment]
@jamesmcgirk @29988122 link to doc in progress below...not sure what process is here, hopefully after walking this 1st one through, i'll get a sense. thanks guys...

[https://docs.google.com/document/d/12fsTUAp8ENibbO6_wXvTN6Sv-RGKq08xuc7k5oU4QiQ/edit#](url)

**Comment by jamesmcgirk** [comment]
Added a few tags, moving to Idea Proposal stage until we get the official OK from Lucas
