### ISSUE TITLE
Discussion Post: Elliptic Curve Pairings Vuneralbility to Quantum Computing #192

### ISSUE THREAD

**Issue by jamesmcgirk** [smartcontractresearchforum/research_content#194]
Posted on behalf of lw-scrf 

Questions that came out of the Ariel/Lucas podcast, but during zk breakout on 8.16, decided it should be a different post.

**Comment by 29988122** [comment]
I'll be contacting ppl participating in the PQC competition @SINICA Taiwan, to see if they're interested in answering questions in my DM, or I can further invite him/her to our forum to reply.

**Comment by lw-scrf** [comment]
> I'll be contacting ppl participating in the PQC competition @sinica Taiwan, to see if they're interested in answering questions in my DM, or I can further invite him/her to our forum to reply.

Cool, thanks Jerry.

**Comment by lw-scrf** [comment]
link to what i already have...need to hone...https://docs.google.com/document/d/1KKfja_pgh5Dn7hFSeQxLcy05iJsVqzE6su9ryHxW3xg/edit

**Comment by jamesmcgirk** [comment]
scooching this over to Idea Proposal until @cipherix has a look or we discuss in the Monday meeting

**Comment by lw-scrf** [comment]
thanks @29988122. i'm really looking forward to a more in-depth explanation from your quantum computing friend, who is also blockchain-savvy, so thanks for getting into contact with him for us. i'll save it for the post, but my next ? would be:  

'it's close to impossible (witn 95% CI) that we'll have quantum computers with enough qubits that can break even rsa 2048'

close to impossible, isn't impossible. 10 years, 50 years, 100 years? realize totally theoretical ? re: how fast quantum computing will evolve, but i think this is exactly the kind of ? to ask a quantum computing expert, with the caveat, that of course, we're just asking for his expert opinion...

i also hope that he'll provide some research papers to support his stance as well...looking forward to it and thanks again!

**Comment by lw-scrf** [comment]
> Although it's better leave the formal answer to him... quick tldr would be: the therotical side (depends on how strict you define therotical) is already completed; the rest efforts are all engineering-wise. And it took time, and damn lots of money. There will only be linear growth (quantum computer development) rather than exponential growth (in terms of qubits), for example.

so hardware & engineering limitations essentially...got it.

**Comment by twan-dev** [comment]
Talked to the content contributor. Further work isn't expected. Moving to icebox.

**Comment by 29988122** [comment]
For reference purposes only: if needed, I've got people with exactly this subdomain of expertise to talk about it, if there's ever a need. 

Such as: ppl are (again..)fearmongered by the so called "quantim supremacy".

Spoiler alert: don't worry about quantum computers breaking Blockchain. At least not in 2021/2022, or even 2023.

**Comment by encore9870** [comment]
I'm closing all issues that are not actively being worked on. Reach out to me if you have questions!
