### ISSUE TITLE
Tebogo Case Study

### ISSUE THREAD

**Issue by Coinproz** [smartcontractresearchforum/research_content#195]
Research and Development of Blockchain Recordkeeping at the National Archives of Korea

https://www.mdpi.com/2073-431X/10/8/90

**Comment by jamesmcgirk** [comment]
This sounds like a perfect overlap with her research. Added some detail to the header.

**Comment by jamesmcgirk** [comment]
Added you as an owner just so you can see the updates in here. Assigning myself as engagement owner
