### ISSUE TITLE
(TEST) Research Summary: Arbitrum - Scalable, private smart contracts

### ISSUE THREAD

**Issue by lw-scrf** [smartcontractresearchforum/research_content#197]
- TEST to see all systems go @jamesmcgirk, but everything looks good, i just assigned myself a few things and added labels...
- saw exchange about arbitrum on discord b/t jean and bill, i'd actually put it on my to read list already...so two birds...looks like @flyinglimao is on this...didn't assign though, will let him self-assign if he is...

[http://stevengoldfeder.com/papers/Arbitrum-USENIX.pdf](url)

**Comment by jamesmcgirk** [comment]
Did you create this one in the document pipeline? I don't see it yet

**Comment by jamesmcgirk** [comment]
Your other comments are all visible, I think I might need to show you where to create a ticket

**Comment by lw-scrf** [comment]
@jamesmcgirk, yep, if you could just give me the tree directory on where to create in doc pipeline, that would be nifty. thanks :)

**Comment by encore9870** [comment]
test was successful
