### ISSUE TITLE
Research Summary: Differential Privacy in Constant Function Market Makers

### ISSUE THREAD

**Issue by lw-scrf** [smartcontractresearchforum/research_content#200]
- New Tarun Chitra paper, mentioned in Research Pulse
- Tarun has already interacted in forum #privacy, good to keep him engaged
* no #privacy label in drop-down menu...

[https://eprint.iacr.org/2021/1101.pdf](url)

**Comment by lw-scrf** [comment]
@jamesmcgirk, not sure if this is showing up in the right place for some reason...i think everything's working, except being able to open a new issue in the Doc Pipeline itself.

**Comment by jamesmcgirk** [comment]
Do you have time today for a demonstration?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by lw-scrf** [comment]
i'd be good in about an hour from 10-10.30CT, i think your PT now? would that work? i'd also be good tomorrow at same time...

**Comment by jamesmcgirk** [comment]
Darn, I've got a meeting... if you get a chance could you please go to the document pipeline https://github.com/orgs/smartcontractresearchforum/projects/5 and tell me whether you see a little "+" in the corner of each column? That will tell me whether you have permission to create new notes on the pipeline

**Comment by jamesmcgirk** [comment]
I'm going to recreate this ticket in the doc pipeline in the meantime

**Comment by jamesmcgirk** [comment]
I remade this ticket in the document pipeline. I'm going to close this ticket. You should have permission to create these now, so I'll show you how to create them in the pipeline again (or figure out the problem if we can't)
