### ISSUE TITLE
Research Summary: Differential Privacy in Constant Function Market Makers

### ISSUE THREAD

**Issue by jamesmcgirk** [smartcontractresearchforum/research_content#201]
Mentioned in Research Pulse
Tarun Chitra's Differential Privacy in CFMM paper
no #privacy label in drop-down menu...

https://eprint.iacr.org/2021/1101.pdf

**Comment by jamesmcgirk** [comment]
@lw-scrf created a version of this in the document pipeline, added metatext, moved into drafting bc it's a RP paper. Are you planning to work on this one or is it up for grabs?

**Comment by lw-scrf** [comment]
cool, thx, up for grabs...but if nobody snags, will take a shot...

**Comment by twan-dev** [comment]
Don't believe this is still in progress. Moving to icebox.

**Comment by encore9870** [comment]
I'm closing all issues that are not actively being worked on. Reach out to me if you have questions!
