### ISSUE TITLE
Research Summary Idea: Smart Contract Security- A Practitioner’s Perspective (2021)

### ISSUE THREAD

**Issue by jamesmcgirk** [smartcontractresearchforum/research_content#202]
(Posted on behalf of MaxGrok / Post Idea submission)

[Smart Contract Security- A Practitioner’s Perspective](https://ieeexplore.ieee.org/document/9402082?partnum=9402082&searchProductType=IEEE%20Conferences)

To date, not much research has been done into current best practices of smart contract security auditing across the major firms such as Trail of Bits, Consensys Diligence, and Quantstamp. As for education of aspiring devs, there are CTF exercises like CaptureTheEther and Ethernauts, but these are not up to date on the latest attacks. This paper summarizes qualitative and quantitative analysis of current practices for smart contract security auditing, including “13 interviewees and 156 survey respondents from 35 countries across six continents”. It amalgamates all of their findings in one paper. Summarizing it for SCRF would be a step towards democratizing and demystifying smart contract security auditing practices and taking a temperature of current practitioner’s methods of protecting smart contracts from attacks.

Link to [Peer Review doc](https://docs.google.com/document/d/1cp2Njua_dPnFFOyD8otfxn4IAZv0fKyxctV07AZqciI/edit)

**Comment by jamesmcgirk** [comment]
Link to[ Doc (as HackMD)](https://hackmd.io/@jebheBHfTsSG8FJVY4HJWg/HJMtgI7Vt )

**Comment by jamesmcgirk** [comment]
@lpassos this might be interesting for you to peer review

**Comment by jamesmcgirk** [comment]
@lw-scrf - this might be of interest

**Comment by ralph** [comment]
Wrong `ralph` 😉

**Comment by jamesmcgirk** [comment]
@ralph terribly sorry! I meant Ralph Lombreglia

**Comment by ralph** [comment]
Don't worry, I get this all the time `¯\_(ツ)_/¯`

**Comment by jamesmcgirk** [comment]
Assigned to @rlombreglia for peer review

**Comment by jamesmcgirk** [comment]
@maxgrok has responded to the peer review questions, moving this to FCR @cipherix ready for you!

**Comment by twan-dev** [comment]
@jamesmcgirk looks like the comments in the document have all been resolved. Is it ready for next steps?

**Comment by twan-dev** [comment]
Looks like this one has been published 
https://www.smartcontractresearch.org/t/research-summary-smart-contract-security-a-practitioner-s-perspective-2021/877
