### ISSUE TITLE
Research Summary: RA: A Static Analysis Tool for Analyzing Re-Entrancy Attacks in Ethereum Smart Contracts

### ISSUE THREAD

**Issue by flyinglimao** [smartcontractresearchforum/research_content#203]
Link: https://www.jstage.jst.go.jp/article/ipsjjip/29/0/29_537/_pdf
Research Pulse: https://www.smartcontractresearch.org/t/research-pulse-31-09-20-21/820

> RA: A Static Analysis Tool for Analyzing Re-Entrancy Attacks in Ethereum Smart Contracts
> Authors: Yuichiro Chinen, Naoto Yanai, Jason Paul Cruz, and Shingo Okamura
> 
> Ethereum smart contracts are programs that are deployed and executed in a consensus-based blockchain managed by a peer-to-peer network. Several re-entrancy attacks that aim to steal Ether, the cryptocurrency used in Ethereum, stored in deployed smart contracts have been found in the recent years. A countermeasure to such attacks is based on dynamic analysis that executes the smart contracts themselves, but it requires the spending of Ether and knowledge of attack patterns for analysis in advance. In this paper, we present a static analysis tool named RA (Reentrancy Analyzer), a combination of symbolic execution and equivalence checking by a satisfiability modulo theories solver to analyze vulnerability of smart contracts to re-entrancy attacks. In contrast to existing tools, RA supports analysis of inter-contract behaviors by using only the Ethereum Virtual Machine bytecodes of target smart contracts, i.e., even without prior knowledge of attack patterns and without spending Ether. Furthermore, RA can verify existence of vulnerability to re-entrancy attacks without execution of smart contracts and it does not provide false positives and false negatives. We also present an implementation of RA to evaluate its performance in analyzing the vulnerability of deployed smart contracts to re-entrancy attacks and show that RA can precisely determine which smart contracts are vulnerable.
>

**Comment by jamesmcgirk** [comment]
I added a couple of tags, please let me know if there's anything better suited than 'security'

**Comment by jamesmcgirk** [comment]
@flyinglimao please don't forget to add the link to your drive (and please leave edit permissions open so we can review it).

**Comment by flyinglimao** [comment]
Sorry for the delay...😅
https://docs.google.com/document/d/12HQc21O-FGDuEd9ZJ8vuWob2WUnCxvQbTqZBB9-cgzg/edit?usp=sharing

**Comment by twan-dev** [comment]
- [ ] The summary is compliant with the running summary template
- [ ] A spelling and grammar check is complete
- [ ] If there exists an available Peer Reviewer, PM has notified them of this draft.

Currently waiting for the author to finish the first item on the list.
