### ISSUE TITLE
Mini-Post: Data analysis of flow of users across Layer 1s

### ISSUE THREAD

**Issue by cryptomarabout** [smartcontractresearchforum/research_content#204]
Layer 1 solutions, or smart contracts platforms, such as Ethereum, Cardano, Binance Smart Chain, Avalanche, Solana, etc. are currently seeing a lot of interest. It could be interesting to try to evaluate if the “hype” of these networks can really be related to their flow of users. Indeed as these projects are releasing their product and Dapps over time, such networks have some periods where usage is growing slightly, however we need to know who are those users and are they used to leaving another blockchain to a ‘better solution’. An approach could be to try to identify users, or groups of users, to know if layer 1s are building their own community of users or are users changing blockchain over time. 
We can perform some clustering to create different groups of users according to their capital by studying the address balances, amount of the transactions, the swaps, or any used operation. We would then be able to extract conclusions such as x% of Uniswap txs are done by users having more than X ETH while it could be different in another blockchain where for example most of the transactions are small amounts.
If the 2 compared layer 1s are using the same address standard, we can identify a specific user across both networks. Then we would be able to execute analysis by comparing the amount of transactions for the same users in the different networks, enabling for example to identify that users are using a specific network for small amounts etc. We can also study if the user is reducing his usage in the other networks. 

We can also focus only on the “new addresses”. 
We can also try to identify “periods” of usage (or DeFi TVL) and looking at the correlation between usages of networks, conclusions could be: most users of blockchain A left for blockchain B in 2021.

**Comment by jamesmcgirk** [comment]
@cryptohazard let me know if you can think of better labels for this suggestion - could work as a mini-post or discussion post

**Comment by cipherix** [comment]
There has been some interesting on-chain analysis on this front, but perhaps focus on something that has already been published? Otherwise, it could be a big lift to source that data.

**Comment by twan-dev** [comment]
Looks like there isn't much interest in this topic. I'll move it to icebox for now.
