### ISSUE TITLE
Research Summary: Towards Private On-Chain Algorithmic Trading

### ISSUE THREAD

**Issue by jamesmcgirk** [smartcontractresearchforum/research_content#209]
From RP #33

[Link to the paper](https://arxiv.org/pdf/2109.11270.pdf)

In this paper we present ChainBot, an approach for creating algorithmic trading bots with the help of blockchain technology. We show how to partition the algorithmic computation into on- and off-chain components in a way that provides a measure of end-to-end integrity, while preserving the algorithmic “secret sauce”. The end result is a system where an enduser can sign-up for the services of a trading bot, with trust established via on-chain publicly readable contracts. Our system is enabled with a careful use of algorithm partitioning and zero-knowledge proofs together with standard smart contracts available on most modern blockchains.

**Comment by jamesmcgirk** [comment]
Posted on behalf of @tony363

**Comment by Tony363** [comment]
https://docs.google.com/document/d/11BZQiL6oGKCM9Jxc8dotcZ64hFjGZXVVZ4sU7kP9S0M/edit?usp=sharing <- please give constructive criticism and comments

**Comment by jamesmcgirk** [comment]
@Astridchou would you like to peer review this one?

**Comment by Tony363** [comment]
The more the merrier~ i only have a single brain running at a time afterall

**Comment by zubepaul** [comment]
Once the GtM is completed and it is discussed between @jamesmcgirk and @Tony363, tag Twan to indicate that the engagement review is completed and that this is ready to be published.

**Comment by jamesmcgirk** [comment]
@twan-dev this one is ready to go...

**Comment by jamesmcgirk** [comment]
@Tony363 you can publish this!

**Comment by Tony363** [comment]
@jamesmcgirk  just posted~ really just copied and pasted. Hope I did the formating right.
