### ISSUE TITLE
Research Summary: ESCORT: Ethereum Smart COntRacTs Vulnerability Detection using Deep Neural Network and Transfer Learning

### ISSUE THREAD

**Issue by twan-dev** [smartcontractresearchforum/research_content#211]
Selected from Research Pulse  Issue 6 03/26/21
I've already finished another summary on a similar topic that uses a different approach. 
This could be great to add to the forum so we can compare them.

[Link to paper](https://arxiv.org/pdf/2103.12607.pdf)

[Link to Google Docs](https://docs.google.com/document/d/1YQaZqUkVv_o3zZtzXedkstZN6F2fX27k_NMswbIm44U/edit#)

**Comment by twan-dev** [comment]
- [ ] All fields described in the Template for that content type have been filled out.
- [ ] If there exists an available Peer Reviewer, PM has notified them of this draft
- [ ] Ensure that the document adheres to the style guide and is formatted correctly

**Comment by twan-dev** [comment]
@amitk2-cmu Here's the ticket I was talking about and would need your review. Thanks!

**Comment by amitk2-cmu** [comment]
Looks complete to me, thanks Twan.

**Comment by amitk2-cmu** [comment]
Peer review complete.

**Comment by twan-dev** [comment]
- [x] All comments from Peer Reviewers have been discussed and addressed by authors. 
- [x] All suggestions provided by Peer Reviewers have been resolved.

**Comment by cipherix** [comment]
Excellent summary @twan-dev -- moving it to Editorial Review @jamesmcgirk

**Comment by jamesmcgirk** [comment]
@twan-dev made a couple of minor changes, and added the GtM questions

**Comment by zubepaul** [comment]
@twan-dev Have GtM questions been addressed on this yet? And are you reading to move through engagement process?

**Comment by twan-dev** [comment]
@zubepaul yes, since Jan 5 I think

**Comment by zubepaul** [comment]
@twan-dev Engagement review complted. This can be posted to the forum no sooner than January 27th, 2022

**Comment by zubepaul** [comment]
@twan-dev Reminder that this is clear to be published at this point.

**Comment by goheesheng** [comment]
I cannot seem to find the github repo and source code to play with it? Is it released?

**Comment by zubepaul** [comment]
> I cannot seem to find the github repo and source code to play with it? Is it released?

The authors of the original paper would be a better target for this question
