### ISSUE TITLE
1.1 - Nathan and Abbey, culture and cryptoecon

### ISSUE THREAD

**Issue by eleventh19** [smartcontractresearchforum/research_content#214]
# Topic: Culture and onboarding

This card is meant to track episode 1 from our first governance mini-series on culture and incentivization through the content pipeline. 

Episode 1: Culture and onboarding and X: cryptoeconomics 
(with SCRF host, Nathan Schneider, and Abbey Titcomb at Radicle) 

Questions to explore in this episode: 
- What role does culture play? 
- Discuss Nathan’s paper - cryptoeconomics as a limitation on governance 
- What problems can culture help solve? 

# Relevant Links

- Source
https://docs.google.com/document/d/1zJfbgSvx9SNhkgGPQX2cBE_2P0jBy4siG_-nIdWahL0/edit?usp=sharing
- Episode Folder Link
https://drive.google.com/drive/u/0/folders/14Ouie9CD5S8BvqGRdgqDcZ4cPh7FyM0b

# Steps to completion

**Idea Proposal Stage**
- [x] Draft a potential topic to cover
- [x] Draft some specific questions 
- [x] Draft ideal guests 
- [x] Reach out to one to gauge interest
- [x] Any updates to the questions/topic?
- [x] Ask the first guest about who they’d want to talk to
- [x] If no, then come up with a second guest 
- [x] Reach out to the second guest 
- [x] Move on to scheduling

**Drafting**
- [x] Send out schedule/pick date
- [x] Send invite w/checklist and questions
- [x] Send confirmation email 24 hrs before recording
- [x] Check "Preparing for the interview" checklist
- [x] Confirm with all guests if the topic/question list looks good

**Peer Review**
- [x] Check the ‘Getting ready to record checklist’
- [x] Press record
- [x] Shift audio levels as needed
- [x] Receiving files for post

**Final Content Review**
- [x] Editing
- [x] Edit check/revisions
- [x] Export final video/save to drive
- [x] Export final audio/save to drive
- [x] Transcribe Audio
- [x] Pull transcript from Riverside 
- [x] Review transcript
- [x] Upload transcript to HackMD
- [ ] Submit pull request to github

**Editorial Review**
- [x] Start Show Notes draft
- [x] Share with team/revise
- [x] Finalize Show Notes

**Engagement and Calendaring**
- [x] Engagement/Social meeting

**Published**
- [x] Market Episode on Twitter/LinkedIn
- [x] Post to YouTube 
- [x] Host on TBC platform

**Comment by eleventh19** [comment]
updating this to drafting stage as we just confirmed both guests and the date - shooting to record on 11/18 potentially at 12p CST

**Comment by eleventh19** [comment]
@ivanplazacic can you please link to where the audio files

**Comment by ivanplazacic** [comment]
Here is the link to all the backup/archival files:

https://drive.google.com/drive/folders/1AyfMQaBUwcbURo3m2ZTO-gMRzhRD12kR

Here is the link to the separate raw recordings:

https://drive.google.com/drive/folders/1hJzIfCgVcu5k-APq3tCshRhOeAxoAkQ4

**Comment by ivanplazacic** [comment]
Here is the link to the edit:

https://drive.google.com/file/d/1evsEiVYACGE2ziH3tI9U2Xi_kTlp5dMD/view?usp=sharing

**Comment by eleventh19** [comment]
i need to review. shared the link to the [write up](https://docs.google.com/document/d/1vcFR7zX12nL00GfEfXP2GmlAfavk2vSiT-iTKUTJA9o/edit#) to Abbey and Nathan in case they have any feedback. debating release on 1/13 or 1/20.

**Comment by ivanplazacic** [comment]
Here is the link to the edit with the **first revision**:

https://drive.google.com/file/d/1eqP-yTdZhhNRQL77xaSK6z8JWBYE11rv/view?usp=sharing

**Comment by ivanplazacic** [comment]
Here is the link to the audio version of the episode:

https://drive.google.com/file/d/1lsafqGbSc8KaE2sNTOVJrN1XrLNo2A7m/view?usp=sharing

**Comment by encore9870** [comment]
Closing this as we have moved the podcast discussion away and will be using this repository for content pipeline drafts.
