### ISSUE TITLE
Research Summary: Analysis of Decentralized Mixing Services in the Greater Bitcoin Ecosystem

### ISSUE THREAD

**Issue by 29988122** [smartcontractresearchforum/research_content#215]
Well I decided to do something easier *relatively*, cause the ones I'm currently doing are either too sophisticated or too long-winded. Change of life phase I think.

Straightly from Research Pulse # 35 
Draft link:
https://docs.google.com/document/d/1FWxHrktIHrC00lz6zIVQQDwrivtI4DglbH8HcxoBpAg/edit

After PM approval, this piece is ready for either peer review or Lucas's review.

**Comment by twan-dev** [comment]
- [ ] The summary is compliant with the running summary template
- [ ] A spelling and grammar check is complete
- [ ] If there exists an available Peer Reviewer, PM has notified them of this draft.

Currently waiting for the author to finish the first item on the list.

**Comment by 29988122** [comment]
@twan-dev , this one is complete, please check if there's any tickboxes that I'm missing, except:
- I can't seem to find the latest summary template (the one asked you to follow specific bullet point format), this one's on me. I'll be changing them after I got the templete. Sorry.
- Grammarly check is completed
- As previously mentioned in this ticket, either Chris Bates or Ming Fong Sie can review this one. It's open to anyone with basic understanding to on-chain analytics, (Graphsense)[https://github.com/graphsense], or money laundering.

**Comment by twan-dev** [comment]
@29988122 No worries. I'll answer all your questions with DM.

**Comment by 29988122** [comment]
Done editing. There's nothing else can be done for the result part filling of figures and graphs - that's the MAIN CONTENTS to this paper, the text sentences are just supplimentary.

Please let me know here if there's anything else not following the summary template, or we could advanced to the peer review stage hopefully.

**Comment by twan-dev** [comment]
- [x]  The first check on format and writing is complete.
- [x]  Peer Review is ready to start

**Comment by cipherix** [comment]
Great job on this @29988122 -- moving to editing.

**Comment by encore9870** [comment]
FYI There are latest updates on the project:
https://github.com/zkSNACKs/WabiSabi/releases/latest/download/WabiSabi.pdf
https://zksnacks.com/

**Comment by jamesmcgirk** [comment]
Nice work! Made a few edits. @zubepaul ready for engagement review. @RuthTolulope are you adding the questions?

**Comment by RuthTolulope** [comment]
Yes @jamesmcgirk 
I have added the questions @29988122

**Comment by ralphlombreglia** [comment]
@29988122 Hi Jerry. I've added the Go-to-Market questions at the bottom of your working draft.

https://docs.google.com/document/d/1FWxHrktIHrC00lz6zIVQQDwrivtI4DglbH8HcxoBpAg/edit#heading=h.o2cvpypa43r6

Please answer them and notify me here when you've finished. 

(Note: the question "Please list 4 questions that we can ask you about this subject to get conversation going?" is particularly important to us.)

**Comment by 29988122** [comment]
@ralphlombreglia Done. Please let me know if further address to certain questions are needed!

**Comment by RuthTolulope** [comment]
Hi @29988122, here is the markdown version of your research summary https://hackmd.io/@content/BJcPmbUF5.
Kindly ensure that this is the ultimate version that is uploaded to the forum when publication is approved.
Let me know if you have any questions or need assistance.

**Comment by ralphlombreglia** [comment]
@29988122. Hi Jerry. I'm satisfied with our GtM answers and feel that we can move this paper along to publication.

Is there anything about the Engagement process for this paper that you'd like to discuss? Any other questions beyond that? If so, I'd be happy to have a short video call with you early next week; let me know. Have a great weekend.

**Comment by 29988122** [comment]
Currently, no questions from my side. Can't wait to see how ppl react to it when it's been published.

: D

**Comment by zubepaul** [comment]
@twan-dev @ralphlombreglia @29988122 
Engagement review completed. Approved for forum publication no sooner than June 22, 2022

**Comment by ralphlombreglia** [comment]
@29988122 You're cleared to publish this piece tomorrow. Congrats! You probably know how to publish from HackMD but if you need any help let us know. Also, obviously, please help spread the word about it!

**Comment by ralphlombreglia** [comment]
@29988122 Greetings, Jerry. I don't know if you saw my note (here, last week) that you were authorized to publish your piece. Let me know if there are any issues blocking you from doing that. Thanks!

**Comment by 29988122** [comment]
Sorry. Too occupied for the past few days.

https://www.smartcontractresearch.org/t/research-summary-analysis-of-decentralized-mixing-services-in-the-greater-bitcoin-ecosystem/1701

Posted. Am ready to answer/watch discussions happening below the post.

**Comment by ralphlombreglia** [comment]
@29988122 Thanks for publishing. I asked one of your questions in response.
