### ISSUE TITLE
1.3 - Ellie and Zach, culture and compensation

### ISSUE THREAD

**Issue by ivanplazacic** [smartcontractresearchforum/research_content#217]
# Topic: Culture & Compensation
Episode 3: How onboarding and compensation feed culture (and vice versa)
(with SCRF host, Ellie Rennie from RMIT, Zach from Coordinape)
- How to compensate early-stage contributors?
- What kind of mechanisms can help teams find ways of compensating individuals that are more representative of their contributions? 
- How to help people understand how to get paid and what the processes are for work?
- Reputation as a form of compensation
# Relevant Links
- Source
https://docs.google.com/document/d/1zJfbgSvx9SNhkgGPQX2cBE_2P0jBy4siG_-nIdWahL0/edit?usp=sharing
- Episode Folder Link
https://drive.google.com/drive/folders/18R4dtiJ00OAJNGwyDXp7tXBlnysJ_U2z?usp=sharing
# Steps to completion
**Idea Proposal Stage**
- [x] Draft a potential topic to cover
- [x] Draft some specific questions 
- [x] Draft ideal guests 
- [x] Reach out to one to gauge interest
- [x] Any updates to the questions/topic?
- [x] Ask the first guest about who they’d want to talk to
- [x] If no, then come up with a second guest 
- [x] Reach out to the second guest 
- [x] Move on to scheduling

**Drafting**
- [x] Send out schedule/pick date
- [x] Send invite w/checklist and questions
- [x] Send confirmation email 24 hrs before recording
- [x] Check "Preparing for the interview" checklist
- [x] Confirm with all guests if the topic/question list looks good

**Peer Review**
- [x] Check the ‘Getting ready to record checklist’
- [x] Press record
- [x] Shift audio levels as needed
- [x] Receiving files for post

**Final Content Review**
- [x] Editing
- [x] Edit check/revisions
- [x] Export final video/save to drive
- [x] Export final audio/save to drive
- [x] Transcribe Audio
- [x] Pull transcript from Riverside 
- [x] Review transcript
- [x] Upload transcript to HackMD
- [ ] Submit pull request to github

**Editorial Review**
- [x] Start Show Notes draft
- [x] Share with team/revise
- [x] Finalize Show Notes

**Engagement and Calendaring**
- [ ] Engagement/Social meeting

**Published**
- [ ] Market Episode on Twitter/LinkedIn
- [x] Post to YouTube 
- [x] Host on [insert platform here]

**Comment by eleventh19** [comment]
emailed them to see if we can get something scheduled soon

**Comment by eleventh19** [comment]
might be rescheduling by a day, but shooting to record next week

**Comment by eleventh19** [comment]
recorded last week

**Comment by ivanplazacic** [comment]
Here is the link to all the backup/archival files:

https://drive.google.com/drive/folders/1EIp3qWd9lgO6IZU-RsGN4upkPtybPwdd?usp=sharing

Here is the link to the separate raw recordings:

https://drive.google.com/drive/folders/1Z3oAoeR7njDYki9B1nkEviupGCO9R9Ff?usp=sharing

**Comment by eleventh19** [comment]
being edited and discussion post is being drafted

**Comment by ivanplazacic** [comment]
Here is the link to the edit:

https://drive.google.com/file/d/1QL24FqxoJ8N34R54zi7m2sGL7wsf9iQx/view?usp=sharing

**Comment by ivanplazacic** [comment]
Here is the link to the edit with the first revision:

https://drive.google.com/file/d/134RL3xSHMllNlg5TpZMw6Vh9K26WgWdW/view?usp=sharing

**Comment by encore9870** [comment]
Closing this as we have moved the podcast discussion away and will be using this repository for content pipeline drafts.
