### ISSUE TITLE
2.1 - Darcy and Bull Trapper, Treasury Management

### ISSUE THREAD

**Issue by ivanplazacic** [smartcontractresearchforum/research_content#218]
# Topic: Treasury Management
Episode 1: Treasury Management:
(with Prof. Chris Berg (host), Eugene Leventhal (host), Bull Trapper (Yearn Core Contributor), Dr Darcy Allen (RMIT))
- Why is treasury hard?
- How is this a unique governance problem?
- How do you raise a treasury? (tokenomics question).
- What is a treasury for? (local/ecosystem/public/club goods):
- Public goods funding as a reason
- Signal as a reason

Managing a treasury as a portfolio 

- How much of native token should a DAO or foundation hold?
- Is this different for DAOs and foundations?
- Should a treasury be diversified, and if so, how much?
- How actively should your treasury be managed? Fund management / reallocation / re-collateralization 
- How much runway should you keep in cash?
# Relevant Links
- Source
https://docs.google.com/document/d/1zJfbgSvx9SNhkgGPQX2cBE_2P0jBy4siG_-nIdWahL0/edit?usp=sharing
- Episode Folder Link
https://drive.google.com/drive/folders/1ENQK74wTYO6pFYzxbxTAlgbZ2K9GVQXP?usp=sharing
# Steps to completion
**Idea Proposal Stage**
- [x] Draft a potential topic to cover
- [x] Draft some specific questions 
- [x] Draft ideal guests 
- [x] Reach out to one to gauge interest
- [x] Any updates to the questions/topic?
- [x] Ask the first guest about who they’d want to talk to
- [x] If no, then come up with a second guest 
- [x] Reach out to the second guest 
- [x] Move on to scheduling

**Drafting**
- [x] Send out schedule/pick date
- [x] Send invite w/checklist and questions
- [x] Send confirmation email 24 hrs before recording
- [x] Check "Preparing for the interview" checklist
- [x] Confirm with all guests if the topic/question list looks good

**Peer Review**
- [x] Check the ‘Getting ready to record checklist’
- [x] Press record
- [x] Shift audio levels as needed
- [x] Receiving files for post

**Final Content Review**
- [x] Editing
- [x] Edit check/revisions
- [x] Export final video/save to drive
- [x] Export final audio/save to drive
- [x] Transcribe Audio
- [x] Pull transcript from Riverside 
- [x] Review transcript
- [x] Upload transcript to HackMD
- [ ] Submit pull request to github

**Editorial Review**
- [x] Start Show Notes draft
- [x] Share with team/revise
- [x] Finalize Show Notes

**Engagement and Calendaring**
- [ ] Engagement/Social meeting

**Published**
- [ ] Market Episode on Twitter/LinkedIn
- [x] Post to YouTube 
- [x] Host on [insert platform here]

**Comment by eleventh19** [comment]
need to finalize a guest here, ideally someone who has experience setting up treasuries and/or running grants programs.

**Comment by eleventh19** [comment]
@ghettodev is confirming the second guest (thanks for reaching out!)

**Comment by eleventh19** [comment]
just dm'ed the anon guest on telegram and the RMIT folks via email to schedule

**Comment by eleventh19** [comment]
proposing a time as no clarity from doodle

**Comment by eleventh19** [comment]
recording tomorrow

**Comment by ivanplazacic** [comment]
Here is the link to all the backup/archival files:

https://drive.google.com/drive/folders/1iyHDo3zh81Un95IB037wfXWDsirhaSxJ?usp=sharing

Here is the link to the separate raw recordings:

https://drive.google.com/drive/folders/1th7uREWRgbzp-bvuc0BAReczTr7Pu6kB?usp=sharing

**Comment by ivanplazacic** [comment]
Here is the link to the edit:

https://drive.google.com/file/d/1SnaCRHUblXTpoIJA6Qlwx4P2gO9jfMPZ/view?usp=sharing

**Comment by encore9870** [comment]
Closing this as we have moved the podcast discussion away and will be using this repository for content pipeline drafts.
