### ISSUE TITLE
2.2 - Jason and Scott, treasury governance

### ISSUE THREAD

**Issue by ivanplazacic** [smartcontractresearchforum/research_content#219]
# Topic: Treasury Governance
Episode 2: Token voting and treasury governance 
(with  RMIT host, SCRF host, Distinguished Prof. Jason Potts, Scott Moore, Gitcoin)
- How do you spend your treasury? 
- What are grant programs?  
- What are the basic principles that should guide a grants program?
- When do you offer grants, as opposed to prizes, tenders, or building it internally (in the case of a team)?
- When should a treasury support another DAO? (i.e. DAO2DAO politics)?
- Is this different for DAOs and foundations?
- What are some of the ways voting can work in relation to treasury spending?
# Relevant Links
- Source
https://docs.google.com/document/d/1zJfbgSvx9SNhkgGPQX2cBE_2P0jBy4siG_-nIdWahL0/edit?usp=sharing
- Episode Folder Link
https://drive.google.com/drive/folders/1zKYlj_SL3sVyvalCFGZv1X2VgirptirX?usp=sharing
# Steps to completion
**Idea Proposal Stage**
- [x] Draft a potential topic to cover
- [x] Draft some specific questions 
- [x] Draft ideal guests 
- [x] Reach out to one to gauge interest
- [x] Any updates to the questions/topic?
- [x] Ask the first guest about who they’d want to talk to
- [x] If no, then come up with a second guest 
- [x] Reach out to the second guest 
- [x] Move on to scheduling

**Drafting**
- [x] Send out schedule/pick date
- [x] Send invite w/checklist and questions
- [x] Send confirmation email 24 hrs before recording
- [x] Check "Preparing for the interview" checklist
- [x] Confirm with all guests if the topic/question list looks good

**Peer Review**
- [x] Check the ‘Getting ready to record checklist’
- [x] Press record
- [x] Shift audio levels as needed
- [x] Receiving files for post

**Final Content Review**
- [x] Editing
- [x] Edit check/revisions
- [x] Export final video/save to drive
- [x] Export final audio/save to drive
- [x] Transcribe Audio
- [x] Pull transcript from Riverside 
- [x] Review transcript
- [x] Upload transcript to HackMD
- [ ] Submit pull request to github

**Editorial Review**
- [x] Start Show Notes draft
- [x] Share with team/revise
- [x] Finalize Show Notes

**Engagement and Calendaring**
- [ ] Engagement/Social meeting

**Published**
- [ ] Market Episode on Twitter/LinkedIn
- [x] Post to YouTube 
- [x] Host on [insert platform here]

**Comment by eleventh19** [comment]
guests are finalized, just sent the invite to the group to schedule

**Comment by eleventh19** [comment]
just sent another email, @ivanplazacic will help schedule as I dropped the ball

**Comment by eleventh19** [comment]
just sent out the invite for recording in just under two weeks

**Comment by eleventh19** [comment]
got rescheduled to next week, ironing out the timing

**Comment by eleventh19** [comment]
got postponed to 12/13

**Comment by eleventh19** [comment]
recording tn

**Comment by ivanplazacic** [comment]
Here is the link to all the backup/archival files:

https://drive.google.com/drive/folders/1GYcuGcUpdAUIDqOT64xlXR3M2HWPIFKc?usp=sharing

Here is the link to the separate raw recordings:

https://drive.google.com/drive/folders/1rrY7jOOhMiw8jWC-AOHxyntzYYBYXQpn?usp=sharing

**Comment by ivanplazacic** [comment]
Here is the link to the edit:

https://drive.google.com/file/d/1OUH49cQ1KY4UzUxG9xjiiRcQVFQ09kpm/view?usp=sharing

**Comment by encore9870** [comment]
Closing this as we have moved the podcast discussion away and will be using this repository for content pipeline drafts.
