### ISSUE TITLE
CANCELED 2.3 - Sinclair, Jess, Rich, Chris, Community engagement in DAOs

### ISSUE THREAD

**Issue by ivanplazacic** [smartcontractresearchforum/research_content#220]
# Topic: Community engagement in DAOs
Episode 3: Community engagement in DAOs
(with Prof. Chris Berg (RMIT host), SCRF host, Prof. Sinclair Davidson or Prof. Ellie Rennie?, industry person (Kain Warwick, Synthetix), maybe 1Hive)
- How do you build an audience?
- How can DAOs fund services and labour within the DAO? 
- What other incentives are there for DAO participation in governance?
# Relevant Links
- Source
https://docs.google.com/document/d/1zJfbgSvx9SNhkgGPQX2cBE_2P0jBy4siG_-nIdWahL0/edit?usp=sharing
- Episode Folder Link
https://drive.google.com/drive/folders/1zRhiMK9_6-yWhlwL8raU845agX3ldxQJ?usp=sharing
# Steps to completion
**Idea Proposal Stage**
- [x] Draft a potential topic to cover
- [x] Draft some specific questions 
- [x] Draft ideal guests 
- [x] Reach out to one to gauge interest
- [x] Any updates to the questions/topic?
- [x] Ask the first guest about who they’d want to talk to
- [x] If no, then come up with a second guest 
- [x] Reach out to the second guest 
- [x] Move on to scheduling

**Drafting**
- [x] Send out schedule/pick date
- [ ] Send invite w/checklist and questions
- [ ] Send confirmation email 24 hrs before recording
- [ ] Check "Preparing for the interview" checklist
- [ ] Confirm with all guests if the topic/question list looks good

**Peer Review**
- [ ] Check the ‘Getting ready to record checklist’
- [ ] Press record
- [ ] Shift audio levels as needed
- [ ] Receiving files for post

**Final Content Review**
- [ ] Editing
- [ ] Edit check/revisions
- [ ] Export final video/save to drive
- [ ] Export final audio/save to drive
- [ ] Transcribe Audio
- [ ] Pull transcript from Riverside 
- [ ] Review transcript
- [ ] Upload transcript to HackMD
- [ ] Submit pull request to github

**Editorial Review**
- [ ] Start Show Notes draft
- [ ] Share with team/revise
- [ ] Finalize Show Notes

**Engagement and Calendaring**
- [ ] Engagement/Social meeting

**Published**
- [ ] Market Episode on Twitter/LinkedIn
- [ ] Post to YouTube 
- [ ] Host on [insert platform here]

**Comment by eleventh19** [comment]
spoke to Jess the other day and we're good to move forward, sent the email to schedule

**Comment by eleventh19** [comment]
just sent a follow up email with a narrowed window of availability that should work better

**Comment by eleventh19** [comment]
this one got canceled

**Comment by encore9870** [comment]
Closing this as we have moved the podcast discussion away and will be using this repository for content pipeline drafts.
