### ISSUE TITLE
2.4 - Daniel and Darcy, Protecting the hart asset

### ISSUE THREAD

**Issue by ivanplazacic** [smartcontractresearchforum/research_content#221]
# Topic: Protecting the hart asset
Episode 4: Protecting the hart asset: Making a DAO and its treasury robust against attack
(Kelsie (RMIT), Eugene (SCRF), Dr. Darcy Allen (RMIT), Daniel Ospina(Governance Researcher).
- What are treasuries vulnerable to?
- Insider attacks
- Rent seeking
- External threats
- How do you make a treasury robust against these threats?
- Examples: The DAO. 
- Other DAO vulnerabilities (Kelsie)
# Relevant Links
- Source
https://docs.google.com/document/d/1zJfbgSvx9SNhkgGPQX2cBE_2P0jBy4siG_-nIdWahL0/edit?usp=sharing
- Episode Folder Link
https://drive.google.com/drive/folders/1BAS0PypkU0DY2Cn8FvVeSi-7VpiLCJCt?usp=sharing
# Steps to completion
**Idea Proposal Stage**
- [x] Draft a potential topic to cover
- [x] Draft some specific questions 
- [x] Draft ideal guests 
- [x] Reach out to one to gauge interest
- [x] Any updates to the questions/topic?
- [x] Ask the first guest about who they’d want to talk to
- [x] If no, then come up with a second guest 
- [x] Reach out to the second guest 
- [x] Move on to scheduling

**Drafting**
- [x] Send out schedule/pick date
- [x] Send invite w/checklist and questions
- [x] Send confirmation email 24 hrs before recording
- [x] Check "Preparing for the interview" checklist
- [x] Confirm with all guests if the topic/question list looks good

**Peer Review**
- [x] Check the ‘Getting ready to record checklist’
- [x] Press record
- [x] Shift audio levels as needed
- [x] Receiving files for post

**Final Content Review**
- [x] Editing
- [x] Edit check/revisions
- [x] Export final video/save to drive
- [x] Export final audio/save to drive
- [x] Transcribe Audio
- [x] Pull transcript from Riverside 
- [x] Review transcript
- [x] Upload transcript to HackMD
- [ ] Submit pull request to github

**Editorial Review**
- [x] Start Show Notes draft
- [x] Share with team/revise
- [x] Finalize Show Notes

**Engagement and Calendaring**
- [ ] Engagement/Social meeting

**Published**
- [ ] Market Episode on Twitter/LinkedIn
- [x] Post to YouTube 
- [x] Host on [insert platform here]

**Comment by eleventh19** [comment]
emailed everyone to schedule

**Comment by eleventh19** [comment]
just sent an invite for 12/6

**Comment by eleventh19** [comment]
recorded Sunday, @ivanplazacic please add a link to where the raw audio

**Comment by ivanplazacic** [comment]
Here is the link to all the backup/archival files:

https://drive.google.com/drive/folders/1kqmGuOjUAIn4DJ1ZBGu0v17DKOPqiJ96?usp=sharing

Here is the link to the separate raw recordings:

https://drive.google.com/drive/folders/1uL02VLB7aem3KkE5Y412kpLlHm19n5Sb?usp=sharing

**Comment by encore9870** [comment]
Closing this as we have moved the podcast discussion away and will be using this repository for content pipeline drafts.
