### ISSUE TITLE
Research Summary: “Do you need a Blockchain”

### ISSUE THREAD

**Issue by Tony363** [smartcontractresearchforum/research_content#222]
Wust, Karl et al. "Do You Need A Blockchain?". Eprint.Iacr.Org, 2021, https://eprint.iacr.org/2017/375.pdf.

I found this paper from this youtube video, https://youtu.be/Zz5kkdvN_DQ , explaining the 9 issues with blockchain.

"_Abstract_—Blockchain is being praised as a technological innovation which allows to revolutionize how society trades and interacts. This reputation is in particular attributable to its properties of allowing mutually mistrusting entities to exchange financial value and interact without relying on a trusted third party. A blockchain moreover provides an integrity protected data storage and allows to provide process transparency. In this paper we critically analyze whether a blockchain is indeed the appropriate technical solution for a particular application scenario. We differentiate between permissionless (e.g.,Bitcoin/Ethereum) and permissioned (e.g. Hyperledger/Corda) blockchains and contrast their properties to those of a centrally managed database. We provide a structured methodology to determine the appropriate technical solution to solve a particular application problem. Given our methodology, we analyze in depth three use cases — Supply Chain Management, Interbank and International Payments, and Decentralized Autonomous Organizations and conclude the article with an outlook for further opportunities."

Summary Draft: https://docs.google.com/document/d/15fFZz99fknVrpsKG831Ns1-2MxiC9lxmGV__kfMswFw/edit?usp=sharing

Completion Date: Once "Towards private on chain algorithmic trading" settled, I Suspect a draft summary to be completed in no more than 2-3 days. Tentatively Nov. 8th hence my onboarding goes smoothly.

-Tony

**Comment by Tony363** [comment]
anything else I should do?

**Comment by twan-dev** [comment]
Adding a few notes to reflect the latest requirements

- See below for LCR's approval
- James mentioned in an Oct 28 email that you have been onboarded

![Screen Shot 2564-11-02 at 22 33 53](https://user-images.githubusercontent.com/85469891/139867838-177630ef-008e-4adb-9ae3-4adef56ad51a.png)

**Comment by twan-dev** [comment]
@Tony363 How's the summary going! Any updates to the estimated date of completion?

**Comment by Tony363** [comment]
@twan-dev I'm almost done the draft. I got context for.esch sub section. just gotta make of the stuff I filled are congruent to the sub section contexts. but otherwise you can find people to do peer reviews I think

**Comment by Tony363** [comment]
@twan-dev I roughly looked over my draft again. I think its appropriate to move on to peer review. Just gonna say my midterms are coming up from 17th - 23rd. Gonna spend more time studying for that these 2 weeks.

**Comment by twan-dev** [comment]
OK

**Comment by twan-dev** [comment]
- [x] All fields described in the Template for that content type have been filled out.
- [x] PM has notified James and Faith of this draft. At least 2 Peer Reviewers have been briefed about this content.

Thank you Faith for picking this up and helping with peer review.

**Comment by Fizzymidas** [comment]
Please, I need comment access to the draft.
@Tony363 
@twan-dev

**Comment by Tony363** [comment]
@Tony363 how about now?

**Comment by twan-dev** [comment]
@Fizzymidas sorry about that...

**Comment by Fizzymidas** [comment]
It's still view only.
Please set permission to anyone with link can comment.

**Comment by Tony363** [comment]
![Screenshot_20211110-161614_Docs.jpg](https://user-images.githubusercontent.com/48950649/141075582-21bde83c-924a-4559-b0f7-2c7bcff6225c.jpg)

 I double checked. It should be “anyone on the internet with the link can comment”

**Comment by Fizzymidas** [comment]
Works now
Thank you

**Comment by Fizzymidas** [comment]
Peer review done
@twan-dev 
@Tony363

**Comment by Tony363** [comment]
@Fizzymidas Thank you for your kind suggestions for my draft! There were some parts where I just didn't proof read enough while some parts where it made more sense to me to keep the original wordings. @twan-dev I want through the suggestions @Fizzymidas suggested. Please advise for the next step.

**Comment by Fizzymidas** [comment]
Thanks for addressing the suggestions. @Tony363 
@twan-dev over to you!

**Comment by twan-dev** [comment]
- [x] All comments from Peer Reviewers have been discussed and addressed by authors. 
- [x] All suggestions provided by Peer Reviewers have been resolved.

**Comment by cipherix** [comment]
Pretty straightforward summary and interesting topic choice @Tony363 -- added a few comments for clarity. Ready for editorial review contingent upon their resolution.

**Comment by jamesmcgirk** [comment]
Posted GtM questions, waiting for resolution of aforementioned changes to proceed with Editorial Review

**Comment by jamesmcgirk** [comment]
Note from Researcher meeting -- we want this summary to follow our standard citation procedure, so during edit process, move the citations to a reference section and convert to a single reference to the original paper

**Comment by Tony363** [comment]
@cipherix @jamesmcgirk Ive addressed the Final content review contexts as best I can and also answered all the GtM questions for the editorial review as well. Please kindly look over the changes and prescribe the next set of action to take.

**Comment by jamesmcgirk** [comment]
Next step is an editorial review, I’ll take care of it this afternoon

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by jamesmcgirk** [comment]
One step before the last step, @Tony363 - do you mind adding a bit more to the Key Terms? check some of the summaries in the forum for a model (e.g. https://www.smartcontractresearch.org/t/research-summary-a-comparative-analysis-of-the-platforms-for-decentralized-autonomous-organizations-in-the-ethereum-blockchain/955 )

**Comment by Tony363** [comment]
@jamesmcgirk will do~

**Comment by zubepaul** [comment]
Will assign Ralph L. as engagement/moderation for this post

**Comment by Tony363** [comment]
@jamesmcgirk Maybe check again on the Key terms. Im not sure whether this is what is expected or not as I directly referenced some definitions from blockchain-council.org.

**Comment by jamesmcgirk** [comment]
@Tony363 they're meant to be more than definitions, think of them as part of the summary, how do they pertain to the summary. Check out the link I posted for you for a model.

**Comment by jamesmcgirk** [comment]
Tony working on key terms, will finish after his midterms.

**Comment by Tony363** [comment]
@jamesmcgirk Thank you for reminding me to add the TLDR. My midterms and juggling of multiple commitments really hit a number on my quality of output. Please check the key terms again to see if there is anything missing! Thankyou~

**Comment by ralphlombreglia** [comment]
I copyedited the summary doc using "Suggestion" mode; the editor(s) and author should accept my changes (if you agree) and publish the summary when ready. I also filled out most sections of the GtM; the spreadsheet said "GtM questions done" but I found nothing but a blank GtM template.

**Comment by jamesmcgirk** [comment]
@Tony363 a couple of other fixes for you to make, in addition to Ralph's comments -- consider opening a similar summary in another window for formatting guidance, big items: summary should be longer and more detailed, we use bulleted TL;DRs,  no need for ALL-CAPS, consider whether Subheads are necessary, make sure definitions match house style

**Comment by jamesmcgirk** [comment]
overall in much better shape, @ralphlombreglia indicates that the GtM is complete, so whenever the edits are ready we'll be ready to go

**Comment by Tony363** [comment]
@jamesmcgirk Ive looked through all the edit suggestions again. Though Im not sure if I did the styling right. Please check.

**Comment by ralphlombreglia** [comment]
On 11/24 I did a complete copyedit of the summary and filled out most fields on the GtM doc.

**Comment by zubepaul** [comment]
GtM plan is completed. Ready for researcher meeting. @Tony363 Need to coordinate a breakout with @zubepaul @ralphlombreglia

**Comment by Tony363** [comment]
I would be available after 2200 taiwan time? so in 18 hours? My wednessday would be tough. My Thursday is alot more free for me.

**Comment by zubepaul** [comment]
@twan-dev GtM and engagement review completed. Can be published no sooner than December 8th, 2021
@Tony363

**Comment by twan-dev** [comment]
@Tony363 I think you didn't delete the citation numbers (the numbers in brackets that come after a sentence and were suppose to point towards a citation. Since you've deleted all other citations they are confusing). @jamesmcgirk Are we on the same page with this issue? If so @Tony363  should make sure that fix happens before the summary gets published.

**Comment by twan-dev** [comment]
@Tony363 I also see that you have a different naming convention for each of your section (such as giving every section a number) and even extra sections that doesn't exist in the SCRF summary template. You can check them out here.
https://github.com/smartcontractresearchforum/docs/blob/main/en/content_research_summary_template.md

**Comment by Tony363** [comment]
@twan-dev I think the "all other citations" are under the title of "additional references.". By giving each section a number, you mean my adding of "Section {number}" to SCRFs template titles that was not in the structure of the SCRF template?

**Comment by Tony363** [comment]
@twan-dev  https://drive.google.com/file/d/1vhtx80xjvlkf5GKEtSOm6SrB3CifLxho/view?usp=sharing <- would this be better for the issue you were describing?

**Comment by Tony363** [comment]
@twan-dev actually, im confused as to what to do with the citations.....

**Comment by twan-dev** [comment]
> By giving each section a number, you mean my adding of "Section {number}" to SCRFs template titles that was not in the structure of the SCRF template?
> @twan-dev https://drive.google.com/file/d/1vhtx80xjvlkf5GKEtSOm6SrB3CifLxho/view?usp=sharing <- would this be better for the issue you were describing?

Yes. We're on the same page. So what is that for?

> @twan-dev actually, im confused as to what to do with the citations.....

Nothing complicated. They don't belong to your summary so just remove them.

**Comment by twan-dev** [comment]
@Tony363 Need you to run the summary through Grammerly too

**Comment by Tony363** [comment]
@twan-dev for the "Section {numbering}", the paper itself was organized according to those sections and the only bullets that I could find to constructively put into SCRFs "Summary" section was specifically the definitions of each of the "Sections {numbering}" . So therefore i added them in as such.

**Comment by Tony363** [comment]
@twan-dev regarding the additional citations, just to confirm, I am to remove all of the citations and the numbering through out the draft and only keep the citation of the "Do you need a blockchain" itself?

**Comment by Tony363** [comment]
@twan-dev ,I taken down all additional citations and the number to the citations. I also went through Grammarly a bit more.

**Comment by twan-dev** [comment]
@Tony363 quite a few changes have been made. Let me know upon your next update. Hope to get this published today.

**Comment by Tony363** [comment]
@twan-dev I updated and made my inputs into the draft just now. Please check for further need to revisory or editorial changes.

**Comment by twan-dev** [comment]
@Tony363 See you in the forum.

**Comment by Tony363** [comment]
I'll publish it the first thing tomorrow morning~

**Comment by ralphlombreglia** [comment]
We asked @Tony363 to do a revision of the paper to bring it up to SCRF's 2022 standards.
He has now completed that revision. I've reviewed it and it looks good to me.

**Comment by Tony363** [comment]
@ralphlombreglia I have revised and posted the revision of "Do you need a Blockchain?" on the forum.
