### ISSUE TITLE
Research Summary Idea: Blockchain-Secured Smart Manufacturing in Industry 4.0: A Survey

### ISSUE THREAD

**Issue by jamesmcgirk** [smartcontractresearchforum/research_content#223]
## Link to source
[Blockchain-Secured Smart Manufacturing in Industry 4.0: A Survey | IEEE Journals & Magazine | IEEE Xplore 3](https://ieeexplore.ieee.org/abstract/document/9298839)

## Content type tag (summary, discussion)
Summary

## Category
Industry & Manufacturing

## Proposed tags
Blockchain, cybersecurity, Industry 4.0, smart contract, smart manufacturing

## Description of why this would be an interesting post
There are many studies regarding the application of technologies for resource organization and system operation of blockchain secured smart manufacturing in Industry 4.0, however, the promotion of blockchain systems has been impeded by various issues such as scalability, flexibility, and cybersecurity. The paper discusses eight potential cybersecurity issues and how blockchains can overcome those issue barriers in Industry 4.0. Summarizing this research paper for SCRF would be a step towards the promotion of developing blockchain systems in manufacturing sector.

**Comment by jamesmcgirk** [comment]
@KiraTheLight
welcome to Github

**Comment by jamesmcgirk** [comment]
this is where you will leave a link to the google document

**Comment by jamesmcgirk** [comment]
@KiraTheLight testing testing hoping this lands in your email

**Comment by twan-dev** [comment]
@jamesmcgirk Hold on
@KiraTheLight   Please complete this before we move to the next stage
- [ ] Author has been Onboarded to Github and is the assignee of the ticket.
- [ ] Author has filled out the ticket correctly, in accordance with the Required Ticket Format.
    - [x] Title
    - [x] Description
    - [x] Link to PDF or Research Pulse Issue
    - [ ] Link to draft Google Doc
    - [x] Subtags
    - [ ] Assignee
    - [x] Estimated Completion Date 
- [x] Tagged Content Type
- [x] Author has linked the discussion where the topic was approved by the LRC as a response to the ticket.
- [ ] Author has added a blank draft doc with the appropriate Content Type Template and added it to Shared Google Drive

**Comment by KiraTheLight** [comment]
@jamesmcgirk Thank you! I've also received the notification in my email
@twan-dev Ok, I'll try

**Comment by KiraTheLight** [comment]
Link to the Google Doc draft: https://docs.google.com/document/d/1bAjDI3zw8PRRtn7dDXdWLWSL7Fs2mZ-8qpv5VlPKWxM/edit?usp=sharing

**Comment by twan-dev** [comment]
@KiraTheLight Added the summary template to your draft. Now if you can give us an estimation to your completion date, you would be good to go. (Just an estimation. You can change it anytime.)

**Comment by KiraTheLight** [comment]
Estimated Completion Date：12/31 (might change)

**Comment by twan-dev** [comment]
@KiraTheLight  How's the summary going! Any updates to the estimated date of completion?

**Comment by KiraTheLight** [comment]
No change on the estimated date of completion.

**Comment by KiraTheLight** [comment]
New date of completion: 31January 2022

**Comment by KiraTheLight** [comment]
New date of completion: 20 February 2022

**Comment by KiraTheLight** [comment]
New date of completion: 30 April 2022

**Comment by twan-dev** [comment]
The author's busy and requested to close the issue
