### ISSUE TITLE
Podcast Episode 1: Culture and onboarding and X: cryptoeconomics 

### ISSUE THREAD

**Issue by virtualtart** [smartcontractresearchforum/research_content#224]
## Steps to completion

- [ ] Draft a potential topic to cover
- [ ] Draft some specific questions 
- [ ] Draft ideal guests 
- [ ] Reach out to one to gauge interest
- [ ] Any updates to the questions/topic?
- [ ] Ask the first guest about who they’d want to talk to
- [ ] If no, then come up with a second guest 
- [ ] Reach out to the second guest 
- [ ] Move on to scheduling 

---

## Topic: Culture & Incentivization in Decentralized Ecosystems 

Episode 1: Culture and onboarding and X: cryptoeconomics 
(with SCRF host, Nathan Schneider, and Abbey Titcomb at Radicle) 
What role does culture play? 
Discuss Nathan’s paper and Vitalik’s response to it - cryptoeconomics as a limitation on governance 
What problems can culture help solve? 

## Link to source

[https://docs.google.com/document/d/1zJfbgSvx9SNhkgGPQX2cBE_2P0jBy4siG_-nIdWahL0/edit#](url)

## Assignee 
Sam Houle

## Size
medium?

**Comment by eleventh19** [comment]
close this out as this was an old duplicate card
