### ISSUE TITLE
Research Summary: The Title of your summary

### ISSUE THREAD

**Issue by jamesmcgirk** [smartcontractresearchforum/research_content#225]
## Link to source
https://www.airitilibrary.com/Publication/alDetailedMesh1?DocID=U0001-1702202111162100 4

## Content type tag (summary, discussion)
Summary

## Category
Consensus

## Proposed tags
Consensus algorithm, Stellar Consensus Protocol(SCP), Federated Byzantine Agreement System(FBAS)

## Description of why this would be an interesting post

FBAS, introduced by Stellar foundation, provides a brand new idea to consortium chains using PBFT, Tendermint, and HotStuff as their backbone. Nodes following FBAS settings is granted a much higher level of flexibility in terms of trusted peers. With the trade-off of slower throughput, trusts in FBAS is more similar to a real-world one. SCP being an implementation of FBAS used by Stellar does not has the most impressive throughput and thus has a certain level of scalability issue. vFBAS, introduced by this paper, modifies SCP such that its throughput is greatly improved under the condition of less Byzantine behaviors. Conditions like environmental monitoring blockchain where nodes may not believe in every other yet with little incentive to be malicious can take an advantage of this consensus algorithm.

Links to background reading (0 to 3 items)
vFBAS.pdf (1.1 MB)

**Comment by encore9870** [comment]
test was successful
