### ISSUE TITLE
Research Summary: Blockchain for Edge of Things: Applications, Opportunities, and Challenges

### ISSUE THREAD

**Issue by rjx223** [smartcontractresearchforum/research_content#228]
Content-type tag:
Summary

Category: 
IoT and the Blockchain (?) 

Proposed tags:
blockchain, IoT, edge computing, Industry 4.0, smart contract, cybersecurity

Description of why this would be an interesting post: 

Based on responses from my previous summary, SoK: Applying Blockchain Technology in Industrial Internet of Things, there is already an interest in the forum on blockchain and edge computing, but to my knowledge, no summary on this topic yet. Please see my annotated bibliography for context: 

[1] T. Gadekallu, Q. Pham, D. Nguyen, P. Reddy, N. Deepa, B. Prabadevi, P. Pathirana, J. Zhao, and W-J. Hwang, “Blockchain for Edge of Things: Applications, Opportunities, and Challenges,” IEEE Internet of Things Journal, October 2021. [2327-4662]. Available: https://www.researchgate.net/publication/355165963_Blockchain_for_Edge_of_Things_Applications_Opportunities_and_Challenges. [Accessed Oct. 29, 2021].

The researchers conducted a qualitative study, collecting data from 146 sources to examine the applications, opportunities, and challenges of the novel Blockchain Edge of Things (BEoT) paradigm. While past research has focused on BEoT scenarios, this study is one of the first to provide a comprehensive literature review on BEoT with an extensive survey on its use cases. Initially, this study explores the opportunities of BEoT in Industry 4.0 by observing its usability in various smart industrial applications. The researchers then supply a generic architecture for the BEoT. Subsequently, their analysis suggests that the integration of blockchain into the EoT will enhance security systems by providing services like “access authentication, data privacy, attack detection, and trust management” [1]. Challenges such as security, standardization, and resource management are discussed. Finally, future research directions and enabling technologies are presented, including blockchain performance in the EoT, the integration of Artificial Intelligence and BEoT, the cognitive edge, and BEoT in 5g.

Estimated date of completion: 12/18

**Comment by jamesmcgirk** [comment]
Yes to Rachel’s onboarding :)

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by rjx223** [comment]
@twan-dev I intend to complete the summary as part of the mentorship workshop. Estimated date of completion would be 12/18

**Comment by twan-dev** [comment]
@cipherix Would you please take a look and see if the paper is good enough for a post?

**Comment by cipherix** [comment]
I think we have plenty of open-ended summaries on the emergence of IoT. I think what could be particularly helpful is to see how cryptoassets (& supporting technologies) have been used in this context.

An interesting option on this front is [LNGate: Powering IoT with Next Generation Lightning Micro-payments using Threshold Cryptography](https://arxiv.org/pdf/2105.08902.pdf), which was featured on [Research Pulse #15](https://www.smartcontractresearch.org/t/research-pulse-issue-15-05-28-21/445) - is this something you would be interested in summarizing @rjx223?

**Comment by rjx223** [comment]
@cipherix Ok, thanks for the consideration. I appreciate the recommendation and am interested.
