### ISSUE TITLE
Research Summary for "Offline verification of Blockchain data for remote IoT/resource constrained devices

### ISSUE THREAD

**Issue by dr-chain** [smartcontractresearchforum/research_content#23]
Draft:

https://docs.google.com/document/d/1XvVS2agNlSvL0k45oDPi8kRrM22N_U9I97osNyg53KQ/edit

Paper: https://ieeexplore.ieee.org/abstract/document/9044957

The second part of the paper deals with the offline verification of blockchain data. This is an important issue for blockchain application as remote resource constrained devices cannot directly communicate with blockchain. A trust on an intermidiary is imperative. The proposed algorithm solves the issue with a double signature algorithm implemented cleverly using a Secure Element

**Comment by jamesmcgirk** [comment]
In progress, should be done in ~week as DV wraps up his academic obligations

**Comment by drvarun** [comment]
Finished drafting, flagging for content review

**Comment by jamesmcgirk** [comment]
@visavishesh @cipherix - wasn't sure who to tag on this one, Dr. Varun says it's ready for content review.

**Comment by cipherix** [comment]
@drvarun content looks great, but there are some missing areas as per our Research Summary format:

https://docs.google.com/document/d/1gs-a4wsgZhLxDioJzQjZDpOvDPl0xqrEKiQazY9nTEU/edit?usp=sharing

If you could please update it to keep it consistent other summaries, that'd be much appreciated. Moving this to drafting now.

**Comment by drvarun** [comment]
@jamesmcgirk Content OKed by LN. Edited the summary to comply with the format (https://github.com/smartcontractresearchforum/research_content/blob/main/templates/research_summary.md) 
Flagging for the editorial review now.

**Comment by jamesmcgirk** [comment]
@drvarun - looks really good overall, I made some changes to the TL;DR section which you should take a glance at to make sure I didn't obscure the meaning of. Otherwise mostly formatting changes.

**Comment by cipherix** [comment]
Went through another review, the new section looks good. Ready to post once the GTM field is filled.

**Comment by drvarun** [comment]
@cipherix The GTM is filled in the original RS. Do you want a separate document for it?

**Comment by jamesmcgirk** [comment]
@drvarun looks like he's updating the ticket to reflect that he approved the last edit

**Comment by cipherix** [comment]
Ok, tagging @tjd233 for engagement. 

@drvarun, ready to post whenever you get a chance

**Comment by drvarun** [comment]
@tjd233 Post is published. @jamesmcgirk and @cipherix thank you. Moving it to the published category and closing the issue.

**Comment by jamesmcgirk** [comment]
Reopening, just because this hasn't gone through the engagement process yet, moving back to calendaring

**Comment by zubepaul** [comment]
Go to market completed.
