### ISSUE TITLE
Research Summary: Penetration Testing a US Election Blockchain Prototypes

### ISSUE THREAD

**Issue by 29988122** [smartcontractresearchforum/research_content#230]
Pull straightly from Research Pulse # 35
Draft link:
https://docs.google.com/document/d/1JhbL2n-p1-wirSb99w_jRfi1p1a4R490YL2XOlpItQk/edit

Ongoing draft, since @easonc13 https://github.com/EasonC13 asked for this in the community call, I think I might as well raise this issue sooner before it's finished. 

I'll ping @twan-dev again together with #215 , after: 
1. I get familiar with the new documenttion pipeline template and fill in the tick boxes so that PM won't have to babysit me (I should complete them myself)
2. I finished this draft. 60~70% atm.

**Comment by twan-dev** [comment]
Hey Jerry, glad to have you back. 

Sorry for not letting you know earlier about the actual context of this update. You don't have to fill in the tick boxes but all tickets start from idea proposal stage now. I'll have to move it back to idea proposal for now to comply with the new rules. 

Also part of the new rules - you already own another ticket that is still in drafting, can we take that to next stage before you continue to invest in this one?

- [x] Author has been Onboarded to Github.
- [ ] Author has filled out the ticket correctly, in accordance with the Required Ticket Format.
   - [x] Title
   - [ ] Description of why this summary is novel, timely, and interesting
   - [ ] Link to PDF or Research Pulse Issue
   - [x] Link to draft Google Doc
   - [ ] Subtags (if no subtags are available, authors should feel free to create their owns)
   - [ ] Assignee
   - [ ] Estimated Completion Date
   - [ ] Tagged Content Type
- [x] Author has linked the discussion where the topic was approved by the LRC as a response to the ticket.
- [x] Author has added a blank draft doc with the appropriate Content Type Template and added it to Shared Google Drive

**Comment by cipherix** [comment]
This is a great paper @29988122 -- an excellent choice.

**Comment by twan-dev** [comment]
Closing this because Jerry is busy with other papers. Jerry might reopen later, but for now up for grabs to anyone.

**Comment by 29988122** [comment]
Progess report.
```
Research impulse link:
https://www.smartcontractresearch.org/t/research-pulse-issue-35-10-18-21/895
Tags: security, e-voting
Estimated completion date: completed.
Content type: summary
```
Link's the same.

Be advised: this paper is of mid-low quality, with numerous outrageous "suggestions" and "findings".
However, considering that:
1. This is the FIRST ATTEMPT from us gov, to use blockchain to experiment on voting
2. The penetration testing and audit done by UCCS, although immature, are still a very interesting case, on "how will a team fail on adopting blockchain on existing applications".
So that I still finished it. Some of the implementations on the *blockchain voting application* is laughable, even. Very educational.

If there's any SCRF peer reviewer has actual penetration testing experiences, he/she can help me to "add more" to this summary, essentially correcting authors results. Otherwise it should stay in its current form as that's what the authors wrote(I've already added and changed as much as I can), other than some format change if suggested.

**Comment by twan-dev** [comment]
You're not working on this until the other 2 drafts are finished.

**Comment by 29988122** [comment]
I disagree. 

The "people shouldn't be working on multiple drafts at once" rule applies to those who don't finish them and use them as excuse to cheat money from SCRF.

This is a 100% finished **draft**, there's nothing more can be done on my side.

As a helper, a PM, you can either:
- Raise format suggestions, we'll see if they make sense or not, I'm open to it as that's what we've already done.
- Find a peer reviewer who can equally contribute to this summary/semi discussion post (at least 10% of it are what I added, not by the authors originally)

Or you can be bureaucratic, and close this ticket again. We'll see.
