### ISSUE TITLE
Research Summary: A Survey on Ethereum Systems Security: Vulnerabilities, Attacks, and Defenses

### ISSUE THREAD

**Issue by cryptomarabout** [smartcontractresearchforum/research_content#231]
This paper classifies Ethereum's vulnerabilities based on a strong literature review. They also study specific attacks that have occurred and discuss various type of defenses.

Link to publication: https://dl.acm.org/doi/fullHtml/10.1145/3391195

Link to validation of Research Summary's proposal in Discord: https://discord.com/channels/784234332617048065/784234333111451670/908673708271501352

**Comment by cipherix** [comment]
Approved

**Comment by cipherix** [comment]
Great suggestion, but this paper has already been summarized!

https://www.smartcontractresearch.org/t/a-survey-on-ethereum-systems-security-vulnerabilities-attacks-and-defenses/98
