### ISSUE TITLE
Research Summary: An analysis and evaluation of lightweight hash functions for blockchain-based IoT devices

### ISSUE THREAD

**Issue by rjx223** [smartcontractresearchforum/research_content#234]
Description: The researchers evaluate common lightweight hash functions to determine practicality for deployment in blockchain-based IoT applications. With the ubiquity of IoT devices, blockchain technologies are becoming increasingly prevalent within IoT environments. This study contributes new insight into key issues like energy efficiency and hardware security and provides lightweight hash functions performance metrics.

Estimated date of completion: 12/18/21

Link to working draft: https://docs.google.com/document/d/1s_kpofYcn3BQfCg2WC20zssV4xGSciLj_POMU0By9ew/edit#heading=h.gaxnhfrwk4jd

Source of approval: Research Pulse # 17
https://www.smartcontractresearch.org/t/research-pulse-issue-17-06-11-21/475

**Comment by twan-dev** [comment]
- [x] Author has been Onboarded to Github.
- [x] Author has filled out the ticket correctly, in accordance with the Required Ticket Format.
   - [x] Title
   - [x] Description of why this summary is novel, timely, and interesting
   - [x] Link to paper
   - [x] Link to draft Google Doc
   - [x] Subtags
   - [x] Assignee
   - [x] Estimated Completion Date
   - [x] Tagged Content Type
- [x] Author has linked the discussion where the topic was approved by the LRC
- [ ] Author has added a blank draft doc with the appropriate Content Type Template and added it to Shared Google Drive

**Comment by twan-dev** [comment]
@rjx223 How's the summary going! Everything on schedule?

**Comment by twan-dev** [comment]
@rjx223 Anything new?

**Comment by rjx223** [comment]
On schedule, will let you know if anything changes regarding the timeline.

**Comment by twan-dev** [comment]
- [x] All fields described in the Template for that content type have been filled out.
- [x] If there exists an available Peer Reviewer, PM has notified them of this draft.
- [x] Complete a first Grammarly check.
- [x] Ensure that the document adheres to the style guide and is formatted correctly.

**Comment by twan-dev** [comment]
The author doesn't seem available to continue on the summary in the short-term future. Moving to icebox and up for grabs to anyone.
