### ISSUE TITLE
Research Summary: Using Distributed Ledger Technologies to Improve and Maximise the Collection of Property Taxes

### ISSUE THREAD

**Issue by Fizzymidas** [smartcontractresearchforum/research_content#235]
Description: This post is a research summary under the SCRF Pan African Grant, about the blockchain use case for the collection of property tax in Africa and beyond.

Estimated date of completion: 10 Nov 2021

Link to Paper: https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3899060 

Link to working draft: https://docs.google.com/document/d/1W7kmCah6RSNw9oIpFg9axhWnWYIoCIZfGVGxs0CB75U/edit?usp=sharing

Source of approval: @Coinproz (PAG)

**Comment by twan-dev** [comment]
As this was created from #206 and was approved, drafted, and peer reviewed under the previous rules, we will be moving it directly to FCR

**Comment by twan-dev** [comment]
@Fizzymidas Got feedback from Lucas. We'll move this back to FCR once you've finished dealing with the latest comments from this review

**Comment by Fizzymidas** [comment]
Comments resolved.

**Comment by jamesmcgirk** [comment]
@Fizzymidas @twan-dev completed a PR

**Comment by jamesmcgirk** [comment]
@Fizzymidas thanks for reviewing my edits! I'll do one last read when you're done cc'd to @twan-dev

**Comment by jamesmcgirk** [comment]
@Fizzymidas added the GtM questions and a few tiny changes

**Comment by Fizzymidas** [comment]
Are all the GTM to be answered?

I am done with them now. Please, proceed.
@jamesmcgirk 
@twan-dev

**Comment by jamesmcgirk** [comment]
@zubepaul nb

**Comment by zubepaul** [comment]
@twan-dev @Fizzymidas Approved for publishing no sooner than January 21, 2022
