### ISSUE TITLE
Research Summary: DevOps for Ethereum Blockchain Smart Contracts

### ISSUE THREAD

**Issue by Astridchou** [smartcontractresearchforum/research_content#236]
Description: This paper provides a comprehensive investigation on leveraging DevOps approach on blockchain solutions, which may foster efficiency of software development and delivery.

Estimated date of completion: 2021/12/8

Link to Paper: http://eprints.cs.univie.ac.at/7141/1/document.pdf

Link to working draft: https://docs.google.com/document/d/1BVpH2j1Arfn50Yhycy9rBZGXu5EuTC7BSdLgje2jlgk/edit#heading=h.qafnps4urw0y

Source of approval: Research Pulse # 39

**Comment by twan-dev** [comment]
- [x] Author has been Onboarded to Github.
- [x] Author has filled out the ticket correctly, in accordance with the Required Ticket Format.
   - [x] Title
   - [x] Description of why this summary is novel, timely, and interesting
   - [x] Link to paper
   - [x] Link to draft Google Doc
   - [x] Subtags
   - [x] Assignee
   - [x] Estimated Completion Date
   - [x] Tagged Content Type
- [x] Author has linked the discussion where the topic was approved by the LRC
- [x] Author has added a blank draft doc with the appropriate Content Type Template and added it to Shared Google Drive

**Comment by Astridchou** [comment]
@twan-dev  I have changed the estimated date of completion and tagged tooling. Thank you very much for your help!

**Comment by twan-dev** [comment]
@Astridchou How's the summary been going?

**Comment by Astridchou** [comment]
@twan-dev Good, I can finish it on time (2021/12/5)

**Comment by twan-dev** [comment]
@Astridchou Please update the estimated date of completion

**Comment by Astridchou** [comment]
@twan-dev I have edited the estimated date of completion

**Comment by Astridchou** [comment]
@twan-dev I have completed the draft.

**Comment by twan-dev** [comment]
@ralphlombreglia Left a few comments. Moving to next stage after this is resolved (probably after the holiday ends).

**Comment by twan-dev** [comment]
- [x] All fields described in the Template for that content type have been filled out.
- [x] If there exists an available Peer Reviewer, PM has notified them of this draft.
- [x] Completed a first Grammarly check or reviewed by an editor.
- [x] Ensure that the document adheres to the style guide and is formatted correctly.

**Comment by Astridchou** [comment]
The format and content rewriting is finished

**Comment by twan-dev** [comment]
@Astridchou Please resolve the comments I left in the document, so we can move it to FCR :)

**Comment by twan-dev** [comment]
@Astridchou Please resolve the comments I left in the document 2 months ago, so we can move it to FCR :)

**Comment by twan-dev** [comment]
- [x]  All comments from Peer Reviewers have been discussed and addressed by authors.
- [x]  All suggestions provided by Peer Reviewers have been resolved.

**Comment by twan-dev** [comment]
@Astridchou @jamesmcgirk I've opened a HackMD file for collaboration: https://hackmd.io/OF-y28UkRKC1bUMFyOvhNw

Please convert the summary draft into Markdown before starting editorial review, and make sure it's in good formatting before moving to the next stage. The HackMD should be the source of reference for what will be posted to the forum.

**Comment by jamesmcgirk** [comment]
@twan-dev do I need hackMD access? I don't have a subscription

**Comment by twan-dev** [comment]
@jamesmcgirk You could register for a free account.

**Comment by twan-dev** [comment]
Thanks for pointing that out!

**Comment by jamesmcgirk** [comment]
@twan-dev - is it a good idea to edit in HackMD? I worry that we won't have access to spell checks and the versatility of Google Docs, which is a full-featured word processor. Of course I'm happy to do so if the decision has already been made

**Comment by twan-dev** [comment]
@jamesmcgirk I'll clarify my point: Make sure the final product is in HackMD, and the HackMD version is the version that has passed your review.

**Comment by jamesmcgirk** [comment]
Okay, I think I understand. Thank you.

**Comment by jamesmcgirk** [comment]
@twan-dev I did my edits in the HackMD, @Astridchou would you like to review them? https://hackmd.io/OF-y28UkRKC1bUMFyOvhNw (NB don't forget to do the GtM questions in the original google doc)
