### ISSUE TITLE
Research Summary: A Source­Code­Based Taxonomy for Ethereum Smart Contracts

### ISSUE THREAD

**Issue by tomideadeoye** [smartcontractresearchforum/research_content#238]
Description: This post is a research summary under the SCRF Mentorship Program. The summary identifies common elements of Ethereum Smart Contracts. The original paper seeks to encourage industry standards in the writing of smart contracts.

Estimated date of completion: Dec 1, 2021

Link to Paper: https://www.researchgate.net/publication/354901921_A_Source-Code-Based_Taxonomy_for_Ethereum_Smart_Contracts

Link to working draft: https://docs.google.com/document/d/18JqVBOBkk454LeG1hn2Wca-MC5_8dsftH3t7_N71jwo/edit?usp=sharing

Source of approval:  Research Pulse Issue #34 10/11/21 @ cipherix URL: https://www.smartcontractresearch.org/t/research-pulse-issue-34-10-11-21/876

**Comment by twan-dev** [comment]
@tomideadeoye thanks for the ticket. You would also need to add this ticket to the pipeline to start it off. I'll show you how if you need me (Discord).

**Comment by tomideadeoye** [comment]
> @tomideadeoye thanks for the ticket. You would also need to add this ticket to the pipeline to start it off. I'll show you how if you need me (Discord).

@twan-dev .... Thank you!! I will really appreciate. Please show me.

**Comment by twan-dev** [comment]
feel free to DM

**Comment by twan-dev** [comment]
something went wrong......I'll fix it once I have access

**Comment by twan-dev** [comment]
@tomideadeoye Did you have access problems?

**Comment by twan-dev** [comment]
- [x]  SCRF has been notified to onboard the author
- [x]  The ticket contains the following information
   - [x]  An estimated date of completion
   - [x]  Link to paper
   - [x]  Link to draft
   - [x]  Source of approval
- [x]  Author does not already have another working document in Drafting

**Comment by twan-dev** [comment]
- [ ] The summary is compliant with the running summary template
- [x] A spelling and grammar check is complete
- [ ] If there exists an available Peer Reviewer, PM has notified them of this draft.

Currently waiting for the author to finish the first item on the list.

**Comment by twan-dev** [comment]
The draft also passed Deane's review over the last couple days.

**Comment by twan-dev** [comment]
- [x] All comments from Peer Reviewers have been discussed and addressed by authors. 
- [x] All suggestions provided by Peer Reviewers have been resolved.

**Comment by cipherix** [comment]
Well done @tomideadeoye. Made a few minor changes. I appreciate the graphic you've created -- please post it as a response to the summary once posted. Moving it to editorial.

**Comment by jamesmcgirk** [comment]
@tomideadeoye I went through and switched to American English and made a few more corrections (and ran Grammarly). Please answer the GtM questions, next step is a brief interview by the engagement team cc'd @zubepaul

**Comment by zubepaul** [comment]
@jamesmcgirk assigned for engagement review

**Comment by jamesmcgirk** [comment]
@zubepaul @twan-dev GtM complete.

**Comment by zubepaul** [comment]
@twan-dev @tomideadeoye Engagement review completed. Can be published no sooner than March 16th 2022
