### ISSUE TITLE
Research Summary: "Why and How zk-SNARK Works"

### ISSUE THREAD

**Issue by bgits** [smartcontractresearchforum/research_content#24]
Paper:

https://arxiv.org/abs/1906.07221

Paper's contribution is a simplistic exposition with a sufficient and gradually increasing level of complexity, necessary to understand zk-SNARK without any prerequisite knowledge of the subject, cryptography or advanced math. The primary goal is not only to explain how it works but why it works and how it came to be this way.

**Comment by encore9870** [comment]
I'm closing all issues that are not actively being worked on. Reach out to me if you have questions!
