### ISSUE TITLE
Research Summary: Chartalist: Labeled Graph Datasets for UTXO and Account based blockchains

### ISSUE THREAD

**Issue by Tony363** [smartcontractresearchforum/research_content#242]
Author: Cuneyt G. Akcora, Friedhelm Victor, Murat Kantarcioglu, and Yulia R. Gel

Machine learning on blockchain graphs is an emerging field with many applications such as ransomware payment detection, price manipulation analysis, and money laundering detection. However, on many blockchains, analyzing the data requires domain expertise and computational resources which pose a significant barrier and hinder advancement in this field. To address this challenge, we introduce Chartalist, the first comprehensive platform to methodically access and use machine learning across a large selection of blockchains. Chartalist contains ML-ready datasets from unspent transaction output and account-based blockchains. Chartalist also provides data science tools for making the execution of machine learning tasks on blockchains easier. We envision that Chartalist can facilitate data modeling, analysis, and representation of blockchain data and attract a wider community of scientists to analyze blockchains. Chartalist is an open-science initiative that can be accessed at https://github.com/Chartalist.

Summary Draft: https://docs.google.com/document/d/1oisyeqXW-L9f9J0GQ2gghyPazZGAWE8e8GL_LxNu6LQ/edit?usp=sharing

Expected Completion Date:

**Comment by twan-dev** [comment]
Hello Tony, would you checkout the latest research summary ticket template that could be found at the upper right hand corner New issue > Get Started, and fill in the required information based on that template instead? Exclude anything that isn't relevant. 
Also, 
1. You need to write your own description. Pasting the abstract doesn't work.
2. The draft has to belong to the shared folder.
3. If you need approval, please make that request in the body of the ticket.

**Comment by Tony363** [comment]
@twan-dev I think im still waiting for access to that shared folder?

**Comment by Tony363** [comment]
I don't have access to the openreview paper itself despite having created an account on openreview. Ill explore what I can do, but for now, ill find another paper to do a research summary on
