### ISSUE TITLE
Research Summary: A systematic literature review of blockchain cyber security

### ISSUE THREAD

**Issue by vincenzospaghetti** [smartcontractresearchforum/research_content#246]
Link to document: https://reader.elsevier.com/reader/sd/pii/S2352864818301536?token=8E95113D59B003557C87C496594AF8A22E4A10223C489253DCD914000602C87CEFF14EB32B18999E3EB2B50EE9FAB20E&originRegion=us-east-1&originCreation=20211213181839

Pulled from Research Pulse on 12/13/21

Estimated date of completion: January 19, 2022

This summary will be novel, timely & interesting because DLT is gaining increasing traction across various industries and security is a primary benefit that practitioners and academics should have at the forefront of their knowledge. 

Link to draft Google Doc: https://docs.google.com/document/d/1cT0zLfsd0ohCaZYbgil0x2kFu30HfM7c4WshKsN7yV4/edit?usp=sharing

I cannot add an Assignee (myself) or tags at the moment (I am not getting the functionality).

**Comment by twan-dev** [comment]
- [x] Author has been Onboarded to Github.
- [x]  Author has filled out the ticket correctly, in accordance with the Required Ticket Format.
- [x]  Author does not already have another working document in Drafting
- [x]  The Idea has been approved

Moving this to drafting. Good luck! And sorry to hear about the access issue.

**Comment by vincenzospaghetti** [comment]
Awesome! Thank you, Twan.

Thanks,
Valerie

**Comment by vincenzospaghetti** [comment]
> January 13, 2022

**Comment by vincenzospaghetti** [comment]
new completion date of January 19, 2022

**Comment by twan-dev** [comment]
- [ ] A first check on format and writing is complete.
- [ ] A Peer Reviewer is ready to do reviews.

**Comment by twan-dev** [comment]
- [x] All comments from Peer Reviewers have been discussed and addressed by authors. 
- [x] All suggestions provided by Peer Reviewers have been resolved.

I reviewed the summary and it's ready to go : )

**Comment by cipherix** [comment]
FCR suggestions have been resolved -- moving it to Editorial Review.

**Comment by jamesmcgirk** [comment]
@vincenzospaghetti nice work on this one! I made a few edits and notes for you to review

**Comment by jamesmcgirk** [comment]
@vincenzospaghetti did a second pass of edits, and @zubepaul added the gtm questions

**Comment by jamesmcgirk** [comment]
@twan-dev @zubepaul GtM questions are complete. Assigned myself as a moderator. Moved to engagement

**Comment by jamesmcgirk** [comment]
@zubepaul ready for publication unless @twan-dev you'd like to review before

**Comment by zubepaul** [comment]
@vincenzospaghetti @twan-dev Engagement review completed and is clear for publication no sooner than March 2, 2022
