### ISSUE TITLE
Research Summary: A Survey of Verification, Validation and Testing Solutions for Smart Contracts

### ISSUE THREAD

**Issue by Astridchou** [smartcontractresearchforum/research_content#249]
Description: The test solutions for smart contracts are crucial for the deployment process. Knowing the analysis of these solutions can improve the product reliability and cost down. This paper makes a detailed survey for the use of the test tools and so to benefit the industry.    

Estimated date of completion: 2021/12/31

Link to Paper: https://arxiv.org/ftp/arxiv/papers/2112/2112.03426.pdf

Link to working draft: https://docs.google.com/document/d/1wyyfbvIss8pI_8g-Eh5aMwzScFosPNIumZNiS08pqhQ/edit#heading=h.vvotry7q60z4

Source of approval: Research pulse # 43

**Comment by Fizzymidas** [comment]
@twan-dev, this has a duplicate #271
