### ISSUE TITLE
An analysis of uniswap markets

### ISSUE THREAD

**Issue by visavishesh** [smartcontractresearchforum/research_content#25]
https://arxiv.org/pdf/1911.03380.pdf

https://docs.google.com/document/d/13FWfd1qSkpZpr4tRemNzfgf-qItT9K4I5oKZVCIWTqo/edit#heading=h.thzg29if21r

**Comment by jamesmcgirk** [comment]
@visavishesh done with my first pass, it's in really good shape - pretty much all of my edits are picky little things. Let me know when you're done and I'll have another look just to make sure I didn't introduce any errors

**Comment by jamesmcgirk** [comment]
moved it over to calendaring

**Comment by jamesmcgirk** [comment]
@jamesmcgirk to revive with Uniswap v 3 release
