### ISSUE TITLE
Research Summary: Understanding Security Issues in the NFT Ecosystem

### ISSUE THREAD

**Issue by LTTOguns** [smartcontractresearchforum/research_content#250]
Description: (Call for Summaries - List of Papers #41). Citation: Das, Dipanjan, et al. "Understanding Security Issues in the NFT Ecosystem." arXiv preprint arXiv:2111.08893 (2021).

The article is a systematic overview of the NFT ecosystem, identifying the emergence of NFTs, their protocols, prominent actors, and subsequently the privacy, security, usability issues, and malicious trading behaviors.The article is a systematic overview of the NFT ecosystem, identifying the emergence of NFTs, their protocols, prominent actors, and subsequently the privacy, security, usability issues, and malicious trading behaviors.

Estimated date of completion: 18th of December, 2021

Link to Paper: https://arxiv.org/pdf/2111.08893.pdf

Link to working draft: https://docs.google.com/document/d/1_aBw-nsFvV4kIlYYCNm8yHSP7YDEGP77/edit

Source of approval:

**Comment by twan-dev** [comment]
@LTTOguns Welcome aboard! Please note that although we wouldn't say no to people who strive to finish summaries as soon as possible, that should NOT come at the price of the quality.

As this is the first time you're doing a summary from the pipeline, I'll respect that and move it to Drafting right away. If you need more time, please, don't hesitate to update the estimation and let me know. Quality over quantity under _**this context**_ is better for both you and SCRF's growth.

- [x] Author has been Onboarded to Github.
- [x] Author has filled out the ticket correctly, in accordance with the Required Ticket Format.
- [x] Author does not already have another working document in Drafting
- [x] The Idea has been approved

**Comment by LTTOguns** [comment]
Thank you @twan-dev I submitted it to Deane on the 18th. I believe I am to await his review. I will await.

**Comment by muhammad-scrf** [comment]
Peer Review Complete

**Comment by twan-dev** [comment]
- [x] All comments from Peer Reviewers have been discussed and addressed by authors. 
- [x] All suggestions provided by Peer Reviewers have been resolved.

**Comment by cipherix** [comment]
Left some comments for you there @LTTOguns

**Comment by zubepaul** [comment]
@ralphlombreglia assigned as engagement team reviewer

**Comment by cipherix** [comment]
Thank you @LTTOguns -- moving to Editorial.

**Comment by jamesmcgirk** [comment]
@LTTOguns I made a couple of edits and a few suggestions for the TLDR and places to add slightly different definitions. Let me know when you're done and I'll make another pass

**Comment by LTTOguns** [comment]
@jamesmcgirk Thank you so much. I will do that and revert.

**Comment by jamesmcgirk** [comment]
@LTTOguns I made a few more changes, mostly shortening your definitions of smart contracts and Ethereum blockchain. I also rephrased the Rarible 98.14% wash-trade section, my read of it was that they were saying "Of the reports that were flagged, 98.14% belonged to Rarible because they give tokens for each trade. OpenSea accounted for 1.87% of the total, and SoRare was the remainder." If that's wrong, please feel free to revert. I'm just being extra cautious given that it's a very damning claim if 98.14% of their total trades are fraudulent, which it doesn't seem like the study is saying

**Comment by LTTOguns** [comment]
@jamesmcgirk, I understand and appreciate the caution. I have edited it. Please help to take another pass through the document. Thank you.

**Comment by jamesmcgirk** [comment]
@LTTOguns this is looking much better, GtM questions are complete, moving this into Engagement review cc @zubepaul @ralphlombreglia

**Comment by ralphlombreglia** [comment]
Hi @LTTOguns. I've been assigned as the engagement / moderation person for your summary. I'd like to have a 15-30 minute conversation to make sure we're coordinated. I'm presently in PST time, which I believe is 9 hours behind you. Please let me know what would be a convenient day / time for you to talk. Thanks.

**Comment by ralphlombreglia** [comment]
@zubepaul I have now completed the GtM document.

**Comment by LTTOguns** [comment]
@ralphlombreglia Thank you so much. How about 8pm my time today; that should be 11am your time. If that is not convenient for me please let me know what time range works for you, and will make it work. Thank you.

**Comment by ralphlombreglia** [comment]
@LTTOguns Just to be clear: You're talking about today meaning Saturday, correct? If so, yes I can do that. Are you on SCRF's Discord server? I can't find you there. If you are, would you please send me a friend request at @ralph? If you're not on Discord (and you should be), for today we can use Google Meet. But let me know.

**Comment by LTTOguns** [comment]
@ralphlombreglia Yes today Saturday. I am on Discord as @Bookie

**Comment by ralphlombreglia** [comment]
@zubepaul My interview with LTTOguns is complete. As of Monday 3/14/22 the piece should be ready to publish.

**Comment by zubepaul** [comment]
@twan-dev @LTTOguns  Engagement review completed, can be published no sooner than March 14th, 2022
