### ISSUE TITLE
Research Summary: Networks of Ethereum Non-Fungible Tokens: A graph-based analysis of the ERC-721 ecosystem

### ISSUE THREAD

**Issue by twan-dev** [smartcontractresearchforum/research_content#251]
Author: Dimitar @stayhungry07212 

Estimated date of completion: Jan 10th 

Link to Paper: https://arxiv.org/pdf/2110.12545.pdf

Link to working draft: https://docs.google.com/document/d/1bQERo2rMSK0_AHcpCtrHQKLv-ACspwgerMUDs_grvjA/edit

Source of approval: RP 37 11/01/21. Call for summaries.

**Comment by twan-dev** [comment]
- [x] SCRF has been notified to onboard the author
- [x] The ticket contains the following information
   - [x] An estimated date of completion
   - [x] Link to paper 
   - [x] Link to draft
   - [x] Source of approval
- [x] Author does not already have another working document in Drafting

**Comment by twan-dev** [comment]
- [ ]  The summary is compliant with the running summary template
- [ ]  A spelling and grammar check is complete
- [x]  If there exists an available Peer Reviewer, PM has notified them of this draft. @ralphlombreglia

First item almost finished.

**Comment by twan-dev** [comment]
- [x] All comments from Peer Reviewers have been discussed and addressed by authors. 
- [x] All suggestions provided by Peer Reviewers have been resolved.

**Comment by zubepaul** [comment]
@jamesmcgirk assigned for engagement review

**Comment by cipherix** [comment]
This summary looks ready for editorial review, thank you @stayhungry07212 for your work on this.

**Comment by jamesmcgirk** [comment]
@stayhungry07212 nice work, I barely made any edits. Posted the GtM questions for you to answer.cc'd to @zubepaul

**Comment by jamesmcgirk** [comment]
@stayhungry07212 has completed the GtM questions, starting work on a GtM and scheduling a conversation.

**Comment by jamesmcgirk** [comment]
gtm interview complete... finishing GtM @zubepaul okay to publish on Monday?

**Comment by zubepaul** [comment]
@twan-dev @stayhungry07212 Engagement review complete, can be published no sooner than March 30, 2022
