### ISSUE TITLE
Research Summary: A Decentralized Framework for Patents and Intellectual Property as NFT in Blockchain Networks

### ISSUE THREAD

**Issue by twan-dev** [smartcontractresearchforum/research_content#254]
Author: Faith @Fizzymidas 

Estimated date of completion: Dec 30, 2021

Link to Paper: https://assets.researchsquare.com/files/rs-951089/v1_covered.pdf?c=1633465371

Link to working draft: https://docs.google.com/document/d/1hnvprMUY2DjqzifFRFAphMNqqpt_pEJANI8f3nBYNcc/edit

Source of approval: RP 35 10/18/21. Mentorship Program 2021.

**Comment by twan-dev** [comment]
- [x]  SCRF has been notified to onboard the author
- [x]  The ticket contains the following information
   - [x]  Author
   - [x]  An estimated date of completion
   - [x]  Link to paper
   - [x]  Link to draft
   - [x]  Source of approval
- [x]   Author does not already have another working document in Drafting

**Comment by twan-dev** [comment]
Currently waiting for the author to finish the first draft. She has been tied up with private things, and will update the estimated date of completion once it is possible.

**Comment by Fizzymidas** [comment]
This is now completed and can go to review.
@twan-dev

**Comment by twan-dev** [comment]
- [ ] A first check on format and writing is complete.
- [ ] A Peer Reviewer is ready to do reviews.

**Comment by jamesmcgirk** [comment]
@Fizzymidas hasn't heard from her peer reviewer, @twan-dev

**Comment by jamesmcgirk** [comment]
@Fizzymidas made some suggestions throughout, mostly changing past tense to present (house style) there also seems to be a chunk missing, I don't quite understand the leap from an NFT-based patent system to a global IP protection system. with @twan-dev's permission, maybe you could add a bit to the summary so this is clear

**Comment by Fizzymidas** [comment]
Thank you. I have just resolved them. Could you clarify what you mean by a chunk missing?
I also do not understand the leap you are referring to.

**Comment by ralphlombreglia** [comment]
Hi @Fizzymidas. I've added our Go-to-Market questions at the bottom of your working draft.

https://docs.google.com/document/d/1hnvprMUY2DjqzifFRFAphMNqqpt_pEJANI8f3nBYNcc/edit#

Please answer them as soon as you can, and notify me here when you're finished.

(Note: the question "Please list 4 questions that we can ask you to get conversation going?" is particularly important to us.)

**Comment by Fizzymidas** [comment]
Thank you @ralphlombreglia 
They have now been answered.

**Comment by ralphlombreglia** [comment]
Thanks @Fizzymidas. I'll look at your answers ASAP (tomorrow at the latest). 

Re your questions: Those were asked by James, who is now out on vacation for the next two weeks. I'm sure the "missing chunk" and "the leap" refer to the same thing: i.e., his sense of a logical gap from "an NFT-based patent system to a global IP protection system." @twan-dev, do you also share this view with James?

**Comment by Fizzymidas** [comment]
Okay.
Perhaps the missing chunk and leap is because the paper is theoretical and there was no simulation or practical application. To support their claim of using NFTs as patents, the authors referred to other IP-related use of NFTs.

**Comment by jamesmcgirk** [comment]
That would be a great thing to include as a bullet and detail in the summary

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Fizzymidas** [comment]
Okay. Apologies for disturbing you during your vacation!

I hesitated including that because I thought summaries were not to include personal opinions/bias that kind of pass judgement on the paper? I thought such a comment was best added in replies/comments while discussing the paper.

**Comment by ralphlombreglia** [comment]
Possibly. Let me read through the summary and I'll give you my opinion (in the next day or two). Meanwhile, @twan-dev do you have an opinion on this matter?

**Comment by encore9870** [comment]
Thanks for pinging. Where can I read about the conversation around the missing chunk and the leap?

**Comment by Fizzymidas** [comment]
@twan-dev, it started from here: https://github.com/smartcontractresearchforum/research_content/issues/254#issuecomment-1153309720

**Comment by twan-dev** [comment]
should be all good now. Pinging @zubepaul for scheduling when it can get published.

**Comment by ralphlombreglia** [comment]
@Fizzymidas Hi. I'm satisfied with your 4 Engagement questions. 

Regarding James: He suggested that you include an acknowledgement of the "lapse" or gap he noticed, along with your explanation that the authors had "referred to other IP-related use of NFTs" in lieu of any real-world patent examples. I just read through the paper and I didn't notice you making that point anywhere, but maybe I missed it. Has that point been included? Once it is, I think this is ready for publication.

**Comment by ralphlombreglia** [comment]
@Fizzymidas Also Faith, I forgot to say: If there's anything about our engagement process for this paper that you'd like to discuss, I'd be happy to have a short video call with you early next week. Let me know about that, and have a great weekend.

**Comment by Fizzymidas** [comment]
As I mentioned before, I thought it was best brought up in the comments and not in the summary.

I have now added it. Thanks.

**Comment by RuthTolulope** [comment]
Hi @Fizzymidas, here is the markdown version of your research summary https://hackmd.io/@content/ryQX8MUYc.
Kindly ensure that this is the ultimate version that is uploaded to the forum when publication is approved.
Let me know if you have any questions or need assistance.

**Comment by Fizzymidas** [comment]
Thank you.
Please, how is it 'uploaded'?

**Comment by RuthTolulope** [comment]
> Thank you. Please, how is it 'uploaded'?

You can upload it by copying the summary from HackMD and pasting it into 'new topic' on the forum. 
Happy to walk you through the process. Please let me know.

**Comment by Fizzymidas** [comment]
Great!
Thank you

**Comment by zubepaul** [comment]
@twan-dev @Fizzymidas Engagement review complete, can be published no sooner than July 6th 2022

**Comment by Fizzymidas** [comment]
Thank you @zubepaul 

@twan-dev this is now published. will you close the issue?

**Comment by jamesmcgirk** [comment]
See if you can do it an objective manner --just state the absence of testing or anything other than theory

It would be interesting to discuss the shortcomings in the comments -- they have some outdated assumptions about NFT use cases

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
