### ISSUE TITLE
Research Summary: Summarizing and Analyzing the Privacy-Preserving Techniques in Bitcoin and other Cryptocurrencies

### ISSUE THREAD

**Issue by twan-dev** [smartcontractresearchforum/research_content#258]
Author: Tolulope @RuthTolulope

Estimated date of completion: Feb 3, 2022

Link to Paper: https://arxiv.org/pdf/2109.07634.pdf

Link to working draft: https://docs.google.com/document/d/1c9qUVAkdIH5IGEvgYYkmhCwoa_VINKbWdQ8IuizkZyw/edit#

Source of approval: RP 32. Call for summaries.

**Comment by twan-dev** [comment]
- [x] Onboarding is either complete or waived.
- [x] The ticket contains the following information.
   - [x] Author
   - [x] An estimated date of completion
   - [x] Link to paper
   - [x] Link to draft
   - [x] Source of approval
- [x] Author does not already have another working document.

**Comment by RuthTolulope** [comment]
@twan-dev - the first draft of the summary is ready. Thank you.

**Comment by twan-dev** [comment]
- [ ] A first check on format and writing is complete.
- [ ] A Peer Reviewer is ready to do reviews.

**Comment by muhammad-scrf** [comment]
@twan-dev Nearly all suggestions/concerns addressed, just a couple of small ones came up today in last batch of fixes, should be easily fixed.

**Comment by twan-dev** [comment]
@muhammad-scrf Great! Let me know when it's ready

**Comment by zubepaul** [comment]
@ttaloute assigned for engagement review

**Comment by ttaloute** [comment]
@RuthTolulope I posted the GTM questions at the top of your draft.

**Comment by RuthTolulope** [comment]
@ttaloute noted, thank you.

**Comment by RuthTolulope** [comment]
> @RuthTolulope I posted the GTM questions at the top of your draft.

@ttaloute GTM completed.

**Comment by cipherix** [comment]
Made quite a few changes to this summary for clarity, please take a look @RuthTolulope -- moving it to Editorial @jamesmcgirk.

**Comment by twan-dev** [comment]
@RuthTolulope Please convert your draft into markdown and refer it as the source of truth for the content that should be posted to the forum using HackMD: https://hackmd.io/HQUpDEfoTKeTma_O9RdrEg

@jamesmcgirk @RuthTolulope  Please conduct editorial review in the HackMD, and make sure the summary looks good in markdown format.

**Comment by jamesmcgirk** [comment]
@RuthTolulope I'm going to experiment with editing it in HackMD, I'll let you know when I'm done with the suggested edits

**Comment by jamesmcgirk** [comment]
> @jamesmcgirk thank you, I will be awaiting your feedback.

I made my suggested edits in the Google doc, I'll transfer the text to the HackMD after you're done 

@twan-dev how do we handle graphics?

**Comment by RuthTolulope** [comment]
@jamesmcgirk I have completed editing. Thank you

**Comment by jamesmcgirk** [comment]
> @jamesmcgirk I have completed editing. Thank you

thanks! I'll review and transfer to the markdown

**Comment by jamesmcgirk** [comment]
@twan-dev https://hackmd.io/HQUpDEfoTKeTma_O9RdrEg?both here's my version, I added the graphics but I'm not sure they'll transfer to the forum

@RuthTolulope - please don't forget to fill out the go to market questions for @ttaloute !

**Comment by RuthTolulope** [comment]
> @twan-dev https://hackmd.io/HQUpDEfoTKeTma_O9RdrEg?both here's my version, I added the graphics but I'm not sure they'll transfer to the forum
> 
> @RuthTolulope - please don't forget to fill out the go to market questions for @ttaloute !

@jamesmcgirk I had completed GTM some weeks back and had a meeting with @ttaloute. I wonder where they disappeared to. Should I fill them again @ttaloute

**Comment by jamesmcgirk** [comment]
> > @twan-dev https://hackmd.io/HQUpDEfoTKeTma_O9RdrEg?both here's my version, I added the graphics but I'm not sure they'll transfer to the forum
> > @RuthTolulope - please don't forget to fill out the go to market questions for @ttaloute !
> 
> @jamesmcgirk I had completed GTM some weeks back and had a meeting with @ttaloute. I wonder where they disappeared to. Should I fill them again @ttaloute

oh! I remember @ttaloute telling me that you had now, never mind!

**Comment by jamesmcgirk** [comment]
ready for engagement

**Comment by zubepaul** [comment]
@twan-dev @RuthTolulope Engagement review complete. Can be published no sooner than May 9, 2022
