### ISSUE TITLE
Research Summary: Decentralized Network Governance: Blockchain Technology and The Future of Regulation

### ISSUE THREAD

**Issue by twan-dev** [smartcontractresearchforum/research_content#259]
Author: Deborah @Debbycool

Estimated date of completion: Jan 17 

Link to Paper: https://doi.org/10.3389/fbloc.2020.00012

Link to draft: https://docs.google.com/document/d/1hSyZTtcxpgps_rAHZDRCzalfPPHZsyLhufkNJ7GhTuw/edit

Source of approval: LRC

Note: This is a summary from the 2021 Mentorship Program.

**Comment by twan-dev** [comment]
- [x] Onboarding is either complete or waived.
- [x] The ticket contains the following information.
   - [x] Author
   - [x] An estimated date of completion
   - [x] Link to paper
   - [x] Link to draft
   - [x] Source of approval
- [x] Author does not already have another working document in Drafting.

**Comment by twan-dev** [comment]
- [ ] A first check on format and writing is complete.
- [ ] A Peer Reviewer is ready to do reviews.

**Comment by jamesmcgirk** [comment]
@debbycool - this was nicely written, I made a bunch of little changes throughout for you to review and flagged a couple of places in the summary that needed a tiny bit more clarification

**Comment by Debbycool** [comment]
> @debbycool - this was nicely written, I made a bunch of little changes throughout for you to review and flagged a couple of places in the summary that needed a tiny bit more clarification

@jamesmcgirk -Thank you for your prompt review and the comments. I'll effect the changes you suggested later today by God's grace and revert. 

I'm most grateful.

**Comment by Debbycool** [comment]
Good day Mr James,

Thanks for your review and the comments. I have effected the suggested
changes. Kindly go through and revert.

I'm most grateful sir.

Deborah Enyone Oni
Lead Partner
Hilton Top Solicitors

D/L : +234 9090245747
Office : +234 7047323799

Website: www.hiltontopsolicitors.com

**Comment by Debbycool** [comment]
Good day Mr James,

Thanks for your review and the comments. I have effected the suggested
changes. Kindly go through and revert.

I'm most grateful sir.


Deborah Enyone Oni
Lead Partner
Hilton Top Solicitors

D/L : +234 9090245747
Office : +234 7047323799

Website: www.hiltontopsolicitors.com

**Comment by Debbycool** [comment]
Good day @jamesmcgirk I've effected the suggested changes. I await further feedback from you.
I'm most grateful.

**Comment by Debbycool** [comment]
Good day @jamesmcgirk I humbly await your further feedback. God bless.

**Comment by twan-dev** [comment]
@Debbycool It's on me to do a final check before moving. Getting to it no later than this week.

**Comment by Debbycool** [comment]
Very well. Noted. God bless.

**Comment by jamesmcgirk** [comment]
@Debbycool I've taken another look -- looks like we need to flesh out the summary a little more, I think there's a little too much background on blockchain technology and not enough on the three modes of governance they articulate. Let's flesh those out a bit if we can. Think of the summary as being three parts, the intro to the tech, the governance and their conclusions./ cc @twan-dev - anything else we should add?

**Comment by Debbycool** [comment]
@jamesmcgirk Thanks for taking out time to review my research summary again.

I have effected the further suggestions by you. Kindly go through and let me have your feedback. 

I'm most grateful.

**Comment by Debbycool** [comment]
@jamesmcgirk <https://github.com/jamesmcgirk> Thanks for taking out time to
review my research summary again.

I have effected the further suggestions by you. Kindly go through and let
me have your feedback.

I'm most grateful.


Deborah Enyone Oni
Lead Partner
Hilton Top Solicitors

D/L : +234 9090245747
Office : +234 7047323799

Website: www.hiltontopsolicitors.com

**Comment by encore9870** [comment]
@Debbycool I left two comments. Hopefully will be the last two comments before FCR. Please take a look! I'm around and should be able to answer your questions if you have any.

**Comment by Debbycool** [comment]
@twan-dev Thanks for your feedback. I've removed the quotations.
I await further feedback. 

God bless.

**Comment by ralphlombreglia** [comment]
Hi @Debbycool. I'm the Engagement person for this summary on the SCRF Forum. As a first step, I've pasted in our "Go to Market (GTM) questions at the bottom of your summary draft:

https://docs.google.com/document/d/1hSyZTtcxpgps_rAHZDRCzalfPPHZsyLhufkNJ7GhTuw/edit#

Please answer these to the best of your ability. The question "Please list 4 questions that we can ask you to get the conversation going" is particularly important, so give that one some extra thought. 

Thanks! Looking forward to working with you.

**Comment by Debbycool** [comment]
Very well @ralphlombreglia I'll respond to the questions and revert. Looking forward to working with you as well.

**Comment by Debbycool** [comment]
Very well Mr Ralph. I'll respond to the questions and revert. Looking
forward to working with you as well.

God bless.

Deborah Enyone Oni
Lead Partner
Hilton Top Solicitors

D/L : +234 9090245747
Office : +234 7047323799

Website: www.hiltontopsolicitors.com

**Comment by RuthTolulope** [comment]
Hi @Debbycool, here is the markdown version of your research summary https://hackmd.io/@content/Hkuqo-k3q.
Kindly ensure that this is the ultimate version that is uploaded to the forum when publication is approved.
Let me know if you have any questions or need assistance.

**Comment by Debbycool** [comment]
Hello Ralph,

Trust this email finds you well.

I have responded to the go to market questions contained in my research
summary. Kindly ho through and revert.

God bless.

Deborah Enyone Oni
Lead Partner
Hilton Top Solicitors

D/L : +234 9090245747
Office : +234 7047323799

Website: www.hiltontopsolicitors.com

**Comment by Debbycool** [comment]
Thanks for your mail @RuthTolulope . Noted.

**Comment by Debbycool** [comment]
Hello @ralphlombreglia ,


Trust this email finds you well.


I have responded to the go to market questions contained in my research summary. Kindly go through and revert. 


God bless.

**Comment by ralphlombreglia** [comment]
Hi @Debbycool: I have read your GtM answers and I think you did a great job. Thank you. I recommend moving this paper to the next step toward publication. Also, I made a few very light edits and comments on the piece, if you can take a look at those and import them into your HackMD file if you agree with them.

**Comment by Debbycool** [comment]
Hello @ralphlombreglia Thanks for your feedback. Could you kindly guide me on how to locate your comments so I can import them and also how can I move it to the next stage for publication afterwards?

Thanks.

**Comment by Debbycool** [comment]
Hello  Mr Ralph,

Thanks for your feedback. Could you kindly guide me on how to locate your
comments so I can import them and also how can I move it to the next stage
for publication afterwards?

I humbly await your reply.

Thanks.

Deborah Enyone Oni
Lead Partner
Hilton Top Solicitors

D/L : +234 9090245747
Office : +234 7047323799

Website: www.hiltontopsolicitors.com

**Comment by zubepaul** [comment]
@twan-dev @Debbycool @ralphlombreglia @MichaelSCRF 
Per Ralph above, Engagement review is completed. This summary has Engagement approval to be published no sooner than July 26th, 2022 on the forum.

**Comment by Debbycool** [comment]
Thank you Mr Zube,

I appreciate you and every member of the SCRF that contributed to the
success of my completing this summary.

Kindly guide, I'm I to do any other thing to see to the publication?

I await your response sir.

God bless.

Deborah Enyone Oni
Lead Partner
Hilton Top Solicitors

D/L : +234 9090245747
Office : +234 7047323799

Website: www.hiltontopsolicitors.com

**Comment by zubepaul** [comment]
Thank you for the question, @Debbycool. Your responsibility now is to publish your Markdown version to the forum user your username. That way you are getting credit for it! You are approved to publish on July 26th or after.

From an engagement perspective, we also have some expectation that you will reply to comments and questions that initially show up on the forum regarding the research you have summarized. 

I'm looking forward to seeing your work on the forum and the discussion that follows!

**Comment by Debbycool** [comment]
Very well Mr Zube. Noted with thanks.

Deborah Enyone Oni
Lead Partner
Hilton Top Solicitors

D/L : +234 9090245747
Office : +234 7047323799

Website: www.hiltontopsolicitors.com

**Comment by Debbycool** [comment]
Hi Tolu,

My research summary has been approved for publishing on the 26th of July
2022 which is tomorrow. Could you kindly guide me on how to publish on the
github and how to submit an invoice after publishing?

I await your response.

God bless.

Deborah Enyone Oni
Lead Partner
Hilton Top Solicitors

D/L : +234 9090245747
Office : +234 7047323799

Website: www.hiltontopsolicitors.com

**Comment by Debbycool** [comment]
Hi Tolu, one more thing, kindly guide me also on where to propose a new
topic for research and how to ccess the available SCRF topics for research.

Thanks and God bless.

Deborah Enyone Oni
Lead Partner
Hilton Top Solicitors

D/L : +234 9090245747
Office : +234 7047323799

Website: www.hiltontopsolicitors.com

**Comment by RuthTolulope** [comment]
Sure! I’m happy to help. I’ll send you a message on Discord.

**Comment by Debbycool** [comment]
Very well. Greatly appreciated.

Deborah Enyone Oni
Lead Partner
Hilton Top Solicitors

D/L : +234 9090245747
Office : +234 7047323799

Website: www.hiltontopsolicitors.com
