### ISSUE TITLE
Research Summary: SoK: How private is Bitcoin? Classification and Evaluation of Bitcoin Mixing Techniques

### ISSUE THREAD

**Issue by twan-dev** [smartcontractresearchforum/research_content#260]
Author: Thanh @tnguyen4341

Estimated date of completion: March 14, 2022

Link to Paper: https://eprint.iacr.org/2021/629.pdf

Link to working draft: https://docs.google.com/document/d/1pE_rd6ge-GcH0ImGNQNhNnHA06gDeZP-VAvOj9jBfZE/edit#heading=h.z7faj3pzgfpb

Source of approval: RP 34. Call for Summaries.

**Comment by twan-dev** [comment]
- [x]  Onboarding is either complete or waived.
- [x]  The ticket contains the following information.
   - [x]  Author
   - [x]  An estimated date of completion
   - [x]  Link to paper
   - [x]  Link to draft
   - [x]  Source of approval
- [x]  Author does not already have another working draft.

**Comment by twan-dev** [comment]
- [ ]  A first check on format and writing is complete.
- [ ]  A Peer Reviewer is ready to do reviews.

**Comment by cipherix** [comment]
Very informative summary @tnguyen4341, good background section.  Moving to editing.

**Comment by zubepaul** [comment]
@ttaloute is assigned for engagement review

**Comment by jamesmcgirk** [comment]
@cipherix / @twan-dev I think the definitions here need some work, which is why I'm moving this back to review.  Do one of you mind having a quick look to confirm before I alert TN?

**Comment by jamesmcgirk** [comment]
@tnguyen4341 I made some editorial suggestions, please let me know after you've had a look. Also left some questions for you to answer from the engagement team

**Comment by jamesmcgirk** [comment]
@twan-dev edits in, should we do the GtM questions together?

**Comment by jamesmcgirk** [comment]
@tnguyen4341 if you get a chance, we left some questions for you from the engagement team

**Comment by RuthTolulope** [comment]
Hi @tnguyen4341,  here is the markdown version of your research summary https://hackmd.io/@content/H1NyKPVt9
Kindly ensure that this is the ultimate version that is uploaded to the forum when publication is approved.
Let me know if you have any questions or need assistance.
Thank you.

**Comment by encore9870** [comment]
Moving to icebox until the author becomes available and in touch again

**Comment by encore9870** [comment]
This got picked up :)

https://www.smartcontractresearch.org/t/research-summary-sok-how-private-is-bitcoin-classification-and-evaluation-of-bitcoin-mixing-techniques/1906/2
