### ISSUE TITLE
Research Summary: A Systematic Literature Review on Blockchain Governance

### ISSUE THREAD

**Issue by twan-dev** [smartcontractresearchforum/research_content#261]
Author: Austin @Austinjul

Estimated date of completion: Feb 26, 2022

Link to Paper: https://arxiv.org/pdf/2105.05460.pdf

Link to working draft: https://docs.google.com/document/d/1yr0B1-b0UXNqh184_0EAutKr4AytdQd-d_t9NWY6rPA/edit

Source of approval: RP 14. Call for Summaries.

**Comment by twan-dev** [comment]
- [ ]  A first check on format and writing is complete.
- [ ]  A Peer Reviewer is ready to do reviews.

**Comment by twan-dev** [comment]
- [x] All comments from Peer Reviewers have been discussed and addressed by the authors.
- [x] All suggestions provided by Peer Reviewers have been resolved.

**Comment by zubepaul** [comment]
@zubepaul is assigned for engagement review

**Comment by jamesmcgirk** [comment]
@austinjul - made some edits, let me know when you're done with them

**Comment by zubepaul** [comment]
Go to market questions added to the summary content. Please let me know if you have questions about these questions @Austinjul

**Comment by Austinjul** [comment]
@jamesmcgirk thank you so much for your edits. I have updated the research summary

**Comment by Austinjul** [comment]
@zubepaul Okay, I will begin work on the market questions. I will notify you when I am done with the assignment

**Comment by jamesmcgirk** [comment]
@Austinjul don't forget to answer the go to market questions, please

**Comment by RuthTolulope** [comment]
Hi @Austinjul, here is the markdown version of your research summary https://hackmd.io/@content/Skw7OGRwq.
Kindly ensure that this is the ultimate version that is uploaded to the forum when publication is approved.
Let me know if you have any questions or need assistance.
Thank you.

**Comment by Austinjul** [comment]
Hi @zubepaul and @jamesmcgirk,

I am done with the GTM question. Please review

**Comment by Austinjul** [comment]
Hi, @RuthTolulope.

Looks good

**Comment by jamesmcgirk** [comment]
@twan-dev this one is probably ready for Engagement Review

**Comment by zubepaul** [comment]
@Austinjul This is ready for engagement review breakout session. We need to schedule a time to have about a 30 minute meeting where I can ask you some follow up questions and we can talk about encouraging conversation around the paper you summarized. Reaching me in our Discord chat is probably easiest (paulzed).
[GTM Document to review](https://docs.google.com/document/d/1kDl1z0L13DmK3hRwtIApdzLXH66NVA98a5eUfvW1gRE/edit#)

**Comment by zubepaul** [comment]
@twan-dev @Austinjul Engagement review complete. Can be published no sooner than June 13, 2022
