### ISSUE TITLE
Research Summary: Research and Development of Blockchain Recordkeeping at the National Archives of Korea

### ISSUE THREAD

**Issue by tebogonong** [smartcontractresearchforum/research_content#262]
Description: 

Estimated date of completion: 22 February 2022

Link to Paper:
https://doi.org/10.3390/computers10080090 

Link to working draft:
https://docs.google.com/document/d/1AFfhhUgVYIg0TKR0G3jIY-Oc2kaCuaC04Gi_lY_eYj0/edit 

Source of approval: 
Chris Bates

**Comment by jamesmcgirk** [comment]
@tebogonong did you mean to close this?

**Comment by tebogonong** [comment]
Greetings James

May I please have a google meets meeting with you where I share my screen. I’m struggling to add my issue to the normal content pipeline. It’s meant to go to the peer review stage but certain heading aren’t coming up on my end. 

Warmest regards 
Tebogo

**Comment by jamesmcgirk** [comment]
Sure! Let me just see if I can take care of it first -- I think the problem may be that @twan-dev has to approve new issues

**Comment by jamesmcgirk** [comment]
Closing this, because I created a new ticket for @tebogonong on the content pipeline https://github.com/smartcontractresearchforum/research_content/issues/264
