### ISSUE TITLE
Research Summary: Research and Development of Blockchain Recordkeeping at the National Archives of Korea

### ISSUE THREAD

**Issue by jamesmcgirk** [smartcontractresearchforum/research_content#264]
Description:

Estimated date of completion: 22 February 2022

Link to Paper:
https://doi.org/10.3390/computers10080090

Link to working draft:
https://docs.google.com/document/d/1AFfhhUgVYIg0TKR0G3jIY-Oc2kaCuaC04Gi_lY_eYj0/edit

Source of approval:
Chris Bates

**Comment by Coinproz** [comment]
Not sure if Tebogo has proper permissions

**Comment by jamesmcgirk** [comment]
@tebogonong - I've recreated your card here

**Comment by jamesmcgirk** [comment]
@twan-dev - Chris has checked this, and it is ready for Peer Review

**Comment by twan-dev** [comment]
I have been available to Tebogo since Feb 28 via email, and have communicated that her summary isn't ready for peer review because the draft isn't in SCRF's drive and the content doesn't follow our guide. 

This ticket also needs to be closed because it shouldn't be created or moved by James.
