### ISSUE TITLE
Research Summary: SoK: Blockchain Governance

### ISSUE THREAD

**Issue by twan-dev** [smartcontractresearchforum/research_content#265]
Author: Fotis @pvblick-vniversal-friend

Estimated date of completion: April 28, 2022

Link to Paper: https://arxiv.org/abs/2201.07188

Link to working draft: https://docs.google.com/document/d/1YLSSBcYscHombzlMrG80hNZ8h_rJSDUKeq5L66CP2xY/edit?usp=sharing

Source of approval: RP 49

**Comment by twan-dev** [comment]
- [x]  Onboarding is either complete or waived.
- [x]  The ticket contains the following information.
    - [x]  Author
    - [x]  An estimated date of completion
    - [x]  Link to paper
    - [x]  Link to draft
    - [x]  Source of approval
- [x]  The author does not already have another working document.

**Comment by twan-dev** [comment]
- [x]  All fields described in the Template for that content type have been filled out.
- [x]  Content review is ready to take the ticket in the next round of review

**Comment by pvblick-vniversal-friend** [comment]
Summary ready for review.

**Comment by jamesmcgirk** [comment]
@pvblick-vniversal-friend this is in solid shape, only area that needs significant improvement is the TLDR which should be more comprehensive. Maybe add a little bit more of the context for this paper in the summary as well... other than that, a couple of minor edits

**Comment by pvblick-vniversal-friend** [comment]
I think it is ok now.

**Comment by pvblick-vniversal-friend** [comment]
I realized something a bit worrisome. The original article and link I found on the forum is of a previous version and the arxiv file has been been updated (since May 17th). The summary I did was based on the previous version and there seems to be some new information in the latest one.

What should be done in this case? Can I mention that this is a summary of a previous version?

**Comment by jamesmcgirk** [comment]
Maybe update it with a detailed comment on the forum

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by pvblick-vniversal-friend** [comment]
Editorial Review comments have been resolved.

**Comment by encore9870** [comment]
- [x] Reviewer's thumbs up
- [x] Markdown document (@RuthTolulope will be handling)

**Comment by RuthTolulope** [comment]
Hi @pvblick-vniversal-friend, here is the markdown version of your research summary https://hackmd.io/@content/B1wKng1c5.
Kindly ensure that this is the ultimate version that is uploaded to the forum when publication is approved.
Let me know if you have any questions or need assistance.

**Comment by pvblick-vniversal-friend** [comment]
So what's left now is to receive and answer the questions from the engagement team, right?

**Comment by zubepaul** [comment]
GTM questions have been added to the draft @pvblick-vniversal-friend. Please tag reply when that is done

**Comment by pvblick-vniversal-friend** [comment]
@zubepaul Done,

**Comment by zubepaul** [comment]
@pvblick-vniversal-friend The GTM strategy doc is completed and linked below. Please review it and we can have a discussion about refinements you would want to make in preparation for publication to the forum.
https://docs.google.com/document/d/1G0WYENROUmiH4v4xGyv78k18IZDJAQvVfAbX90dImyg/edit#

**Comment by zubepaul** [comment]
Conducting an experiment for Engagement
- [x] Engagement Board Task Created

Edit: It did not work as intended

**Comment by zubepaul** [comment]
@twan-dev @pvblick-vniversal-friend Engagement Review complete. Approved to publish no sooner than July 13, 2022

**Comment by encore9870** [comment]
Published July 15, 2022
