### ISSUE TITLE
Research Summary: A Short Survey on Business Models of Decentralized Finance (DeFi) Protocols

### ISSUE THREAD

**Issue by vincenzospaghetti** [smartcontractresearchforum/research_content#267]
Author: Valerie @vincenzospaghetti

Estimated date of completion: April 1, 2022

Link to Paper: https://arxiv.org/pdf/2202.07742.pdf

Link to working draft: https://docs.google.com/document/d/1gQ1IL-O7DRRL4Id0D2wrVQmRgj3N0PSciyj9sr6JT6k/edit

Source of approval: RP # 54

**Comment by twan-dev** [comment]
- [x] Onboarding is either complete or waived.
- [x] The ticket contains the following information.
   - [x] Author
   - [x] An estimated date of completion
   - [x] Link to paper
   - [x] Link to draft
   - [x] Source of approval
- [x] Author does not already have another working document.

**Comment by twan-dev** [comment]
I believe the summary author is planning to close this draft and work on another one instead
