### ISSUE TITLE
Research Summary: Testbed Design and Performance Analysis for Multilayer Blockchains

### ISSUE THREAD

**Issue by twan-dev** [smartcontractresearchforum/research_content#268]
Author: Seth @SethHasi  

Estimated date of completion: March 22, 2022

Link to Paper: https://ieeexplore.ieee.org/document/9461103 or https://drive.google.com/file/d/1eg0QxegsCjnC7SaAy0TioCL-zAMB8dim/view?usp=sharing internally

Link to working draft: https://docs.google.com/document/d/1cRJfdum5tcCjXUL9QwlAfkNaUK0b8jkObc5TzFWE9T4/edit

Source of approval: LRC

**Comment by twan-dev** [comment]
- [x]  Onboarding is either complete or waived.
- [ ]  The ticket contains the following information.
   - [x]  Author
   - [x]  An estimated date of completion
   - [x]  Link to paper
   - [ ]  Link to draft
   - [x]  Source of approval
- [x]  Author does not already have another working document.

**Comment by twan-dev** [comment]
- [ ] The first check on format and writing is complete.
- [ ]  Peer Review is ready to start

**Comment by jamesmcgirk** [comment]
@SethHasi - don't forget your edits!

**Comment by zubepaul** [comment]
@SethHasi Could you please finish the remaining GTM questions so that we can continue moving this piece toward publication?

**Comment by zubepaul** [comment]
@twan-dev @ttaloute @SethHasi 
Engagement review completed. Can be published on the forum no sooner than August 4, 2022.

**Comment by RuthTolulope** [comment]
Hi @SethHasi, here is the markdown version of your research summary https://hackmd.io/@content/HyU42CvTc.
Kindly ensure that this is the ultimate version uploaded to the forum.
Let me know if you have any questions or need assistance.
