### ISSUE TITLE
Research Summary: Three Attacks on Proof-of-Stake Ethereum

### ISSUE THREAD

**Issue by twan-dev** [smartcontractresearchforum/research_content#269]
Author: Dimitar (@stayhungry07212)

Estimated date of completion: April 28, 2022

Link to the paper: https://arxiv.org/pdf/2110.10086.pdf

Link to the draft: https://docs.google.com/document/d/1S9o4FdG5n-8CvLesl5oVtzt-u2h5XH96Uv4W8QM7yEY/edit

Source of approval: RP 36, Call for summaries

**Comment by twan-dev** [comment]
- [ ] Onboarding is either complete or waived.
- [ ] The ticket contains the following information.
    - [ ] Author
    - [ ] An estimated date of completion
    - [ ] Link to paper
    - [ ] Link to draft
    - [ ] Source of approval
- [ ] The author does not already have another working document.

**Comment by twan-dev** [comment]
@stayhungry07212 You're good to go!

**Comment by jamesmcgirk** [comment]
beginning my editorial review @stayhungry07212 cc @twan-dev

**Comment by encore9870** [comment]
scheduled to be done on June 6

**Comment by stayhungry07212** [comment]
Hi Twan,
I modified most parts of it, but seeing the feedback, James asked for the
overall update for Method and Result.
Currently, Method part is done. Follow-ups are added.
The result is left.
Would you please change the estimated day to June 13th?
Kind regards,
Dimitar

**Comment by encore9870** [comment]
Iceboxing for special project (by @cipherix) purposes. The GTM questions have been completed for future references.
