### ISSUE TITLE
Generate Intro Post

### ISSUE THREAD

**Issue by visavishesh** [smartcontractresearchforum/research_content#27]
- [ ] Define what SCRF is
- [ ] Define what SCRF is not
- [ ] Convert frowns upside down
- [ ] Explain how SCRF what SCRF is doing now
- [ ] Explain needs it fills
- [ ] Reinforce this is agnostic platform
- [ ] Convey connecting researchers and engineers
- [ ] Provide examples of above

**Comment by encore9870** [comment]
I'm closing all issues that are not actively being worked on. Reach out to me if you have questions!
