### ISSUE TITLE
Research Summary: A Formal Specification Smart-Contract Language for Legally Binding Decentralized Autonomous Organizations

### ISSUE THREAD

**Issue by twan-dev** [smartcontractresearchforum/research_content#270]
Author: Tomide (@tomideadeoye)

Estimated date of completion: April 21, 2022

Link to the paper: https://ieeexplore.ieee.org/abstract/document/9435331

Link to the draft: https://docs.google.com/document/d/1SYYAgfWyGBLzAKMZHnmjsQO1rQLbgCBGuCHot8UfKg8/edit

Source of approval: RP 15 Call for summaries

**Comment by twan-dev** [comment]
- [ ] Onboarding is either complete or waived.
- [ ] The ticket contains the following information.
    - [ ] Author
    - [ ] An estimated date of completion
    - [ ] Link to paper
    - [ ] Link to draft
    - [ ] Source of approval
- [ ] The author does not already have another working document.

**Comment by twan-dev** [comment]
@tomideadeoye You're good to go!

**Comment by twan-dev** [comment]
@tomideadeoye is there anything I need to know :)

**Comment by tomideadeoye** [comment]
Thanks @twan-dev ... still on it (T⌓T)

**Comment by twan-dev** [comment]
- [x] All fields described in the Template for that content type have been filled out.
- [x] Content review is ready to take the ticket in the next round of review

**Comment by jamesmcgirk** [comment]
@tomideadeoye this was a really clearly laid out, interesting summary. I've made some minor revisions throughout and left a suggestion for drastically cutting the length -- I think you could lose the description of the ontology in the summary and accompanying graphics because anyone after them would probably look in the original paper. I think simply showing the automotive use case and describing how they developed the SCL is enough.

**Comment by tomideadeoye** [comment]
Thanks @jamesmcgirk reverting soon

**Comment by osapeter** [comment]
Hello @tomideadeoye, I am from the content team, I have included some suggestions and inquiries for your validation. Thanks

**Comment by tomideadeoye** [comment]
Hello @osapeter. Noted with thanks. I will revert through the doc.

**Comment by tomideadeoye** [comment]
Hi @osapeter. I read a couple more related papers and adjusted the earlier summary. I also addressed all remaining comments. Help review and let me know your thoughts.

**Comment by osapeter** [comment]
Hello @tomideadeoye, many thanks for the feedback. Just a couple of suggestions and inquiries for your validation. Thanks

**Comment by encore9870** [comment]
https://www.smartcontractresearch.org/t/research-summary-a-formal-specification-smart-contract-language-for-legally-binding-decentralized-autonomous-organizations/2110?u=twan
