### ISSUE TITLE
Research Summary: A Survey of Verification, Validation and Testing Solutions for Smart Contracts

### ISSUE THREAD

**Issue by LTTOguns** [smartcontractresearchforum/research_content#271]
Description: The research paper aims to (i) identify existing solutions to the vulnerability issues of smart contracts, (ii) categorize and analyze the identified solutions, and (iii) juxtapose the advantages and disadvantages of each solution. A survey is carried out on the existing verification, validation, and testing  (VV&T) solutions for Smart Contracts; comparing the solutions to reveal loopholes. The findings reveal that using a complementary combination of VV&T solutions could eliminate limitations such as inconvenience, difficulty to use, and high cost of Smart Contracts. The general use of the VV&T imposes the limitations mentioned above. Consequently, the elimination would make Smart Contracts more secure.

Estimated date of completion: April 20, 2022

Link to Paper: https://arxiv.org/ftp/arxiv/papers/2112/2112.03426.pdf

Link to working draft: https://docs.google.com/document/d/1_PiRYi7Bnp2fgatLelz_8SXJ5sM1MZI3tm4IGTM98XU/edit?usp=sharing

Source of approval: RP 43. Call for summaries.

**Comment by twan-dev** [comment]
- [x] Onboarding is either complete or waived.
- [x] The ticket contains the following information.
    - [x] Author
    - [x] An estimated date of completion
    - [x] Link to paper
    - [x] Link to draft
    - [x] Source of approval
- [x] The author does not already have another working document.

**Comment by twan-dev** [comment]
- [x] A first check on format and writing is complete.
- [x] A Peer Reviewer is ready to do reviews.

**Comment by twan-dev** [comment]
Overall it's a very clean summary so thanks for your great work! Our general comments would be that we think the juice of the paper is how the different characteristics of VV&T solutions are compared, so the actual results after the comparison should take a slightly higher proportion in the summary. Please work on that and my other comments and it should be ready soon.

**Comment by jamesmcgirk** [comment]
@twan-dev am I editing this one now or is this being edited by someone else?

**Comment by twan-dev** [comment]
@jamesmcgirk We need Buki to make edits to her draft before moving on. You'll work with her once this hits editorial review!

**Comment by LTTOguns** [comment]
> Overall it's a very clean summary so thanks for your great work! Our general comments would be that we think the juice of the paper is how the different characteristics of VV&T solutions are compared, so the actual results after the comparison should take a slightly higher proportion in the summary. Please work on that and my other comments and it should be ready soon.

Okay duly noted. Thanks @twan-dev

**Comment by osapeter** [comment]
Hello @LTTOguns , I am from the content team, I have included some suggestions and inquiries for your validation. Thanks

**Comment by LTTOguns** [comment]
Noted @osapeter

**Comment by osapeter** [comment]
Hello @LTTOguns, thanks for the feedback update. I have included a few suggestions and inquiries for your validation. Thanks

**Comment by LTTOguns** [comment]
> Hello @LTTOguns, thanks for the feedback update. I have included a few suggestions and inquiries for your validation. Thanks

@osapeter Validation completed. Thank you.

**Comment by osapeter** [comment]
Hello @LTTOguns, thanks for the feedback update. Just a few minor suggestions for you action. Thanks

**Comment by LTTOguns** [comment]
> Hello @LTTOguns, thanks for the feedback update. Just a few minor suggestions for you action. Thanks

Thank you @osapeter The updates have been made.

**Comment by jring-o** [comment]
Cannot access draft.

**Comment by jring-o** [comment]
Requires significant edits. While the results are clear, I'm not really sure about anything the researchers did to achieve those results.

**Comment by encore9870** [comment]
Left some edits too @LTTOguns.

**Comment by encore9870** [comment]
https://www.smartcontractresearch.org/t/research-summary-a-survey-of-verification-validation-testing-solutions-for-smart-contracts/2109?u=twan
