### ISSUE TITLE
Onboarding Content for Chat (Discord) Go Live

### ISSUE THREAD

**Issue by SirAh0** [smartcontractresearchforum/research_content#273]
https://docs.google.com/document/d/1rX2Yzua2BaDn6MJqukC1FKvzEUi9yfbO/edit#heading=h.1fob9te

- [ ] 🏁-start-here content: Welcome, Useful Links, FAQ, Unlock Server

- [ ] review 📘-directory-faq descriptions for each channel. 

- [ ]  Bot Message To New Users

- [ ] Pinned Messages.

**Comment by twan-dev** [comment]
This should go to Research Team :)
