### ISSUE TITLE
Research Summary: DeFiRANGER: Detecting Price Manipulation Attacks On DeFi Applications

### ISSUE THREAD

**Issue by twan-dev** [smartcontractresearchforum/research_content#274]
Author: Tolu (@RuthTolulope)

Estimated date of completion: May 18, 2022

Link to Paper: https://arxiv.org/pdf/2104.15068.pdf

Link to working draft: https://docs.google.com/document/d/12x2vTsxB4nYQGxG_IRWyjuwAsX3BGyl-Fa4lHj-FQ5c/edit

Source of approval: RP. Call for summaries.

**Comment by twan-dev** [comment]
- [x] Onboarding is either complete or waived.
- [x] The ticket contains the following information.
   - [x] Author
   - [x] An estimated date of completion
   - [x] Link to paper
   - [x] Link to draft
   - [x] Source of approval
- [x] Author does not already have another working document.

**Comment by RuthTolulope** [comment]
Draft complete.

**Comment by jamesmcgirk** [comment]
@RuthTolulope I did a first editing pass, ready for you

**Comment by RuthTolulope** [comment]
> @RuthTolulope I did a first editing pass, ready for you

@jamesmcgirk Thank you, I have implemented the changes.

**Comment by jamesmcgirk** [comment]
@RuthTolulope made a few minor suggestions @zubepaul ready for engagement review once it's in markdown

**Comment by RuthTolulope** [comment]
Thanks @jamesmcgirk, changes implemented.

Here is the HackMD link: https://hackmd.io/@content/HyJbmqEY5

**Comment by ralphlombreglia** [comment]
Hi @RuthTolulope. I've pasted our go-to-market questions at the bottom of your working draft. 

https://docs.google.com/document/d/12x2vTsxB4nYQGxG_IRWyjuwAsX3BGyl-Fa4lHj-FQ5c/edit#

Please answer them as soon as possible and notify me here when you do.

(Note: the question "Please list 4 questions that we can ask you about this subject to get conversation going?" is particularly important to us.)

**Comment by RuthTolulope** [comment]
Thank you @ralphlombreglia. The GtM questions have been answered.

**Comment by ralphlombreglia** [comment]
Hi @RuthTolulope, I'm happy with your GtM answers and feel that we can move this paper along toward publication.

Is there anything relating to Engagement for this paper on our forum that you'd like to discuss? If so, I can meet you for a brief Discord meeting early next week. Let me know. Have a great weekend.

**Comment by RuthTolulope** [comment]
Thanks @ralphlombreglia I have nothing to discuss in particular, but I am happy to have a chat if you'd like one.

**Comment by zubepaul** [comment]
@RuthTolulope @ralphlombreglia @twan-dev 
Engagement review completed. Approved for forum publication no sooner than June 20, 2022

**Comment by ralphlombreglia** [comment]
@RuthTolulope Congrats on publishing! I was glad to see a couple of immediate questions from Ulysses — please make sure to answer him. That's much better than me or someone else internally at SCRF jumping in, though of course I will do that if the conversation starts to lag.

**Comment by RuthTolulope** [comment]
Thank you for the heads-up @ralphlombreglia I have responded to his questions.
