### ISSUE TITLE
Research Summary: Ethereum Name Service: the Good, the Bad, and the Ugly

### ISSUE THREAD

**Issue by twan-dev** [smartcontractresearchforum/research_content#275]
Author: Favour (@Hartxyz)

Estimated date of completion: April 22, 2022

Link to Paper: https://arxiv.org/pdf/2104.05185.pdff

Link to working draft: https://docs.google.com/document/d/1zCznhBF63LS8KvSLcBLoI9aQG7H99H4m-jwt45aP3gY/

Source of approval: RP 10. Call for summaries.

**Comment by twan-dev** [comment]
- [x] Onboarding is either complete or waived.
- [x] The ticket contains the following information.
     - [x] Author
     - [x] An estimated date of completion
     - [x] Link to paper
     - [x] Link to draft
     - [x] Source of approval
- [x] Author does not already have another working document.

**Comment by twan-dev** [comment]
- [x] All fields described in the Template for that content type have been filled out.
- [x] Content review is ready to take the ticket in the next round of review

**Comment by twan-dev** [comment]
It's a great summary that we don't get very often. 

I'll be leaving comments that came up in CR later.

But we didn't catch anything that needs to be changed at this stage. It's ready for FCR.

**Comment by Hartxyz** [comment]
> It's a great summary that we don't get very often.
> 
> I'll be leaving comments that came up in CR later.
> 
> But we didn't catch anything that needs to be changed at this stage. It's ready for FCR.

Thanks Twan. I'll be on standby.

**Comment by cipherix** [comment]
Very well done, I enjoyed reading this and made a few changes.

As noted, Privacy could be a very interesting discussion topic in the context of this paper. 

For example, this paper used ENS addresses to link the identity of millions of users: https://ieeexplore.ieee.org/abstract/document/9566179

Something in the spirit of "What are the implications for the users of this service?" would be a great addition to the "Discussion and Key Takeaways" section. 

Moving it to final edits board.

**Comment by Hartxyz** [comment]
> Very well done, I enjoyed reading this and made a few changes.
> 
> As noted, Privacy could be a very interesting discussion topic in the context of this paper.
> 
> For example, this paper used ENS addresses to link the identity of millions of users: https://ieeexplore.ieee.org/abstract/document/9566179
> 
> Something in the spirit of "What are the implications for the users of this service?" would be a great addition to the "Discussion and Key Takeaways" section.
> 
> Moving it to final edits board.

Thank you @cipherix.  I just read the abstract of the paper. Exactly what I guessed would be possible. 

I noticed the highlighted text in the document. Are you proposing we change the question to "What are the implications for the users of this service?"

**Comment by zubepaul** [comment]
@ralphlombreglia Added for GtM and Engagement process

**Comment by cipherix** [comment]
> I noticed the highlighted text in the document. Are you proposing we change the question to "What are the implications for the users of this service?"

Yes, something along those lines would facilitate some interesting discussions. The authors didn't really cover the privacy angle, but as the linked paper showcased, there are non-trivial privacy implications when using ENS.

**Comment by Hartxyz** [comment]
> > I noticed the highlighted text in the document. Are you proposing we change the question to "What are the implications for the users of this service?"
> 
> Yes, something along those lines would facilitate some interesting discussions. The authors didn't really cover the privacy angle, but as the linked paper showcased, there are non-trivial privacy implications when using ENS.

Alright. I'll implement the change.

**Comment by jamesmcgirk** [comment]
@ralphlombreglia @zubepaul I still haven't edited this one yet -- it still has to go through editorial review

**Comment by jamesmcgirk** [comment]
@twan-dev should we move this one to Editorial Review? Looks like @Hartxyz has finished her FCR edits

**Comment by twan-dev** [comment]
@cipherix highlighted this piece of text in the doc:
> - Would users not sacrifice privacy if they decide to explore the full functionality of ENS name records?

and commented that:

> Privacy could be a very interesting discussion topic in the context of this paper. 
> 
> For example, this paper used ENS addresses to link the identity of millions of users: [https://ieeexplore.ieee.org/abstract/document/9566179](https://www.google.com/url?q=https://ieeexplore.ieee.org/abstract/document/9566179&sa=D&source=docs&ust=1653571880721984&usg=AOvVaw329p2Rr19PLH_izOA7-PIi)
> 
> What are the implications for the users of this service?

The text is now changed to:
> - What are the implications for the users of this service?

@Hartxyz Can you provide color around the privacy implications? As suggested by @cipherix above:
> The authors didn't really cover the privacy angle, but as the linked paper showcased, there are non-trivial privacy implications when using ENS.

**Comment by Hartxyz** [comment]
> @cipherix highlighted this piece of text in the doc:
> 
> > * Would users not sacrifice privacy if they decide to explore the full functionality of ENS name records?
> 
> and commented that:
> 
> > Privacy could be a very interesting discussion topic in the context of this paper.
> > For example, this paper used ENS addresses to link the identity of millions of users: [https://ieeexplore.ieee.org/abstract/document/9566179](https://www.google.com/url?q=https://ieeexplore.ieee.org/abstract/document/9566179&sa=D&source=docs&ust=1653571880721984&usg=AOvVaw329p2Rr19PLH_izOA7-PIi)
> > What are the implications for the users of this service?
> 
> @Hartxyz Can you provide color around the privacy implications? As suggested by @cipherix above:
> 
> > The authors didn't really cover the privacy angle, but as the linked paper showcased, there are non-trivial privacy implications when using ENS.
> 
> The text currently in place would benefit more if you added the privacy implications:
> 
> > * What are the implications for the users of this service?

Hi @twan-dev, I have added some colour as requested. I hope it suffices.

**Comment by jamesmcgirk** [comment]
@Hartxyz a few minor edits to the TLDR, otherwise in good shape! @twan-dev ready for engagement and publication @zubepaul once they're taken care of cc @ralphlombreglia

**Comment by Hartxyz** [comment]
> @Hartxyz a few minor edits to the TLDR, otherwise in good shape! @twan-dev ready for engagement and publication @zubepaul once they're taken care of cc @ralphlombreglia

Thank you @jamesmcgirk. I've implemented all suggestions and comments.

**Comment by RuthTolulope** [comment]
Hi @Hartxyz, here is the markdown version of your research summary https://hackmd.io/@content/HykpYW0vc.
Kindly ensure that this is the ultimate version that is uploaded to the forum when publication is approved.
Let me know if you have any questions or need assistance.
Thank you.

**Comment by Hartxyz** [comment]
> Hi @Hartxyz, here is the markdown version of your research summary https://hackmd.io/@content/HykpYW0vc. Kindly ensure that this is the ultimate version that is uploaded to the forum when publication is approved. Let me know if you have any questions or need assistance. Thank you.

Hi @RuthTolulope . I have two questions: 
First, regarding the images. I can only see two in the markdown version. Is that all that would be uploaded?
Secondly, do I just copy and paste the markdown format to the forum?

**Comment by RuthTolulope** [comment]
> 

@Hartxyz Thanks for the catch, I will post the other pictures now.
Yes, you just copy and paste.

**Comment by Hartxyz** [comment]
> > 
> 
> @Hartxyz Thanks for the catch, I will post the other pictures now. Yes, you just copy and paste.

Alright. Thank you very much.

**Comment by RuthTolulope** [comment]
> > > 
> > 
> > 
> > @Hartxyz Thanks for the catch, I will post the other pictures now. Yes, you just copy and paste.
> 
> Alright. Thank you very much.

All done @Hartxyz

**Comment by ralphlombreglia** [comment]
@Hartxyz Hi. It sounds like you're all set to publish this piece. I've experimented with using HackMD files, and simply copying and pasting the *source code* column into the forum editor should work fine. Please let me know when you actually publish the piece. And thank you!
