### ISSUE TITLE
Research Summary: An Overview of Trees in Blockchain Technology: Merkle Trees and Merkle Patricia Tries

### ISSUE THREAD

**Issue by twan-dev** [smartcontractresearchforum/research_content#277]
Contributor: Nancy @circusqp

Estimated date of completion: May 30, 2022
(Extending 1-2 days to finish the background section)

Paper: https://www.researchgate.net/publication/358740207_An_Overview_of_Trees_in_Blockchain_Technology_Merkle_Trees_and_Merkle_Patricia_Tries

Draft: https://docs.google.com/document/d/1yyMYeRWTCxGUErETy_12U_yiyB_1oLP7_h5l7gC6NSs/edit#

Source of approval: RP 56, Call for Summaries

**Comment by twan-dev** [comment]
- [x]  Onboarding is either complete or waived.
- [x]  The ticket contains the following information.
   - [x]  Contributor
   - [x]  First Draft Turn-In Date Estimation
   - [x]  Link to paper
   - [x]  Link to draft
   - [x]  Source of approval
- [x]  The author does not already have another working document.

**Comment by twan-dev** [comment]
- [x]  Onboarding is either complete or waived.
- [x]  The ticket contains the following information.
   - [x]  Contributor
   - [x]  First Draft Turn-In Date Estimation
   - [x]  Link to paper
   - [x]  Link to draft
   - [x]  Source of approval
- [x]  The author does not already have another working document.

**Comment by encore9870** [comment]
- [x] All fields described in the Template for that content type have been filled out.

**Comment by osapeter** [comment]
Hello @circusqp, I am from the content team, I have included some suggestions and inquiries for your validation. Thanks

**Comment by circusqp** [comment]
Got it, taking a look

**Comment by circusqp** [comment]
completed edits, please have a look @osapeter @twan-dev

**Comment by encore9870** [comment]
https://www.smartcontractresearch.org/t/research-summary-an-overview-of-trees-in-blockchain-technology-merkle-trees-and-merkle-patricia-tries/2403?u=twan
