### ISSUE TITLE
Research Summary: DeFi Liquidity Management via Optimal Control: Ohm as a Case Study

### ISSUE THREAD

**Issue by twan-dev** [smartcontractresearchforum/research_content#278]
Contributor: Junxi @Songjunxi2000

Estimated date of first draft completion: July 31, 2022

Paper: https://web.stanford.edu/~guillean/papers/ohm-staking.pdf

Draft: https://docs.google.com/document/d/1hLjxCQt9Mblgidq0x7tWImoot1_yzKYyzb0HWfvTDRk/

Source of approval: RP 55, call for summaries

**Comment by encore9870** [comment]
- [x] Onboarding is either complete or waived.
- [x] The ticket contains the following information.
   - [x] Author
   - [x] An estimated date of completion
   - [x] Link to paper
   - [x] Link to the draft
   - [x] Source of approval
- [x] The author does not already have another working document.

**Comment by encore9870** [comment]
replacing with #339
