### ISSUE TITLE
Research Summary: An Empirical Study of Blockchain Repositories in GitHub

### ISSUE THREAD

**Issue by encore9870** [smartcontractresearchforum/research_content#279]
Contributor: Faith 

Drafting Deadline: June 20, 2022

Link to the Paper: https://arxiv.org/pdf/2205.08087.pdf

Link to the Draft: https://docs.google.com/document/d/16FGDG_CTckSLdwlH7lXLoaSN6bO_atqWR37R9_GOT5k/

Source of Approval: RP 66

**Comment by encore9870** [comment]
- [x]  Onboarding is either complete or waived.
- [x]  The ticket contains the following information.
   - [x]  Contributor
   - [x]  Drafting deadline
   - [x]  Link to the paper
   - [x]  Link to the draft
   - [x]  Source of approval
- [x]  The author does not already have another working document.

**Comment by encore9870** [comment]
@Fizzymidas You're good to go!

**Comment by Fizzymidas** [comment]
Draft ready.

**Comment by Fizzymidas** [comment]
@twan-dev

**Comment by encore9870** [comment]
We're expecting Faith to resume work around August! (correct me if I'm wrong)

**Comment by Fizzymidas** [comment]
Hi Twan, I think there is a misunderstanding. I am done with this research summary. You already did the first review.

You must be referring to the Discussion post on DAO legal wrappers that I expect to resume in August.

**Comment by osapeter** [comment]
Hello @Fizzymidas, I have included some suggestions and inquiries for your validation. Thanks

**Comment by Fizzymidas** [comment]
Thank you, I have resolved them.

Faith Obafemi
Legal Consultant, Trainer, and Writer
Emerging Technologies
www.fintconsulting.com
SMS/WhatsApp/Telegram: +234 806 323 2704

**Comment by osapeter** [comment]
Thanks for the feedback.

**Comment by jring-o** [comment]
A few suggested edits. Otherwise good to go.

**Comment by Fizzymidas** [comment]
Thank you @jring-o, I have just addressed your comments.
cc @twan-dev

**Comment by encore9870** [comment]
https://www.smartcontractresearch.org/t/research-summary-an-empirical-study-of-blockchain-repositories-in-github/1950
