### ISSUE TITLE
Research Summary: Blockchain Oracle Design Patterns 

### ISSUE THREAD

**Issue by encore9870** [smartcontractresearchforum/research_content#280]
Contributor: Favour (@Hartxyz)

Drafting Deadline: June 4, 2022

Link to the Paper: https://arxiv.org/pdf/2106.09349.pdf

Link to the Draft: https://docs.google.com/document/d/11fBPnNxZdJ4vIZZVRCE8O2dBCJe7wySEbXe9j0rkit4/edit

Source of Approval: RP 19, Call for Summaries

**Comment by encore9870** [comment]
- [x]  Onboarding is either complete or waived.
- [x]  The ticket contains the following information.
   - [x]  Contributor
   - [x]  Drafting deadline
   - [x]  Link to the paper
   - [x]  Link to the draft
   - [x]  Source of approval
- [x]  The author does not already have another working document.

**Comment by encore9870** [comment]
@Hartxyz you're good to go!

**Comment by encore9870** [comment]
- [x] All fields described in the Template for that content type have been filled out.

**Comment by ralphlombreglia** [comment]
Hi @Hartxyz. I'm the Engagement person for this summary on the SCRF Forum. As a first step, I've pasted in our "Go to Market (GTM) questions at the bottom of your summary draft. Please answer these to the best of your ability. The question "Please list 4 questions that we can ask you to get conversation going" is particularly important, so give that some extra thought. Thanks! Looking forward to working with you.

**Comment by Hartxyz** [comment]
> Hi @Hartxyz. I'm the Engagement person for this summary on the SCRF Forum. As a first step, I've pasted in our "Go to Market (GTM) questions at the bottom of your summary draft. Please answer these to the best of your ability. The question "Please list 4 questions that we can ask you to get conversation going" is particularly important, so give that some extra thought. Thanks! Looking forward to working with you.

Thank you @ralphlombreglia . I'm on it.

**Comment by ralphlombreglia** [comment]
Hi @Hartxyz. I know that answering the GtM questions intelligently takes some time. Please let me know when you think you'll be able to do that, or if you're having any problems with it.

**Comment by Hartxyz** [comment]
> Hi @Hartxyz. I know that answering the GtM questions intelligently takes some time. Please let me know when you think you'll be able to do that, or if you're having any problems with it.

Hello @ralphlombreglia. I have filled in my answers for the questions. Apologies for the delay.

**Comment by ralphlombreglia** [comment]
Hi @Hartxyz. No problem at all with your timing; I just reminded you to make sure you realized the questions were ready.

@twan-dev @zubepaul: I think the GtM questions are answered well and we can move this to the next step.

**Comment by osapeter** [comment]
Hello @Hartxyz, I am from the content review team, kindly review and update the summary. I have included some suggestions and inquiries for your validation. Thanks

**Comment by Hartxyz** [comment]
> Hello @Hartxyz, I am from the content review team, kindly review and update the summary. I have included some suggestions and inquiries for your validation. Thanks

Thank you @osapeter . I have reviewed all suggestions. I left a question to your comment. I'd really love some clarification on it.

**Comment by osapeter** [comment]
@Hartxyz I have included a sampled template item for your review in the comment. Thanks

**Comment by Hartxyz** [comment]
> @Hartxyz I have included a sampled template item for your review in the comment. Thanks

Please review the document. I have implemented all suggestions.

**Comment by jamesmcgirk** [comment]
@Hartxyz made some editing suggestions

**Comment by jamesmcgirk** [comment]
once we get those filled in, I'll take a stab at answering some of the GtM questions

**Comment by Hartxyz** [comment]
> once we get those filled in, I'll take a stab at answering some of the GtM questions

@jamesmcgirk I have implemented your suggestions. I also dropped a comment on the GTM questions.

**Comment by ralphlombreglia** [comment]
I created a GtM document for this summary: 

https://docs.google.com/document/d/1ejKEK8wefCE3N750gbg2IrKveE-yn9httcB4YV7q0EQ/edit#

@Hartxyz : You said "I also dropped a comment on the GtM questions." I'm not sure what you meant. Can you explain?

**Comment by Hartxyz** [comment]
> I created a GtM document for this summary:
> 
> https://docs.google.com/document/d/1ejKEK8wefCE3N750gbg2IrKveE-yn9httcB4YV7q0EQ/edit#
> 
> @Hartxyz : You said "I also dropped a comment on the GtM questions." I'm not sure what you meant. Can you explain?

Oh yes I was speaking to James. He had included the GtM questions again so the comment was to inform him that I had answered them already.

**Comment by RuthTolulope** [comment]
Hi @Hartxyz, here is the markdown version of your research summary https://hackmd.io/@content/rkIuHyua5.
Kindly ensure that this is the ultimate version that is uploaded to the forum when publication is approved.
Let me know if you have any questions or need assistance.

**Comment by zubepaul** [comment]
@twan-dev @Hartxyz 
Engagement review complete. Approved for posting no sooner than August 8, 2022

**Comment by Hartxyz** [comment]
The article has been published on the forum.

**Comment by encore9870** [comment]
Amazing! See you on the forum.
