### ISSUE TITLE
Research Summary: A Short Survey on Business Models of Decentralized Finance (DeFi) Protocols

### ISSUE THREAD

**Issue by encore9870** [smartcontractresearchforum/research_content#281]
Contributor: Tomide(@tomideadeoye)

Drafting Deadline: June 5, 2022

Link to the Paper: https://arxiv.org/pdf/2202.07742.pdf

Link to the Draft: https://docs.google.com/document/d/1pnwnYqMSw0y6o-g3uSQO2aR_RHn6EMfIQgTEN9Vevhs/

Source of Approval: RP54, Call for Summaries

**Comment by encore9870** [comment]
- [x]  Onboarding is either complete or waived.
- [x]  The ticket contains the following information.
   - [x]  Contributor
   - [x]  Drafting deadline
   - [x]  Link to the paper
   - [x]  Link to the draft
   - [x]  Source of approval
- [x]  The author does not already have another working document.

**Comment by encore9870** [comment]
@tomideadeoye you're good to go!

**Comment by encore9870** [comment]
- [x] All fields described in the Template for that content type have been filled out.

**Comment by ralphlombreglia** [comment]
Hi @tomideadeoye. I'm the Engagement person for this summary on the SCRF Forum. As a first step, I've pasted in our "Go to Market (GTM) questions at the bottom of your summary draft. Please answer these to the best of your ability. The question "Please list 4 questions that we can ask you to get conversation going." is particularly important to us, so give that some extra thought. Thanks! Looking forward to working with you.

**Comment by tomideadeoye** [comment]
Hello @ralphlombreglia . Glad to hear from you. I will revert shortly with the details.

**Comment by ralphlombreglia** [comment]
Hi @tomideadeoye. We're still waiting for your answers to our GtM questions, which we need for encouraging engagement with your summary after it's published. Please let me know if you're having problems with this process.

**Comment by osapeter** [comment]
@tomideadeoye kindly review and update the summary. I have included some suggestions and inquiries for your validation.

**Comment by tomideadeoye** [comment]
@osapeter & @ralphlombreglia have I addressed the requirements?
@https://docs.google.com/document/d/1pnwnYqMSw0y6o-g3uSQO2aR_RHn6EMfIQgTEN9Vevhs/edit#

**Comment by osapeter** [comment]
@tomideadeoye, thanks for the feedback.  Do confirm the inquiries as a follow-up remark. Thanks

**Comment by tomideadeoye** [comment]
> @tomideadeoye, thanks for the feedback. Do confirm the inquiries as a follow-up remark. Thanks

Hi @osapeter. Thank you. I made some further edits to reflect the last remark in the doc. I am unsure what the quoted text above requires that I do next.

**Comment by jring-o** [comment]
A few minor edits. Please run spellcheck before submitting. Good to go.

**Comment by encore9870** [comment]
https://www.smartcontractresearch.org/t/research-summary-a-short-survey-on-business-models-of-decentralized-finance-defi-protocols/1947
