### ISSUE TITLE
Research Summary: Design and analysis of a distributed ECDSA signing service

### ISSUE THREAD

**Issue by encore9870** [smartcontractresearchforum/research_content#283]
Contributor: Bill @flyinglimao 

Drafting Deadline: July 31, 2022

Link to the Paper: https://eprint.iacr.org/2022/506.pdf

Link to the Draft: https://docs.google.com/document/d/1rQ1jCBY4C-wEcyCfibxIjbw9CNcMoWI8sYt-1aHUZ9Y/

Source of Approval: RP 64

**Comment by encore9870** [comment]
- [x]  Onboarding is either complete or waived.
- [x]  The ticket contains the following information.
   - [x]  Contributor
   - [x]  Drafting deadline
   - [x]  Link to the paper
   - [x]  Link to the draft
   - [x]  Source of approval
- [x]  The author does not already have another working document.

**Comment by osapeter** [comment]
Hello @flyinglimao, I am from the content team, kindly review and update the summary. I have included some suggestions and inquiries for your validation. Thanks

**Comment by osapeter** [comment]
Hello @flyinglimao, kindly review and accept as resolved. Also, accent to the inquiries for your validation. Thanks

**Comment by encore9870** [comment]
I did [GTM](https://docs.google.com/document/d/1B47IXEM9O33QrtwMynvDgUCx8SihhBK5-0zwtaspZ9I/edit?usp=sharing) for this one. Should be able for next steps once @ttaloute finishes the edits

**Comment by encore9870** [comment]
Sould be good to go
