### ISSUE TITLE
Research Summary: A Cooperative Optimal Mining Model for Bitcoin

### ISSUE THREAD

**Issue by encore9870** [smartcontractresearchforum/research_content#284]
Contributor: Peter @osapeter

First Draft Turn In Date Estimation: June 7, 2022

Paper: https://arxiv.org/pdf/2107.09707.pdf

Draft: https://docs.google.com/document/d/1mBgN9MVQ0rYEXK-Y39139S7obbXXPii9CDHqyL8vwas/edit

Source of approval: RP 23

**Comment by encore9870** [comment]
- [x] Onboarding is either complete or waived.
- [x] The ticket contains the following information.
   - [x] Author
   - [x] An estimated date of completion
   - [x] Link to paper
   - [x] Link to the draft
   - [x] Source of approval
- [x] The author does not already have another working document.

**Comment by osapeter** [comment]
Kindly review and update the paper URL link

**Comment by osapeter** [comment]
Hello Twan,

I am submitting my first draft for review - same doc link

**Comment by encore9870** [comment]
- [x] All fields described in the Template for that content type have been filled out.

**Comment by osapeter** [comment]
Good day Twan,
The feedback has been incorporated into the summary. This is for your review action
Thanks

**Comment by encore9870** [comment]
https://www.smartcontractresearch.org/t/research-summary-a-cooperative-optimal-mining-model-for-bitcoin/2107?u=twan
