### ISSUE TITLE
Research Summary: Usability of Cryptocurrency Wallets Providing CoinJoin Transactions

### ISSUE THREAD

**Issue by RuthTolulope** [smartcontractresearchforum/research_content#285]
Contributor: Matthew (@Ulyssesmathew)

Drafting Deadline: June 24, 2022

Link to the Paper: https://eprint.iacr.org/2022/285.pdf

Link to the Draft: https://docs.google.com/document/d/1pvDT9AiZk6E8uQHMPAZiYfv7lZwUQVFKlbWAOqFUg-o/edit?usp=sharing

Source of Approval: RP 57, Call for summaries

**Comment by Ulyssesmathew** [comment]
Greetings Tolu.

I found that out that I don't access to the Google Docs link you shared in
the previous mail.

Please, kindly check. Thank you.

**Comment by RuthTolulope** [comment]
Hello Matthew,

Kindly hold on.

You’ll be notified about when you can start.

Thank you for your patience.

**Comment by Ulyssesmathew** [comment]
Noted. Thanks.

**Comment by encore9870** [comment]
- [x]  Onboarding is either complete or waived.
- [x]  The ticket contains the following information.
   - [x]  Contributor
   - [x]  Drafting deadline
   - [x]  Link to the paper
   - [x]  Link to the draft
   - [x]  Source of approval
- [x]  The author does not already have another working document.

**Comment by osapeter** [comment]
Hello @Ulyssesmathew I am from the content team, kindly review and update the summary. I have included some suggestions and inquiries for your validation. Thanks

**Comment by Ulyssesmathew** [comment]
Hi @osapeter,

Thank you for your corrections and insights.
I have made the changes and as requested.

Best regards,
Matthew

**Comment by osapeter** [comment]
Hello @Ulyssesmathew, thanks for the feedback. Kindly review the suggestions and contextual flow. Thanks

**Comment by Ulyssesmathew** [comment]
Thanks, I'll take a look.

**Comment by Ulyssesmathew** [comment]
Hi, @osapeter, I have adequately considered your suggestions and changes have been effected. Thank you.

**Comment by osapeter** [comment]
Hello @Ulyssesmathew, I have included a few suggestions for your validation. Thanks

**Comment by Ulyssesmathew** [comment]
@osapeter I have considered the suggestion. You can check to see.

**Comment by jring-o** [comment]
Some minor edits. Good to go.

**Comment by Ulyssesmathew** [comment]
Suggestion considered

Best regards, 
Matthew

**Comment by RuthTolulope** [comment]
[HackMD link](https://hackmd.io/@content/rJsj8Ines)

**Comment by encore9870** [comment]
https://www.smartcontractresearch.org/t/research-summary-usability-of-cryptocurrency-wallets-providing-coinjoin-transactions/2037/5

**Comment by Ulyssesmathew** [comment]
Thank you for your email, Tolu.

This means I can start?
