### ISSUE TITLE
Research Summary: Rectifying Administrated ERC20 Tokens

### ISSUE THREAD

**Issue by RuthTolulope** [smartcontractresearchforum/research_content#286]
Contributor: Peter (@osapeter)

Drafting Deadline: June 13, 2022

Link to the Paper: https://arxiv.org/pdf/2107.10979.pdf

Link to the Draft: [Rectifying Administrated ERC20 Tokens](https://docs.google.com/document/d/1oaWrcVwkLMF8AXwmeQuoxbP4R1wU6Z7D5agh3U2t4O4/edit?usp=sharing)

Source of Approval: RP 24, Call for Summaries

**Comment by osapeter** [comment]
Kindly update the Drafting Deadline 13th

**Comment by encore9870** [comment]
- [x] Onboarding is either complete or waived.
- [x]  The ticket contains the following information.
   - [x]  Contributor
   - [x]  Drafting deadline
   - [x]  Link to the paper
   - [x]  Link to the draft
   - [x]  Source of approval
- [x]  The author does not already have another working document.

**Comment by osapeter** [comment]
Hello,

I am submitting my first draft for review - same doc link

**Comment by encore9870** [comment]
I believe that has finished editing. Moving to the next stage to complete the final steps before publishing.

**Comment by content-scrf** [comment]
Hi @osapeter, here is the markdown version of your research summary https://hackmd.io/@content/SkTmxz7sc.
Kindly ensure that this is the ultimate version that is uploaded to the forum when publication is approved.
Let me know if you have any questions or need assistance.

**Comment by jamesmcgirk** [comment]
@osapeter hey there, I've been assigned to work on engagement for this piece. I'll be asking you some questions soon

**Comment by osapeter** [comment]
Thanks @jamesmcgirk I am glad to work with you

**Comment by jamesmcgirk** [comment]
@osapeter thanks so much! me too... I've added in a couple of questions for you to answer, and then we'll schedule some time for a Discord chat

**Comment by osapeter** [comment]
@jamesmcgirk I am not sure exactly where you put up the questions for my response.  Do advise and direct as necessary.  Thanks

**Comment by osapeter** [comment]
@jamesmcgirk I have gotten an update from @twan-dev

**Comment by jamesmcgirk** [comment]
@zubepaul gtm complete

**Comment by zubepaul** [comment]
@twan-dev  @osapeter @MichaelSCRF Engagement review completed. Can be published no sooner than July 19, 2022

**Comment by Fizzymidas** [comment]
Please, why is this closed? I can't find the publication on the forum.
