### ISSUE TITLE
Research Summary: Route Discovery in Private Payment Channel Networks

### ISSUE THREAD

**Issue by RuthTolulope** [smartcontractresearchforum/research_content#287]
Contributor: Peter (@osapeter)

Drafting Deadline: June 20, 2022

Link to the Paper: https://eprint.iacr.org/2021/1539.pdf

Link to the Draft: https://docs.google.com/document/d/1x3JoNsysde1487uvk8vUTbOm6lBgDagvOeG4Te7cNNA/edit?usp=sharing

Source of Approval: RP 41, Call for Summaries

**Comment by encore9870** [comment]
- [x]  Onboarding is either complete or waived.
- [x]  The ticket contains the following information.
   - [x]  Contributor
   - [x]  Drafting deadline
   - [x]  Link to the paper
   - [x]  Link to the draft
   - [x]  Source of approval
- [x]  The author does not already have another working document.

**Comment by osapeter** [comment]
Kindly review the initial draft summary. Thanks

**Comment by jamesmcgirk** [comment]
@osapeter this one is in good shape, I flagged a few places that need some work and be sure to paraphrase rather than c/p

**Comment by osapeter** [comment]
@jamesmcgirk many thanks for the feedback. I have done the required updates. Do take another look for content and flow. Thanks

**Comment by encore9870** [comment]
https://www.smartcontractresearch.org/t/research-summary-route-discovery-in-private-payment-channel-networks/2098?u=twan
