### ISSUE TITLE
Research Summary: ÐArcher: Detecting On-Chain-Off-Chain Synchronization Bugs in Decentralized Applications

### ISSUE THREAD

**Issue by RuthTolulope** [smartcontractresearchforum/research_content#290]
Contributor: David (@cashkid1994)

Drafting Deadline: June 16, 2022

Link to the Paper: https://arxiv.org/pdf/2106.09440.pdf

Link to the Draft: https://docs.google.com/document/d/1JgBLL6VzdANAizEWirDCZjtU_TyDr6HDjo3r2Oo1maw/edit?usp=sharing

Source of Approval: RP 31, Call for Summaries

**Comment by encore9870** [comment]
- [x] Onboarding

**Comment by cashkid1994** [comment]
The draft have been submitted

**Comment by cashkid1994** [comment]
Hello,
Any update on this?
    On Monday, June 20, 2022, 10:35:18 AM GMT+1, twan-dev ***@***.***> wrote:  
 
 

   
   -  Onboarding

**Comment by encore9870** [comment]
- [x] All fields described in the Template for that content type have been filled out.

**Comment by encore9870** [comment]
@cashkid1994 Need you to go over the comments!

**Comment by cashkid1994** [comment]
Dear Twan,
This draft have been worked on as requested 
    On Wednesday, July 13, 2022 at 01:33:35 PM GMT+1, twan-dev ***@***.***> wrote:  
 
 


@cashkid1994 Need you to go over the comments!

**Comment by encore9870** [comment]
Gotcha we'll get to it soon. In the meantime, I see that there are still open edit suggestions. Please go through them (accept the edits, or communicate) so they can be resolved soon!

**Comment by cashkid1994** [comment]
Dear twan,
Kindly check again
    On Friday, July 15, 2022 at 01:28:24 PM GMT+1, twan-dev ***@***.***> wrote:  
 
 


Gotcha we'll get to it soon. In the meantime, I see that there are still open edit suggestions. Please go through them (accept the edits, or communicate) so they can be resolved soon!

**Comment by osapeter** [comment]
Hello @cashkid1994, I have included some suggestions and inquiries for your validation. Thanks

**Comment by cashkid1994** [comment]
This is noted
    On Friday, July 22, 2022 at 08:55:53 AM GMT+1, osapeter ***@***.***> wrote:  
 
 


Hello @cashkid1994, I have included some suggestions and inquiries for your validation. Thanks

**Comment by cashkid1994** [comment]
Hello Peter,
This have been taken care of as requested 
    On Friday, July 22, 2022 at 02:23:45 PM GMT+1, Chiebonam Onah ***@***.***> wrote:  
 
  This is noted
    On Friday, July 22, 2022 at 08:55:53 AM GMT+1, osapeter ***@***.***> wrote:  
 
 


Hello @cashkid1994, I have included some suggestions and inquiries for your validation. Thanks

**Comment by osapeter** [comment]
Hello @cashkid1994, many thanks for the feedback.  I have included some suggestions for necessary affirmation. Thanks

**Comment by cashkid1994** [comment]
Dear osapeter,
This have been taken care of.
    On Friday, July 29, 2022 at 09:27:48 AM GMT+1, osapeter ***@***.***> wrote:  
 
 


Hello @cashkid1994, many thanks for the feedback. I have included some suggestions for necessary affirmation. Thanks

**Comment by encore9870** [comment]
https://www.smartcontractresearch.org/t/research-summary-darcher-detecting-on-chain-off-chain-synchronization-bugs-in-decentralized-applications/1974

**Comment by Fizzymidas** [comment]
@twan-dev met this too: "Oops! That page doesn’t exist or is private."
