### ISSUE TITLE
Research Summary: Investigating Arbitrageurs and Oracle Manipulators in Ethereum

### ISSUE THREAD

**Issue by RuthTolulope** [smartcontractresearchforum/research_content#292]
Contributor: Tomide (@tomideadeoye)

Drafting Deadline: July 31, 2022

Link to the Paper: https://repository.tudelft.nl/islandora/object/uuid:06ddf1dd-7dba-495b-b7f3-31b8d2bb966c

Link to the Draft: https://docs.google.com/document/d/1rM7EqUkjmW_LsuSG-dqrQ__2DZtNIofgwdeYUGz2UUQ/edit?usp=sharing

Source of Approval: RP 20, Call for Summaries

**Comment by twan-dev** [comment]
- [x] Onboarding
- [x] Contributor does not already have another draft on their plate

**Comment by encore9870** [comment]
- [x] Onboarding
- [x] Contributor does not already have another draft on their plate

**Comment by RuthTolulope** [comment]
Contributor requested an extension. 
Next check-in date: August 12, 2022

**Comment by tomideadeoye** [comment]
> Contributor requested an extension. Next check-in date: August 12, 2022

Thanks @RuthTolulope 

I look forward to the review.

**Comment by tomideadeoye** [comment]
@RuthTolulope 👀

**Comment by osapeter** [comment]
Hello @tomideadeoye, nice work.  I have included a few suggestions and inquiries for your validation. Thanks

**Comment by encore9870** [comment]
https://www.smartcontractresearch.org/t/research-summary-investigating-arbitrageurs-and-oracle-manipulators-in-ethereum/2105?u=twan
