### ISSUE TITLE
Research Summary: Disentangling Decentralized Finance (DeFi) Compositions

### ISSUE THREAD

**Issue by RuthTolulope** [smartcontractresearchforum/research_content#293]
Contributor: Peter (@osapeter)

Drafting Deadline: June 27, 2022

Link to the Paper: https://www.depositonce.tu-berlin.de/bitstream/11303/13867/4/Kitzler_etal_Disentangling_2021_Cover.pdf

Link to the Draft: https://docs.google.com/document/d/19KuBNkM1wFT4aqEYRQRVcMgjIiug_Te4Z4alzCIz7RY/edit?usp=sharing

Source of Approval: RP 40, Call for Summaries

**Comment by encore9870** [comment]
- [x] Onboarding
- [x] Contributor does not have another draft in the drafting or editing stages

**Comment by osapeter** [comment]
I am done with the first draft

**Comment by osapeter** [comment]
Updates effected

**Comment by jamesmcgirk** [comment]
@osapeter I made some edits -- take a close look at the summary, methodology and results section and make sure each section is readable. I made a few suggestions throughout but you should take some time to go through and make sure that you're articulating what's going on in these sections. Implications, Follow-ups and Application sections are in good shape. I'll take another look when you're done editing. - J

**Comment by osapeter** [comment]
@jamesmcgirk many thanks for your review and suggestion.  I have gone through and updated it.  Do take another look for content and flow.  Thanks

**Comment by encore9870** [comment]
https://www.smartcontractresearch.org/t/research-summary-disentangling-decentralized-finance-defi-compositions/2106?u=twan
