### ISSUE TITLE
Research Summary: Do the Rich get Richer ? Fairness Analysis for Blockchain Incentives 

### ISSUE THREAD

**Issue by RuthTolulope** [smartcontractresearchforum/research_content#294]
Contributor: David (@cashkid1994)

Drafting Deadline: June 22, 2022

Link to the Paper: https://arxiv.org/pdf/2103.14713.pdf

Link to the Draft: https://docs.google.com/document/d/14D3ck9hsBdhLaXYTaSVlvBDd8Ui2hxgbfAMzVqiBHJo/edit?usp=sharing

Source of Approval: RP 6, Call for Summaries

**Comment by encore9870** [comment]
- [x] Onboarding
- [x] Contributor does not have another draft in the drafting or editing stages

**Comment by cashkid1994** [comment]
This research have been drafted and submitted

**Comment by cashkid1994** [comment]
This research summary have been edited as requested

**Comment by cashkid1994** [comment]
Hello,
Any update on this ?

    On Wednesday, June 22, 2022, 03:54:14 PM GMT+1, twan-dev ***@***.***> wrote:  
 
 

   
   -  Onboarding
   -  Contributor does not have another draft in the drafting or editing stages

**Comment by encore9870** [comment]
- [x] All fields described in the Template for that content type have been filled out.

**Comment by encore9870** [comment]
@cashkid1994 Need you to go over the comments!

**Comment by cashkid1994** [comment]
Dear Twan,
This draft have been worked on as requested 
    On Wednesday, July 13, 2022 at 01:33:42 PM GMT+1, twan-dev ***@***.***> wrote:  
 
 


@cashkid1994 Need you to go over the comments!

**Comment by cashkid1994** [comment]
Kindly ignore the last message.
It wasn't for this paper
    On Friday, July 15, 2022 at 01:15:09 PM GMT+1, Chiebonam Onah ***@***.***> wrote:  
 
  Dear Twan,
This draft have been worked on as requested 
    On Wednesday, July 13, 2022 at 01:33:42 PM GMT+1, twan-dev ***@***.***> wrote:  
 
 


@cashkid1994 Need you to go over the comments!

**Comment by cashkid1994** [comment]
Dear Twan,
This have been worked on as requested 
    On Wednesday, July 13, 2022 at 01:33:42 PM GMT+1, twan-dev ***@***.***> wrote:  
 
 


@cashkid1994 Need you to go over the comments!

**Comment by osapeter** [comment]
Hello @cashkid1994, I have included some suggestions and inquiries for your validation. Thanks

**Comment by cashkid1994** [comment]
This is noted
    On Friday, July 22, 2022 at 08:42:00 AM GMT+1, osapeter ***@***.***> wrote:  
 
 


Hello @cashkid1994, I have included some suggestions and inquiries for your validation. Thanks

**Comment by cashkid1994** [comment]
Hello Peter,
This have been taken care of as requested 
    On Friday, July 22, 2022 at 02:12:51 PM GMT+1, Chiebonam Onah ***@***.***> wrote:  
 
  This is noted
    On Friday, July 22, 2022 at 08:42:00 AM GMT+1, osapeter ***@***.***> wrote:  
 
 


Hello @cashkid1994, I have included some suggestions and inquiries for your validation. Thanks

**Comment by jring-o** [comment]
This requires significant work. I am also concerned about plagiarism from the article itself (unless the summary is written by the primary author of the research).

I would want to review this again after changes are made. Generally speaking, after reading this summary I still don't know what the research determined.

**Comment by encore9870** [comment]
Let's move this ticket to drafting until the contributor addresses the edits you've left. Thanks for flagging!

**Comment by cashkid1994** [comment]
Noted
    On Thursday, August 11, 2022 at 02:14:26 PM GMT+1, jring-o ***@***.***> wrote:  
 
 


This requires significant work. I am also concerned about plagiarism from the article itself (unless the summary is written by the primary author of the research).

I would want to review this again after changes are made. Generally speaking, after reading this summary I still don't know what the research determined.

**Comment by cashkid1994** [comment]
This have been taken care of
    On Thursday, August 11, 2022 at 02:14:26 PM GMT+1, jring-o ***@***.***> wrote:  
 
 


This requires significant work. I am also concerned about plagiarism from the article itself (unless the summary is written by the primary author of the research).

I would want to review this again after changes are made. Generally speaking, after reading this summary I still don't know what the research determined.

**Comment by osapeter** [comment]
Hello @cashkid1994, we have made a couple of suggestions and comments for your necessary action. Thanks

**Comment by cashkid1994** [comment]
Hello Peter,
This have been taken care of

    On Wednesday, September 7, 2022 at 02:01:44 PM GMT+1, osapeter ***@***.***> wrote:  
 
 


Hello @cashkid1994, we have made a couple of suggestions and comments for your necessary action. Thanks

**Comment by encore9870** [comment]
https://www.smartcontractresearch.org/t/research-summary-do-the-rich-get-richer-fairness-analysis-for-blockchain-incentives/2113
