### ISSUE TITLE
Research Summary: Ethereum Data Structures

### ISSUE THREAD

**Issue by RuthTolulope** [smartcontractresearchforum/research_content#295]
Contributor: Dimitar (@stayhungry07212)

Drafting Deadline: July 11, 2022

Link to the Paper: https://arxiv.org/pdf/2108.05513.pdf

Link to the Draft: https://docs.google.com/document/d/1vNaBVbCzR4RSEFsx9WeEu9NjnrgTpVFXGeZ-6wtRJMU/edit?usp=sharing

Source of Approval: RP 27, Call for Summaries

**Comment by encore9870** [comment]
- [x] Onboarding
- [x] Contributor does not have another draft in drafting or editing stages

**Comment by encore9870** [comment]
Looks good. Moving to content review

**Comment by osapeter** [comment]
Hello @stayhungry07212, I am from the content team, I have included some suggestions and inquiries for your validation. Thanks

**Comment by stayhungry07212** [comment]
@osapeter, I just fixed the contents and replied some. Can you please suggest more meaningful details for some content?
Thanks.

**Comment by jring-o** [comment]
Outstanding summary. One typo. Good to go.

**Comment by stayhungry07212** [comment]
@jring-o, I just fixed the typo, thanks, what's the next step?

**Comment by encore9870** [comment]
https://www.smartcontractresearch.org/t/research-summary-ethereum-data-structures/1973
