### ISSUE TITLE
Research Summary: SCSGuard: Deep Scam Detection for Ethereum Smart Contracts

### ISSUE THREAD

**Issue by RuthTolulope** [smartcontractresearchforum/research_content#296]
Contributor: David (@cashkid1994)

Drafting Deadline: July 31, 2022

Link to the Paper: https://arxiv.org/pdf/2105.10426.pdf     

Link to the Draft: https://docs.google.com/document/d/1_DF-d-8rT1H3TvGCFXipyHQIcjjgl-qP3MTLucXEZiU/edit?usp=sharing

Source of Approval: RP 23, Call for summaries

**Comment by Ulyssesmathew** [comment]
@twan-dev Any news on this?

**Comment by twan-dev** [comment]
We've told you, you need to finish the other drafts in the content pipeline before starting a new one

**Comment by encore9870** [comment]
> @twan-dev Any news on this?

sorry, I confused you with another contributor that also wanted to summarize this work.

**Comment by Ulyssesmathew** [comment]
Alright. No Problem.

**Comment by encore9870** [comment]
- [x] Onboarding
- [x] Contributor does not have competing priorities in the content pipeline

**Comment by osapeter** [comment]
Hello, I am from the content team, I have included some suggestions and inquiries for your validation. Thanks

**Comment by jring-o** [comment]
A few minor edits. Good to go.

**Comment by cashkid1994** [comment]
The work have been edited as requested.
    On Thursday, August 11, 2022 at 02:36:51 PM GMT+1, jring-o ***@***.***> wrote:  
 
 


A few minor edits. Good to go.

**Comment by cashkid1994** [comment]
Any update on this one ??
    On Sunday, July 24, 2022 at 08:51:52 PM GMT+1, Chiebonam Onah ***@***.***> wrote:  
 
  Hello Peter,
This have been taken care of as requested 

    On Friday, July 22, 2022 at 07:01:11 AM GMT+1, Chiebonam Onah ***@***.***> wrote:  
 
  Dear peter,
This is noted
    On Friday, July 22, 2022 at 02:58:05 AM GMT+1, osapeter ***@***.***> wrote:  
 
 


Hello, I am from the content team, I have included some suggestions and inquiries for your validation. Thanks

**Comment by cashkid1994** [comment]
This summary have been worked on as requested.

**Comment by encore9870** [comment]
https://www.smartcontractresearch.org/t/research-summary-scsguard-deep-scam-detection-for-ethereum-smart-contracts/1941

**Comment by cashkid1994** [comment]
Hello Peter,
This have been taken care of as requested 

    On Friday, July 22, 2022 at 07:01:11 AM GMT+1, Chiebonam Onah ***@***.***> wrote:  
 
  Dear peter,
This is noted
    On Friday, July 22, 2022 at 02:58:05 AM GMT+1, osapeter ***@***.***> wrote:  
 
 


Hello, I am from the content team, I have included some suggestions and inquiries for your validation. Thanks

**Comment by cashkid1994** [comment]
Dear peter,
This is noted
    On Friday, July 22, 2022 at 02:58:05 AM GMT+1, osapeter ***@***.***> wrote:  
 
 


Hello, I am from the content team, I have included some suggestions and inquiries for your validation. Thanks
