### ISSUE TITLE
Research Summary: Mitigating Game Theoretic vulnerabilities in Chainlink

### ISSUE THREAD

**Issue by content-scrf** [smartcontractresearchforum/research_content#299]
Contributor: Samuel (@samuelngwu)

Drafting Deadline: July 20, 2022

Link to the Paper: https://repository.tudelft.nl/islandora/object/uuid:b9a62989-f7b3-4334-af27-c4cde929d7df

Link to the Draft: https://docs.google.com/document/d/1i0iAxg3GgNny2C6oGQmMh6MjUvSFwgYljrZCeX3IUXQ/edit?usp=sharing

Source of Approval: RP 20, Call for Summaries

**Comment by samuelngwu** [comment]
Thank you for the approval.

The drafting dare should be 20th July not June since we are already in July.


Best regards
Samuel Ngwu

**Comment by encore9870** [comment]
- [x] Onboarding
- [x] The contributor does not have competing priorities in the content pipeline

**Comment by samuelngwu** [comment]
Thank you for the clarification, Twan.

**Comment by osapeter** [comment]
Hello @samuelngwu, I am from the content team, kindly review and update the summary. I have included some suggestions and inquiries for your validation. Thanks

**Comment by osapeter** [comment]
Hello @samuelngwu, I have included some suggestions and inquiries for your validation. Thanks

**Comment by osapeter** [comment]
Hello @samuelngwu, just a few suggestions for your action. Thanks

**Comment by samuelngwu** [comment]
Hello Peter,

Thanks for the feedback.
I will effect the corrections.

Regards

**Comment by samuelngwu** [comment]
Hello Peter,

I trust work is coming fine.

This corrections has been effected for your attention.

Thank you
Samuel

**Comment by osapeter** [comment]
Hello @samuelngwu, I observed and included just a few suggestions for your action. Also, review the context flow of the results. Thanks

**Comment by samuelngwu** [comment]
Hello Peter,

This corrections has been effected. However, I dropped comment under result
for your attention.

Thank you

**Comment by osapeter** [comment]
Hello @samuelngwu, thanks for the feedback.  Do review the commented item in result section (focus on the outcome).  Also, review the general context flow as earlier suggested.  Thanks

**Comment by encore9870** [comment]
https://www.smartcontractresearch.org/t/research-summary-mitigating-game-theoretic-vulnerabilities-in-chainlink/2097

**Comment by samuelngwu** [comment]
Thanks, I'll take a look, dear Peter.
