### ISSUE TITLE
Generate Research Summary for Tim Roughgarden's assessment of  EIP-1559

### ISSUE THREAD

**Issue by ericjaurena** [smartcontractresearchforum/research_content#3]
https://docs.google.com/document/d/1Soia7Da8jcsxfz9n1B_KjeBI8OBuLOM8m2agvqHstG8/edit#heading=h.vebeviabrepg

http://timroughgarden.org/papers/eip1559.pdf

**Comment by ghettodev** [comment]
@cipherix can we get a link to the draft doc?

**Comment by ericjaurena** [comment]
@cipherix and @visavishesh indicate this is ready for an editorial review. @bgits offered to do another content review. Assigned @bgits and @jamesmcgirk for these reviews.
