### ISSUE TITLE
Understanding Ethereum via Graph Analysis - Tina

### ISSUE THREAD

**Issue by ericjaurena** [smartcontractresearchforum/research_content#30]
[Summary](https://docs.google.com/document/d/1bULyetoNwZzsujUV4LFYKzO3gA7P251_p3HLN8DogZE/edit)

**Comment by ericjaurena** [comment]
Summary [published to SCRF](https://www.smartcontractresearch.org/t/research-summary-understand-ethereum-via-graph-analysis/168)

**Comment by zubepaul** [comment]
Engagement priority changed to 4
