### ISSUE TITLE
Research Summary: Mitigating Sandwich Attacks in Kyber DMM

### ISSUE THREAD

**Issue by content-scrf** [smartcontractresearchforum/research_content#300]
Contributor: Matthew (@Ulyssesmathew)

Drafting Deadline: July 24, 2022

Link to the Paper: https://repository.tudelft.nl/islandora/object/uuid:58ac3b00-10fb-44cd-b1eb-1e1139c39fd7/datastream/OBJ/download

Link to the Draft: https://docs.google.com/document/d/1aYjU7rJfGbvJBU1pr2tXqXnHTHA1avqE97ZlYG1n_eI/edit?usp=sharing

Source of Approval: RP 20, Call for Summaries

**Comment by encore9870** [comment]
- [x] Onboarding
- [x] Contributor does not have competing priorities in the pipeline

**Comment by encore9870** [comment]
- [x] all sections have been filled out

**Comment by osapeter** [comment]
Hello @Ulyssesmathew, I have included a few suggestions and inquiries for your validation. Thanks

**Comment by Ulyssesmathew** [comment]
Hi @osapeter, all suggestions have been considered. Thanks for your feedback.

**Comment by osapeter** [comment]
Hello @Ulyssesmathew, appreciate your feedback. Just a couple of suggestions and inquiries for your validation. Thanks

**Comment by Ulyssesmathew** [comment]
@osapeter Considered, thanks

**Comment by jring-o** [comment]
A few typos. Good to go.

**Comment by Ulyssesmathew** [comment]
Changes made, thanks.

**Comment by RuthTolulope** [comment]
[HackMD link](https://hackmd.io/@content/ryXMFZkWj)

**Comment by encore9870** [comment]
https://www.smartcontractresearch.org/t/research-summary-mitigating-sandwich-attacks-in-kyber-dmm/2058
