### ISSUE TITLE
Research Summary: Attacks on Smart Contracts

### ISSUE THREAD

**Issue by content-scrf** [smartcontractresearchforum/research_content#301]
Engaging with the researchers of https://helda.helsinki.fi/bitstream/handle/10138/345427/20220607_Porkka_Pro_Gradu_FINAL.pdf?sequence=2

Expecting to get them around by EOM

**Comment by encore9870** [comment]
waiting for contract but secured first draft

**Comment by encore9870** [comment]
contract ok. draft editing in progress. should be publishing August 1-2, 2022
