### ISSUE TITLE
Research Summary:  An Empirical Study of DeFi Liquidations: Incentives, Risks, and Instabilities

### ISSUE THREAD

**Issue by content-scrf** [smartcontractresearchforum/research_content#302]
Contributor: Jacob (@jacob-thrackle)

Drafting Deadline: August 5, 2022

Link to the Paper: https://arxiv.org/pdf/2106.06389.pdf

Link to the Draft: https://docs.google.com/document/d/1TwLd6FlpI3nNwASRkEswcfsmzE-jzIySqhz277vm3yU/edit?usp=sharing

Source of Approval: RP 19, Call for Summaries

**Comment by content-scrf** [comment]
- [x] Onboarding
- [x] Contributor does not have another draft in the drafting or editing stages

**Comment by jacob-thrackle** [comment]
Draft is completed. Please advise on next steps.

**Comment by osapeter** [comment]
Hello @jacob-thrackle, I am from the content team, kindly review and update the summary. I have included some suggestions and inquiries for your validation. Thanks

**Comment by jacob-thrackle** [comment]
Completed. Please advise if more edits are required.

**Comment by osapeter** [comment]
@jacob-thrackle, many thanks for the prompt feedback.  I observed that you are yet to mark as resolved some of the suggestions.  This will make the summary cleaner for further analysis.  Do affirm and seek clarifications so we can have a good understanding otherwise. Thanks

**Comment by jring-o** [comment]
A few suggestions and edits. Otherwise good to go.

**Comment by encore9870** [comment]
https://www.smartcontractresearch.org/t/research-summary-an-empirical-study-of-defi-liquidations-incentives-risks-and-instabilities/1952
