### ISSUE TITLE
Research Summary: SuperDetector: A Framework for Performance Detection on Vulnerabilities of Smart Contracts

### ISSUE THREAD

**Issue by content-scrf** [smartcontractresearchforum/research_content#303]
Contributor: Harvesto (@HarvestoOrlando)
Checking with Progress on: July 15, 2022
Link to Paper: https://iopscience.iop.org/article/10.1088/1742-6596/2289/1/012010/pdf
Link to Draft: https://docs.google.com/document/d/1P-qYiXL-gojNAmBDSRJt5N324Ehy_HHyTeoP0nSTjO4/edit

**Comment by content-scrf** [comment]
- [x] Onboarding
- [x] Contributor does not have competing priorities in the content pipeline

**Comment by osapeter** [comment]
Hello @HarvestoOrlando, I am from the content team, I have included some suggestions and inquiries for your validation. Thanks

**Comment by HarvestoOrlando** [comment]
Hi @osapeter, I have responded to your comments and suggestions on the summary.

**Comment by osapeter** [comment]
Hello @HarvestoOrlando, thanks for the feedback update. I have also included some suggestions and inquiries for your validation. Thanks

**Comment by HarvestoOrlando** [comment]
Thanks @osapeter. I have gone through the suggestions, edits and responded. Let me know if there's anything else.

**Comment by jring-o** [comment]
Intro is rough, but the rest is great. A few edits then good to go.

**Comment by HarvestoOrlando** [comment]
> Intro is rough, but the rest is great. A few edits then good to go.

I'm done with the suggestions and edits.

**Comment by encore9870** [comment]
https://www.smartcontractresearch.org/t/research-summary-superdetector-a-framework-for-performance-detection-on-vulnerabilities-of-smart-contracts/1945

**Comment by Fizzymidas** [comment]
@twan-dev  I tried to visit the link above and got this: "Oops! That page doesn’t exist or is private."
