### ISSUE TITLE
Research Summary: Resurrecting Address Clustering in Bitcoin

### ISSUE THREAD

**Issue by content-scrf** [smartcontractresearchforum/research_content#304]
Contributor: Idara (@idybest)

Drafting Deadline: July 20, 2022

Link to the Paper: https://arxiv.org/pdf/2107.05749.pdf

Link to the Draft: https://docs.google.com/document/d/1-zeaa91cgP31EhY3u1dmFUST9lhX0UXSFlQpFAY8kxM/edit?usp=sharing

Source of Approval: RP 22, Call for Summaries

**Comment by content-scrf** [comment]
- [x] Onboarding

- [x] Contributor does not have another draft in the drafting or editing stages

**Comment by Idybest** [comment]
Done with drafting.

**Comment by osapeter** [comment]
Hello @Idybest, I am from the content team, kindly review and update the summary. I have included some suggestions, couple of comments and inquiries for your validation. Thanks

**Comment by Idybest** [comment]
Hello @osapeter, I appreciate your review. I have finished revising the summary and added the fixes and comments you requested. Please let me know what comes next. Thanks.

**Comment by osapeter** [comment]
Hello @Idybest, your feedback is appreciated.  However, there are some related contextual issues requiring fixing as well as a couple of comments and inquiries for your validation. Thanks

**Comment by Idybest** [comment]
Thank you for the feedback @osapeter 

I would work on fixing them as soon as possible.

**Comment by Idybest** [comment]
Hello @osapeter 

I hope this finds you well.

I wanted to let you know that I had finished responding to the remarks and suggestions about my research summary. Thanks.

**Comment by encore9870** [comment]
https://www.smartcontractresearch.org/t/research-summary-resurrecting-address-clustering-in-bitcoin/2196
