### ISSUE TITLE
Discussion Post: Cryptoeconomics as a Limitation on Governance

### ISSUE THREAD

**Issue by content-scrf** [smartcontractresearchforum/research_content#305]
Contributor: David Wither (@davidwither)

Drafting Deadline: August 20, 2022

Link to the Paper: https://osf.io/wzf85?view_only=a10581ae9a804aa197ac39ebbba05766

Link to the Draft: https://docs.google.com/document/d/13FD1_QTpl5XiV-MnyCGPoIFGUSX3dWW7mYxYRBCKfj4/edit?usp=sharing

Source of Approval: RP 55

**Comment by RuthTolulope** [comment]
Contributor requested an extension.
Next check-in date: August 27, 2022

**Comment by davidwither** [comment]
Draft complete, ready for review.

**Comment by osapeter** [comment]
Hello @davidwither, I am from the content team, we appreciate the amazing work on this post. However, I have included a few suggestions for your validation. Thanks

**Comment by davidwither** [comment]
Hi @osapeter, thank you for your comments and time. I've validated most of the changes, but have left two minor comment responses in the text. 

Can I also just double check if you want me to switch from UK English to US English in general for work at SCRF?

**Comment by RuthTolulope** [comment]
Hi @davidwither yes, you may use US English.

**Comment by osapeter** [comment]
Hello @davidwither, many thanks for the feedback.  Pretty sure the preferred US English format has been adopted.  It will be passed to the next stage for necessary action.  Thanks

**Comment by encore9870** [comment]
https://www.smartcontractresearch.org/t/discussion-post-cryptoeconomics-as-a-limitation-on-governance/2115
