### ISSUE TITLE
Research Summary: User perceived privacy in Blockchain

### ISSUE THREAD

**Issue by encore9870** [smartcontractresearchforum/research_content#306]
A summary by the researchers: https://eprint.iacr.org/2022/287.pdf

Draft in SCRF's drive:
(Removed)

**Comment by jamesmcgirk** [comment]
@twan-dev I made a few very minor suggestions. Ready for engagement / publication

**Comment by encore9870** [comment]
@jamesmcgirk Thank you so much!!

**Comment by encore9870** [comment]
calendaring for August (week TBD)

**Comment by encore9870** [comment]
Post Created at https://www.smartcontractresearch.org/t/research-summary-user-perceived-privacy-in-blockchain/1917

We will be publishing it ~ a month after 
- #260 

goes live
