### ISSUE TITLE
Research Summary: Studying Bitcoin privacy attacks and their Impact on Bitcoin-based Identity Methods

### ISSUE THREAD

**Issue by encore9870** [smartcontractresearchforum/research_content#307]
A summary by the researchers
https://link.springer.com/chapter/10.1007/978-3-030-85867-4_7

Draft in SCRf's drive:
(Removed)

**Comment by encore9870** [comment]
prioritize this draft (let this post go first, post a week apart) before #306

**Comment by jamesmcgirk** [comment]
@twan-dev made some edits to this one, it's in good shape should be ready for engagement and publishing

**Comment by encore9870** [comment]
@jamesmcgirk Thank you so much!!

**Comment by encore9870** [comment]
Published on July 20, 2022. 
https://www.smartcontractresearch.org/t/research-summary-studying-bitcoin-privacy-attacks-and-their-impact-on-bitcoin-based-identity-methods/1790
