### ISSUE TITLE
Research Summary: Penny Wise and Pound Foolish: Quantifying the Risk of Unlimited Approval of ERC20 Tokens on Ethereum

### ISSUE THREAD

**Issue by encore9870** [smartcontractresearchforum/research_content#309]
A summary by the researchers. We're expecting their draft by Monday.

**Comment by encore9870** [comment]
Draft around. Needs edits.

**Comment by jamesmcgirk** [comment]
Edits done -- looks good content wise, I made some grammatical suggestions throughout and had a suggestion for the TLDR. Happy to take a second look cc @twan-dev

**Comment by encore9870** [comment]
Published July 21, 2022 https://www.smartcontractresearch.org/t/research-summary-penny-wise-and-pound-foolish-quantifying-the-risk-of-unlimited-approval-of-erc20-tokens-on-ethereum/1795
