### ISSUE TITLE
Use Cases: eThor

### ISSUE THREAD

**Issue by jamesmcgirk** [smartcontractresearchforum/research_content#31]
https://docs.google.com/document/d/1I1m6L_6RSi3aSIcmN7EMOvByVUWXHEqnoXnnWu65XKk/edit?usp=sharing

**Comment by jamesmcgirk** [comment]
https://docs.google.com/document/d/1I1m6L_6RSi3aSIcmN7EMOvByVUWXHEqnoXnnWu65XKk/edit - transcript with timecode, will create Use Cases on this doc.

**Comment by ghettodev** [comment]
We're running through some process stuff. Moving this ticket back to the idea column until the project plan has been ratified. Please see https://github.com/smartcontractresearchforum/research_team/issues/18

**Comment by jamesmcgirk** [comment]
Sounds good. I'll get started on a project plan.

**Comment by jamesmcgirk** [comment]
Project Plan is done, meeting assigned. Going to move this to Idea Stage. @visavishesh

**Comment by jamesmcgirk** [comment]
https://docs.google.com/document/d/1K36GVBZkNazv7HuCBQ28fzxDpe5EZ4_7xeJ7mFCdVbw/edit

Added some questions generated from a discussion by Leo and Larry. Waiting for Trents $0.02 then will reach out to Clara for answers

**Comment by jamesmcgirk** [comment]
Will present questions to @ClaraS and flag for content review once she's had a chance to review.

**Comment by jamesmcgirk** [comment]
Reached out to @ClaraS awaiting her decision on which questions to respond to...

**Comment by jamesmcgirk** [comment]
Since this is really an engagement experiment, I'm going to execute it.
