### ISSUE TITLE
Research Summary: FlashSyn: Flash Loan Attack Synthesis via Counter Example Driven Approximation

### ISSUE THREAD

**Issue by encore9870** [smartcontractresearchforum/research_content#310]
https://arxiv.org/abs/2206.10708

**Comment by encore9870** [comment]
contract and draft received

**Comment by encore9870** [comment]
We've editing and sent back yesterday. Looking to publish August 1-2, 2022

**Comment by jamesmcgirk** [comment]
@jring-o where's the doc? Twan wants me to add some suggested readings
