### ISSUE TITLE
Research Summary: zPROBE: Zero Peek Robustness Checks for Federated Learning

### ISSUE THREAD

**Issue by encore9870** [smartcontractresearchforum/research_content#321]
Paper: 
https://arxiv.org/abs/2206.12100
Draft:
https://docs.google.com/document/d/1g-9oHNamqXT7WMNyfLliI1-s3-v-7-k4z9CEZ_kYMEg/edit?usp=sharing

**Comment by jring-o** [comment]
A few typos. Good to go.

**Comment by encore9870** [comment]
https://www.smartcontractresearch.org/t/research-summary-zprobe-zero-peek-robustness-checks-for-federated-learning/1981?u=twan
