### ISSUE TITLE
Research Summary: NFT Wash Trading: Quantifying suspicious behavior in NFT markets

### ISSUE THREAD

**Issue by encore9870** [smartcontractresearchforum/research_content#325]
Contract signed in late May. Summary to be delivered "within the next days"

**Comment by encore9870** [comment]
Draft is finally here! https://docs.google.com/document/d/1lsM1ntSxk-671b4YAmx1-xBzeU84f_08nNVEb_ILNSk/edit?usp=sharing

**Comment by jring-o** [comment]
Several typos. Good to go.

**Comment by encore9870** [comment]
https://www.smartcontractresearch.org/t/research-summary-nft-wash-trading-quantifying-suspicious-behaviour-in-nft-markets/1982
