### ISSUE TITLE
Research Summary: Secure and Privacy-Aware Blockchain Design: Requirements, Challenges and Solutions

### ISSUE THREAD

**Issue by content-scrf** [smartcontractresearchforum/research_content#326]
Contributor: Tolu (@RuthTolulope)

Drafting Deadline: August 31, 2022

Link to the Paper: https://www.mdpi.com/2624-800X/1/1/9/htm

Link to the Draft: https://docs.google.com/document/d/1mRfbiqb4ISZZ1rgVdZjAw-1d2BsZ_jWODdJ3tw9YF7I/edit?usp=sharing

Source of Approval: RP 5

**Comment by content-scrf** [comment]
- [x] Onboarding
- [x] Contributor does not have another draft in the drafting or editing stages

**Comment by RuthTolulope** [comment]
New check-in date: 09/26/2022

**Comment by RuthTolulope** [comment]
Draft completed

**Comment by encore9870** [comment]
https://www.smartcontractresearch.org/t/research-summary-secure-and-privacy-aware-blockchain-design-requirements-challenges-and-solutions/2260
