### ISSUE TITLE
Research Summary: A ZK-SNARK based Proof of Assets Protocol for Bitcoin Exchanges

### ISSUE THREAD

**Issue by encore9870** [smartcontractresearchforum/research_content#337]
https://docs.google.com/document/d/1P0eEjfVJRVA9_Izi26R3Q763OhKp3ZkQz7N1bKPzzBM/edit

**Comment by encore9870** [comment]
contract received and draft claimed to have been finished

**Comment by jring-o** [comment]
edit done

**Comment by encore9870** [comment]
scheduled to be published next monday
