### ISSUE TITLE
Research Summary: Zerocash: Decentralized Anonymous Payments from Bitcoin

### ISSUE THREAD

**Issue by ericjaurena** [smartcontractresearchforum/research_content#34]
[Research Summary by Tina](https://docs.google.com/document/d/1nfh4An1g49jzV6wEaCrNDwc80nCQj1WQkJpSUQy17uQ/edit)

**Comment by ericjaurena** [comment]
Ready for content review by @visavishesh

**Comment by jamesmcgirk** [comment]
Edits done

**Comment by zubepaul** [comment]
Go to market completed
