### ISSUE TITLE
Research Summary: Jenga: Orchestrating Smart Contracts in Sharding-Based Blockchain for Efficient Processing

### ISSUE THREAD

**Issue by content-scrf** [smartcontractresearchforum/research_content#341]
Contributor: Harvesto (@HarvestoOrlando)

Drafting Deadline: August 23, 2022

Link to the Paper: https://home.cse.ust.hk/~weiwa/papers/jenga-icdcs22.pdf

Link to the Draft: https://docs.google.com/document/d/1KnCJjuXNF6Oam1qq3hCL2X2ABUkVQbrqWz64aKEFXzg/edit?usp=sharing

Source of Approval: RP 74

**Comment by content-scrf** [comment]
- [x] Onboarding
- [x] Contributor does not have another draft in the drafting or editing stages

**Comment by HarvestoOrlando** [comment]
Hello! I have finished the summary.

**Comment by osapeter** [comment]
Hello @HarvestoOrlando, nice summary. I have included some suggestions, comments and inquiries for your validation. Thanks

**Comment by HarvestoOrlando** [comment]
Hi @osapeter, thanks. I am done reviewing the suggestions, comments and edits.

**Comment by osapeter** [comment]
Hello @HarvestoOrlando,  many thanks for the feedback. Just a few suggestions and inquiries for your validation. Thanks

**Comment by HarvestoOrlando** [comment]
Hi @osapeter done with the suggestions and inquiries.

**Comment by encore9870** [comment]
https://www.smartcontractresearch.org/t/research-summary-jenga-orchestrating-smart-contracts-in-sharding-based-blockchain-for-efficient-processing/2096
