### ISSUE TITLE
Research Summary: The Economics of Automated Market Makers

### ISSUE THREAD

**Issue by content-scrf** [smartcontractresearchforum/research_content#342]
Contributor: Jacob (@jacob-thrackle)

Drafting Deadline: September 7, 2022

Link to the Paper: https://arxiv.org/pdf/2206.04634.pdf

Link to the Draft: https://docs.google.com/document/d/1xblXn_RzrVg7yXDkOkZwQIIITiv-wG_DDphvQfMHOFQ/edit?usp=sharing

Source of Approval: RP 70

**Comment by content-scrf** [comment]
- [x] Onboarding
- [x] Contributor does not have another draft in the drafting or editing stages

**Comment by jacob-thrackle** [comment]
Draft written. Feedback appreciated, I feel it's a bit clunky.

**Comment by RuthTolulope** [comment]
- [x] All fields described in the Template for that content type have been filled out.

**Comment by osapeter** [comment]
Hello @jacob-thrackle, thanks for the research summary, I have included some suggestions, comments, and inquiries for your validation. Thanks

**Comment by jacob-thrackle** [comment]
Updated. Suggestions welcome.

**Comment by osapeter** [comment]
Hello @jacob-thrackle, thanks for the feedback updates.  I have included some comments for clarification and accept the update/ suggestions. Thanks

**Comment by jacob-thrackle** [comment]
Updated. Thanks, Peter!

**Comment by osapeter** [comment]
@jacob-thrackle, thanks for the feedback update.  I made some section reorganization suggestions and some comments for your validation. Thanks

**Comment by woolgathering** [comment]
Edits made, awaiting feedback. (this is @jacob-thrackle on my personal account).

**Comment by encore9870** [comment]
https://www.smartcontractresearch.org/t/research-summary-the-economics-of-automated-market-makers/2404?u=twan
