### ISSUE TITLE
When is a DAO Decentralized?

### ISSUE THREAD

**Issue by encore9870** [smartcontractresearchforum/research_content#344]
https://csimq-journals.rtu.lv/article/viewFile/csimq.2022-31.04/2972

**Comment by encore9870** [comment]
[Link to the draft](https://docs.google.com/document/d/1de7phRjwO7QXxrkelKRODa_f8D1LhRF4/edit) stored in SCRF's folder.

**Comment by jring-o** [comment]
A single typo. Thanks for the great research! Pleasure to read and learn from.

**Comment by Fizzymidas** [comment]
Please, is this published? Couldn't find it on the forum.
