### ISSUE TITLE
Declarative Smart Contracts

### ISSUE THREAD

**Issue by encore9870** [smartcontractresearchforum/research_content#346]
https://arxiv.org/pdf/2207.13827.pdf

Turning it in by August 19

**Comment by encore9870** [comment]
https://docs.google.com/document/d/1oaUVd8kXA61M4hxNwAw08_GxUccIv8ny94VHXXBZ1qU/edit

**Comment by jring-o** [comment]
A few typos. Good to go.

**Comment by encore9870** [comment]
https://www.smartcontractresearch.org/t/research-summary-declarative-smart-contracts/1948
