### ISSUE TITLE
Research Summary: Tutela: An Open-Source Tool for Assessing User-Privacy on Ethereum and Tornado Cash

### ISSUE THREAD

**Issue by content-scrf** [smartcontractresearchforum/research_content#347]
Contributor: Dimitar

Drafting Deadline: n/a

[Link to the Paper](https://arxiv.org/pdf/2201.06811.pdf)

[Link to the Draft](https://docs.google.com/document/d/1WDWusIu_uw_BSdnxg3cRptB2KwPIuIuA/edit)

Source of Approval: RP 49

**Comment by encore9870** [comment]
- [x] Onboarding
- [x] Competing Obligations

**Comment by encore9870** [comment]
- [x] Sections are filled

**Comment by osapeter** [comment]
Hello @stayhungry07212, I have included some suggestions, a couple of comments, and inquiries for your validation. Thanks

**Comment by RuthTolulope** [comment]
Next check-in date: 26 September 2022

**Comment by osapeter** [comment]
Hello @stayhungry07212, thanks for the feedback and rework, I have included a couple of suggestions and inquiries for your validation. Thanks

**Comment by stayhungry07212** [comment]
Hey @osapeter, I just fixed the summary according to your suggestions and inquiries. Thanks.

**Comment by encore9870** [comment]
https://www.smartcontractresearch.org/t/research-summary-tutela-an-open-source-tool-for-assessing-user-privacy-on-ethereum-and-tornado-cash/2195?u=twan
