### ISSUE TITLE
Analysis of Polkadot: Architecture, Internals, and Contradictions

### ISSUE THREAD

**Issue by encore9870** [smartcontractresearchforum/research_content#348]
https://arxiv.org/pdf/2207.14128.pdf

https://docs.google.com/document/d/1p7l_Fq3tNqG26-rN0pi4Cr8Epef3IInE/edit

**Comment by jring-o** [comment]
A few clarification edits regarding parentheticals (which will be the death of us all), and a couple typos. Otherwise good to go.

**Comment by encore9870** [comment]
https://www.smartcontractresearch.org/t/research-summary-analysis-of-polkadot-architecture-internals-and-contradictions/1960

**Comment by Fizzymidas** [comment]
@twan-dev it says the page does not exist on the forum
