### ISSUE TITLE
Research Summary: An Empirical Analysis of Chain Reorganizations and Double-Spend Attacks on Proof-of-Work Cryptocurrencies

### ISSUE THREAD

**Issue by cipherix** [smartcontractresearchforum/research_content#35]

**Comment by cipherix** [comment]
https://docs.google.com/document/d/1Fq1em4cZsDAHOyAJ8b83PemWawWaim0Ra9lxmxpcW8A/edit?usp=sharing

**Comment by jamesmcgirk** [comment]
This one is in good shape, there was one area which looked like you forgot to delete a copy-paste. I flagged it. Other edits are mostly grammatical - seemed like there was only one author

**Comment by cipherix** [comment]
Thanks @jamesmcgirk! Went over all of your suggestions, looks good. I will post it tomorrow.

**Comment by zubepaul** [comment]
Changed to engagement priority 4
