### ISSUE TITLE
Research Summary: Collaborative Learning for Cyberattack Detection in Blockchain Networks

### ISSUE THREAD

**Issue by encore9870** [smartcontractresearchforum/research_content#355]
Contributor: Henry
Link to Paper: https://arxiv.org/pdf/2203.11076.pdf
Draft: https://docs.google.com/document/d/16GjXj18cdMgAGthqUIMYyo0gJmuKU-pYH-J3sQOm5yU/edit?usp=sharing
Est. Date of Completion: Oct 11, 2022

**Comment by encore9870** [comment]
https://www.smartcontractresearch.org/t/research-summary-collaborative-learning-for-cyberattack-detection-in-blockchain-networks/2140?u=twan

**Comment by RuthTolulope** [comment]
https://www.smartcontractresearch.org/t/research-summary-collaborative-learning-for-cyberattack-detection-in-blockchain-networks/2140
