### ISSUE TITLE
Research summary: "On the Instability of Bitcoin Without the Block Reward"

### ISSUE THREAD

**Issue by tjd233** [smartcontractresearchforum/research_content#38]
Draft link:
https://docs.google.com/document/d/1c_5XkJL-dCPnA46DM3a0-1lVGNkk0REia0HkpdxcdpI/edit

Paper link:
https://www.cs.princeton.edu/~arvindn/publications/mining_CCS.pdf

**Comment by jamesmcgirk** [comment]
@tjd233 Trent - this one was in really good shape, my edits are ready for your okay. Ping me when you're done
