### ISSUE TITLE
Research Summary: Attacking the DeFi Ecosystem with Flash Loans for Fun and Profit

### ISSUE THREAD

**Issue by ericjaurena** [smartcontractresearchforum/research_content#39]
Summary: https://docs.google.com/document/d/1EXMJ_Ktgv-sxlILSz4kPidLp-zhfo00utiJwwgJ3W5Q/edit

**Comment by visavishesh** [comment]
@lpassos giving it a look as well

**Comment by lpassos** [comment]
@visavishesh and @tina1998612  Did my pass and this summary looks great! Left very few minor comments.

**Comment by jamesmcgirk** [comment]
Looks like Tina put them in, I'll have another look and then put it through calendaring.

**Comment by jamesmcgirk** [comment]
Looks good! Moved over to calendaring.

**Comment by visavishesh** [comment]
get it published now @jamesmcgirk

**Comment by jamesmcgirk** [comment]
@tina1998612 - this one is ready to be published, when you have a chance please prepare a Go to Market strategy for it as well. The research summary template: https://docs.google.com/document/d/1gs-a4wsgZhLxDioJzQjZDpOvDPl0xqrEKiQazY9nTEU/edit - contains the latest version of it

**Comment by tina1998612** [comment]
Just posted: https://www.smartcontractresearch.org/t/research-summary-attacking-the-defi-ecosystem-with-flash-loans-for-fun-and-profit/260
For the go to market strategy, should I email the author and ask for feedback directly? Thanks!

**Comment by jamesmcgirk** [comment]
Why don’t you write that down as part of the go to market strategy, and we’ll talk about it on Monday

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
