### ISSUE TITLE
Research (written) debate

### ISSUE THREAD

**Issue by cryptohazard** [smartcontractresearchforum/research_content#44]
I stumble across this discussion/debate about cryptocurrencies role: https://www.pairagraph.com/dialogue/e3b365e55a9d4208873f7e92aa481ba8/1
I liked this back and worth style, like researchers use to do when writing to each other. This is already possible on the forum or Twitter and would be generally worth a listen as a podcast between researchers. But the format pushes "hot takes" while giving each person time, to rethink the arguments and also calm down, might make a better conversation.

**Comment by cryptohazard** [comment]
As an example, POW vs POS would have been an interesting debate because it would have summarized all the assumptions and trade-offs from both consensus.

**Comment by jamesmcgirk** [comment]
@jamesmcgirk follow-up to see if he wants to do this

**Comment by jamesmcgirk** [comment]
adding some notes from this morning's meeting... Larry suggested an opinion-like section. Vishesh created a ticket for a discussion post on the content board.

**Comment by encore9870** [comment]
I'm closing all issues that are not actively being worked on. Reach out to me if you have questions!
