### ISSUE TITLE
Notable Works: Scaling

### ISSUE THREAD

**Issue by cryptohazard** [smartcontractresearchforum/research_content#45]

**Comment by jamesmcgirk** [comment]
Jean is in the middle of a hackathon and will work on this next week

**Comment by jamesmcgirk** [comment]
@cryptohazard - hey Jean, just wanted to see if you were still working on this one

**Comment by cryptohazard** [comment]
draft: https://docs.google.com/document/d/1whFTsUby0Pg1T2zUzVkYfrK_7CMQcf71Jhen6j3rsDM/edit

**Comment by ghettodev** [comment]
@cipherix can you get with @cryptohazard to walk through this work? This is a pretty valuable content type for us, I would love to see some additional planning around this one.

**Comment by cryptohazard** [comment]
Hey @ghettodev I am planning to finish this one by the end of the week.
Feel free to comment @cipherix, even though for now it's just a list of papers.
 I have pretty much all the papers I want there but I am missing some categories like L2 I think.

**Comment by visavishesh** [comment]
@cryptohazard status update

**Comment by cryptohazard** [comment]
@visavishesh I will finish it this week!

**Comment by visavishesh** [comment]
@cryptohazard status update on this?

**Comment by cryptohazard** [comment]
@visavishesh should I assign the review to you when I am done? 
I am finishing the last papers.

**Comment by cryptohazard** [comment]
https://docs.google.com/document/d/1whFTsUby0Pg1T2zUzVkYfrK_7CMQcf71Jhen6j3rsDM/edit

Moving to review

**Comment by visavishesh** [comment]
I'll review this

**Comment by jamesmcgirk** [comment]
self assigned for engagement and posted questions

**Comment by jamesmcgirk** [comment]
@cryptohazard I did my first pass of edits, this looks really good - added a few engagement questions, I'll look over it again tomorrow.

**Comment by jamesmcgirk** [comment]
@cryptohazard i had one outstanding question about Ethereum uncle blocks (is it uncles or uncle blocks), also have a few questions at the beginning of the document for you to answer for the Go to Market strategy -- otherwise, ready for engagement review

**Comment by cryptohazard** [comment]
I will go over it tomorrow and ping you when I am done.

**Comment by cryptohazard** [comment]
I just added a quick correction.
I am not sure how to do the GTM questions. There is a lot of papers for this post so the @ list might be long. 
I will write a paragraph and you let me know what you think or if you have better ideas.

**Comment by jamesmcgirk** [comment]
@cryptohazard I can identify the authors accounts etc. These questions were designed for summaries, so few of them will apply to the notable works. If you could speak to some of the general takeaways, that would be very helpful for social media. Also if there's anything omitted that might be interesting to mention. We can chat about it during our meeting this afternoon

**Comment by cryptohazard** [comment]
@jamesmcgirk ok I just wrote something

**Comment by cryptohazard** [comment]
Forum post: https://www.smartcontractresearch.org/t/notable-works-in-blockchain-scaling/571
