### ISSUE TITLE
Research Summary: Multiple Private Keys for Single Public Key (EPID by Intel)

### ISSUE THREAD

**Issue by dr-chain** [smartcontractresearchforum/research_content#48]
https://eprint.iacr.org/2009/095.pdf

**Comment by ghettodev** [comment]
@visavishesh  does this fit, lets talk on monday

**Comment by jamesmcgirk** [comment]
@drvarun when you have a moment, could you please paste the Google doc in here?

**Comment by drvarun** [comment]
Moving to the icebox due to acceptance of my paper for a journal, deadline approaching. Will resume working on this soon.

**Comment by encore9870** [comment]
I'm closing all issues that are not actively being worked on. Reach out to me if you have questions!
