### ISSUE TITLE
Research Summary: SoK: Transparent Dishonesty: Front-running Attacks on Blockchain

### ISSUE THREAD

**Issue by ericjaurena** [smartcontractresearchforum/research_content#50]
Tina: [Summary](https://docs.google.com/document/d/1RfuLNvmXqCEGZcKz4f1ubZ_mjv3o7qEkT5WvEukFp0c/edit)

**Noteworthy**: this paper was authored by Shayan Eskandari, a previous SCRF contact

**Comment by jamesmcgirk** [comment]
@tina1998612 we could definitely include reaching out to the author (mentioned in the document) as one aspect of Go to Market strategy, let's come up with a couple of others too

**Comment by jamesmcgirk** [comment]
moving this one over to published, as it went up on 1/22

**Comment by zubepaul** [comment]
Go to market completed
