### ISSUE TITLE
Research Summary: PERIMETER: A network-layer attack on the anonymity of cryptocurrencies

### ISSUE THREAD

**Issue by tina1998612** [smartcontractresearchforum/research_content#53]
This would be a good post because it is the first passive attack that leverages the design of internet router to map transactions to IP addresses. 

- Link to paper: https://nsg.ee.ethz.ch/fileadmin/user_upload/publications/perimeter.pdf
- Google doc: https://docs.google.com/document/d/1KfAbC9jd9NStwbtgIINKLWSZgt7xm9Etl0Wn9LUrCNs/edit

**Comment by jamesmcgirk** [comment]
@tina1998612 Could you add a go to market strategy when you get chance, please?

**Comment by jamesmcgirk** [comment]
Great work with go-to-market, I had a few minor changes. Take another look at the research question, I left some notes in the document. Other than that, excellent work!

**Comment by jamesmcgirk** [comment]
Changes made, moving this to calendaring.

**Comment by visavishesh** [comment]
@tina1998612 ready to post

**Comment by visavishesh** [comment]
@tina1998612 ready to post. any blockers?

**Comment by visavishesh** [comment]
@tina1998612 once posted, author can close ticket. thanks for posting!

**Comment by ericjaurena** [comment]
Socials drafted, submitted to @tina1998612 for posting at her soonest convenience

**Comment by tina1998612** [comment]
posted on twitter & linkedin

**Comment by jamesmcgirk** [comment]
GtM successfully launched?

**Comment by jamesmcgirk** [comment]
GtM review scheduled for Friday @ericjaurena to brief (if he's available)
