### ISSUE TITLE
Research Summary: The Attack of the Clones Against Proof-of-Authority

### ISSUE THREAD

**Issue by tjd233** [smartcontractresearchforum/research_content#55]
Paper link:
https://arxiv.org/pdf/1902.10244.pdf

Interest:
Discusses a potential security threat to PoA systems, specifically Aura and Clique. Respective teams have begun to implement security changes proposed in the paper to mitigate the risk of a clone attack.

**Comment by encore9870** [comment]
I'm closing all issues that are not actively being worked on. Reach out to me if you have questions!
