### ISSUE TITLE
Research Summary: PoX: Proof of Transfer Mining with Bitcoin

### ISSUE THREAD

**Issue by tjd233** [smartcontractresearchforum/research_content#56]
Paper link:
https://uploads-ssl.webflow.com/5e7b1a27d160ce49af1c24e1/5f1596b12bcc0800f3dcadcd_pox.pdf

Interest:
Whitepaper discussing a new consensus PoX. First, our consensus category is lacking content compared to other areas of the forum. Second, this is an interesting consensus structure that may result in further evolutions of it, and this paper leads into another reputation incentive mechanism paper utilizing PoX.

**Comment by encore9870** [comment]
I'm closing all issues that are not actively being worked on. Reach out to me if you have questions!
