### ISSUE TITLE
Research Summary: PoRX: A reputation incentive scheme for blockchain consensus of IIoT

### ISSUE THREAD

**Issue by tjd233** [smartcontractresearchforum/research_content#57]
Paper link:
https://www.sciencedirect.com/science/article/pii/S0167739X19310581?casa_token=KJxU24taQboAAAAA:c-7ikk7bb1QSkUevtyrLGtCunpJo5NPjVEXJUyy0KXdvEf2DxMjTXZN9opO2MCUKtAwwyFZIqQ#b5

Interest: 
Using PoX as a base the authors propose a change by including a reputation scheme to improve node participation. The authors use IIoT (Industrial Internet of Things) as an example of the potential benefits of this stucture.

**Comment by encore9870** [comment]
I'm closing all issues that are not actively being worked on. Reach out to me if you have questions!
