### ISSUE TITLE
WIP: Finding Bugs Automatically in Smart Contacts

### ISSUE THREAD

**Issue by jamesmcgirk** [smartcontractresearchforum/research_content#59]
Contracts with Parameterized (Called by Sean Sie) Invariants https://www.certora.com/pubs/sbc2020.pdf

An AAVE V2 white paper, and find out AAVE’s smart contract was audit by Certora.com. They published WIP: Finding Bugs Automatically in Smart Contracts with Parameterized Invariants last year. I think this framework is also works on lots of DeFi projects.

https://docs.google.com/document/d/1NiQ9pL6yAYqdQn_r2BOXSV2EJ6DnZclGQjImvHN-FpU/edit

**Comment by jamesmcgirk** [comment]
Called (and created) by Sean Sie (Siemingfong)

**Comment by cipherix** [comment]
@jamesmcgirk Sean provided the following doc: https://docs.google.com/document/d/1NiQ9pL6yAYqdQn_r2BOXSV2EJ6DnZclGQjImvHN-FpU/edit?usp=sharing

I went over it a couple of days ago, looks like it's ready for content review.

**Comment by jamesmcgirk** [comment]
Note for future @jamesmcgirk, ping Trent when this is ready

**Comment by jamesmcgirk** [comment]
Needs a little work on the TL;DR and background section. Please move the document into the SCRF shared drive as well. Let me know when this ready for another look. - J

**Comment by jamesmcgirk** [comment]
@Siemingfong did @cipherix give you the okay to post this in the forum? We normally discuss a publishing strategy on Friday before posting.

**Comment by jamesmcgirk** [comment]
Moving this one into calendaring

**Comment by Siemingfong** [comment]
@jamesmcgirk Sorry, I misunderstood the go to publishing strategy. I thought it is a draft version to get some new comments from the forum after two peer-review. 
@cipherix Could you please kindly give me some advice from this document, thanks for your help :)

**Comment by jamesmcgirk** [comment]
No worries, Sean! We can go over the publishing process on Monday— this one was in good shape so it was okay to publish :)

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Siemingfong** [comment]
Thanks! Look forward to hearing from everyone :)
