### ISSUE TITLE
Research Summary: Blockchain-Based Settlement for Asset Trading

### ISSUE THREAD

**Issue by cipherix** [smartcontractresearchforum/research_content#61]
Pitch:
An interesting paper on how viable it would be to settle securities on public and private blockchains. 

Draft link:
https://docs.google.com/document/d/1KkQbpZHpGzk4Y_Y7GDOe2ISUYn5Dn96QrrvEkYWTSUg/edit

Update link:
https://www.researchgate.net/profile/Jonathan_Chiu/publication/327026205_Blockchain-Based_Settlement_for_Asset_Trading/links/5c2fcb9392851c22a35b2a23/Blockchain-Based-Settlement-for-Asset-Trading.pdf

**Comment by jamesmcgirk** [comment]
@tjd233 also in good shape, mostly fixed the flow and flagged a few sentences that were a little garbled. Biggest change was making the background section into bullets. Feel free to revert. Ping me when you're ready and I'll go through a second time and drag to Calendaring

**Comment by jamesmcgirk** [comment]
Nicely done, moved over to calendaring
