### ISSUE TITLE
Post-Quantum Security of the Bitcoin Backbone and Quantum Multi-Solution Bernoulli Search

### ISSUE THREAD

**Issue by Coinproz** [smartcontractresearchforum/research_content#65]
**Why is this important?**
This paper addresses the potential vulnerabilities of the Bitcoin blockchain in a scenario in which Quantum computing is no longer theoretical and Quantum-attacks on the blockchain become possible.

Link:

https://arxiv.org/pdf/2012.15254.pdf

doc:
https://docs.google.com/document/d/1y4f95soZCstD_8WBKtRFegNnlIf338QOrSYHg5V6VZ8/edit?usp=sharing

**Comment by jamesmcgirk** [comment]
@Coinproz - super cool summary, I flagged a couple of places which might benefit from splitting your sentences into smaller chunks; otherwise ready for calendaring once you've added in a GtM strategy

**Comment by jamesmcgirk** [comment]
Assigned to @ghettodev socials ready

**Comment by ghettodev** [comment]
Can you put it on the calendar? The 'coding a bot' socials went out today.

**Comment by jamesmcgirk** [comment]
Post-quantum socials scheduled for 4/15. @ghettodev to post.

**Comment by zubepaul** [comment]
Go to market completed.
