### ISSUE TITLE
About post: audits

### ISSUE THREAD

**Issue by jamesmcgirk** [smartcontractresearchforum/research_content#66]
About post for the "Audit" subcategory. https://www.smartcontractresearch.org/t/about-the-audits-category/49

**Comment by jamesmcgirk** [comment]
@lpassos thank you for volunteering!

**Comment by lpassos** [comment]
Update: this will be delayed to next week, as I was not able to put efforts on this front. Let me know of any issues.

**Comment by jamesmcgirk** [comment]
Me either. Hope all is going well and let me know if you need anything from our end. - J

**Comment by lpassos** [comment]
Suggestion: 

Summaries of audit reports assessing  different aspects of a crypto project (e.g., code, economics, compliance, etc).

**Comment by lpassos** [comment]
@jamesmcgirk and @ghettodev  Let me know if you are ok with the proposed one liner.

**Comment by ghettodev** [comment]
Updated the category description.
