### ISSUE TITLE
Research Summary: General Purpose AMM and Options

### ISSUE THREAD

**Issue by jamesmcgirk** [smartcontractresearchforum/research_content#68]
Current progress: 
The team has replied that they will provide a mathematical proof for their options AMM and a graph to illustrate the mechanism soon. 

https://medium.com/podsfinance/general-purpose-amms-and-options-6d371dae396c 

Tina chose this out of the Research Pulse

Google doc: https://docs.google.com/document/d/1YOvvOKxGyxXqiBNPKXK5f0GLfKlT3iVFP4LXE9wnw8s/edit#

**Comment by jamesmcgirk** [comment]
https://docs.google.com/document/d/1YOvvOKxGyxXqiBNPKXK5f0GLfKlT3iVFP4LXE9wnw8s/edit

**Comment by jamesmcgirk** [comment]
Tina is busy with school so made the edits myself. Moving over to calendaring. Could be a good tool for engagement if Pods Finance can update us

**Comment by tina1998612** [comment]
yeah thanks:) when can this one be published?

**Comment by jamesmcgirk** [comment]
This is another one that needs a go to market strategy.

@cipherix when should this one be published?

**Comment by jamesmcgirk** [comment]
@jamesmcgirk check with engagement team

**Comment by jamesmcgirk** [comment]
Tina is adding some context and the GtM

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by zubepaul** [comment]
Assigned as Engagement Team

**Comment by jamesmcgirk** [comment]
@tina1998612 are you still working on this?

**Comment by jamesmcgirk** [comment]
We could peer review and publish this one...

**Comment by jamesmcgirk** [comment]
This one is up for grabs if anyone would like to finish it off.

**Comment by jamesmcgirk** [comment]
Picked up by @twan-dev

**Comment by jamesmcgirk** [comment]
@tina1998612 any special instructions for this one? (I'm passing this along to Twan to finish)

**Comment by twan-dev** [comment]
I've created a new document as I don't want to overwrite Tina's summary, which has remained intact since March 22. 

Although everything written in this new document is individual work, I would say that the existing document did help me pick up quickly. 

Many factors allowed me to finish early, taking up only around a day's work, which was not possible without my background in Finance and the existing part of the summary.

https://docs.google.com/document/d/1KSUNXkQ86uMaH7x7ti1u7BgPtqfDiN7m9nd5JU8QnQI/edit#heading=h.ihnld5i5bej6

**Comment by jamesmcgirk** [comment]
@Coinproz would you like to take a look at this one?

**Comment by jamesmcgirk** [comment]
@29988122 would like to take a look at this one for peer review?

**Comment by 29988122** [comment]
Done reviewing. Feedbacks are provided as Mandarin comments in the google doc, for better conveying nunances.

Wait for @twan-dev to reply and then we can progress.

**Comment by jamesmcgirk** [comment]
@cipherix what do you recommend we do with this one? It's the one that Tina abandoned about halfway through (even though we gave her the okay to publish it with some missing sections). My suggestion would be run it as is... could be an interesting debate for Monday's meeting

**Comment by encore9870** [comment]
I'm closing all issues that are not actively being worked on. Reach out to me if you have questions!
