### ISSUE TITLE
Research Summary: Markets for Crypto Tokens, and Security under Proof of Stake

### ISSUE THREAD

**Issue by tjd233** [smartcontractresearchforum/research_content#69]
Interest: Discusses the robustness of PoS cryptocurrencies by modelling "... the market for tokens and determine how the cost of attacking the system depends on the level and shape of token supply and demand." 

Key findings:
Stablecoins may be less vulnerable than free-floating PoS cryptocurrencies, currencies that act primarily as units of exchange are more vulnerable if the velocity of money is higher.

Link: https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3740654&download=yes

**Comment by ericjaurena** [comment]
@cipherix indicates this paper is relevant https://arxiv.org/abs/2006.11156

**Comment by jamesmcgirk** [comment]
@tjd233 Trent, welcome back - just wanted to see if you were still working on this one

**Comment by encore9870** [comment]
I'm closing all issues that are not actively being worked on. Reach out to me if you have questions!
