### ISSUE TITLE
Research Summary for Ripple Protocol

### ISSUE THREAD

**Issue by Coinproz** [smartcontractresearchforum/research_content#7]
**What is this paper about?**  
This is a mathematical analysis of the Ripple consensus protocol.

**Why is it important?**  
The paper discovers some critical vulnerabilities in the protocol that are relevant to engineers to be able to either solve the problem or figure out how to warn users how to avoid succumbing to the issues.

Leonardo reviewed for content previously, so really just needs editorial review:
https://docs.google.com/document/d/1ROhYBCyvt9whvfVa90BmasIGD826dH2crIJqNnWEDUs/edit

**Comment by lpassos** [comment]
@Coinproz @visavishesh Did my first pass. IMHO, this is not an audit; rather, it is a research paper. I recommend changing the format from "audit summary" to "research summary" and adapting the content accordingly. Then, we do another review pass. My apologies for the delay in having the first review ready.

**Comment by visavishesh** [comment]
@Coinproz Are you in agreement?

**Comment by lpassos** [comment]
@visavishesh and @Coinproz  Did my second pass on the document - the review is complete. Overall, I would suggest: (1) change this post into a research summary; (2) clarify terms with a Background section; (3) clarify some sentences as some parts could be better connected and explained. I've tried to highlight those to the best of my effort, but likely we will need a third pass after the changes are in place.

**Comment by visavishesh** [comment]
Heading back to drafting based on meeting about definition of audits. This is a RP not an audit.

**Comment by jamesmcgirk** [comment]
Made some editorial suggestions, let me know when it's ready @Coinproz

**Comment by jamesmcgirk** [comment]
@Coinproz if you're pressed for time I can push through some of these changes. There were only a few I had questions about.

**Comment by cipherix** [comment]
@Coinproz @jamesmcgirk also went through a review -- the content itself looks good, but it seems like @Coinproz still needs to resolve the suggestions. We can then review the final piece once again and if there are no problems, we can move to calendaring.

**Comment by lpassos** [comment]
Let me know if/when I should do a content review pass.

**Comment by jamesmcgirk** [comment]
@Coinproz tidied up a few minor things. Ready to go!

**Comment by zubepaul** [comment]
Go to market completed
