### ISSUE TITLE
Research Summary:  'BitML: A Calculus for Bitcoin Smart Contracts' (CCS '18)

### ISSUE THREAD

**Issue by jamesmcgirk** [smartcontractresearchforum/research_content#72]
Clara S. suggests this one, she notes it's older but is still relevant (and her team is studying it). Would this be worth creating a summary of?

(CCS '18): https://eprint.iacr.org/2018/122.pdf

**Comment by ClaraS** [comment]
The draft for review is here: https://docs.google.com/document/d/1oBFQEkjNApvFKKBzAjtly-M9Hf-KPZSa3IdlyJPXLDU/edit

**Comment by jamesmcgirk** [comment]
Added go-to-market questions, assigned myself to it for now

**Comment by jamesmcgirk** [comment]
Added notes from Wed status update to GtM

**Comment by Coinproz** [comment]
Create question about the limitations of blockchain functionality being a benefit over Turing complete functionality

**Comment by jamesmcgirk** [comment]
Minor edits. I left them as suggested changes because I'm not sure if it's "a small-semantics" or just "small-semantics"...

**Comment by zubepaul** [comment]
@cipherix Please use the GTM document during the author interview to keep notes (on the bottom of the doc) so that the engagement team can use those notes for future engagement.

**Comment by jamesmcgirk** [comment]
@ClaraS @cipherix this one is ready to be published
