### ISSUE TITLE
Research Summary: REDSHIFT: Transparent SNARKs from List Polynomial Commitment IOPs

### ISSUE THREAD

**Issue by cipherix** [smartcontractresearchforum/research_content#74]
https://eprint.iacr.org/2019/1400.pdf

https://docs.google.com/document/d/1mPtCHfmDO4XABV1xMFR9LiGHPGi56UoCQKjHPGx98TU/edit?usp=sharing

**Comment by jamesmcgirk** [comment]
@Siemingfong - I just wanted to confirm, is this the one you're working on?

**Comment by jamesmcgirk** [comment]
Sean is working on his draft, his progress so far is below - 
https://docs.google.com/document/d/1mPtCHfmDO4XABV1xMFR9LiGHPGi56UoCQKjHPGx98TU/edit?usp=sharing

**Comment by jamesmcgirk** [comment]
[Another version for LN](https://docs.google.com/document/d/1MP-E5pzYhhPwkWYCR5DU28IQiletXtNB1eogJeCBmgs/edit) - this one is almost done

**Comment by cipherix** [comment]
@Siemingfong I took the liberty to write the remaining sections of this summary. Please let me know if you have any content-related comments, specially on the Results and Applicability sections.

@jamesmcgirk this is ready for a first editorial pass if you want. Please connect with @Siemingfong when possible to go trough the GTM strategy. Thank you!

**Comment by jamesmcgirk** [comment]
@Siemingfong this was really good! I added a couple of bullet points to the TLDR; could you please check that they are accurate? I also have a few 'go to market' questions for the engagement team.

**Comment by jamesmcgirk** [comment]
@jamesmcgirk assigned for ET, prepared initial GtM, waiting for questions

**Comment by jamesmcgirk** [comment]
Looked over the rewrite, changed a few minor things. @Siemingfong you're free to publish this summary. Please answer the questions in blue when you can.

**Comment by Siemingfong** [comment]
@jamesmcgirk I finished the Go-To-Market questions. It's ready to publish

**Comment by Siemingfong** [comment]
Publish
Twitter: https://twitter.com/SieMingFong/status/1384075324657307656?s=20
LinkedIn: https://www.linkedin.com/posts/siemingfong_research-summary-redshift-transparent-snarks-activity-6789840478918574080-foUY

**Comment by jamesmcgirk** [comment]
Retweeting research post today, then GtM

**Comment by jamesmcgirk** [comment]
Seeded a comment. Next phase is reaching out to the authors.

**Comment by jamesmcgirk** [comment]
Socials posted. Inviting authors.
