### ISSUE TITLE
Research Summary: "Game Theoretical Analysis of Atomic Cross-Chain Swaps"

### ISSUE THREAD

**Issue by bgits** [smartcontractresearchforum/research_content#76]
With cross-chain bridging becoming more common, the security and reliability of these approaches is top of mind.

Presents a mathematical framework that characterizes blockchain swap protocols as the combination of a publishing and a commitment phase.

Proves that following a swap protocol characterized by concurrent publishing of exchange contracts and snap (immediate) assets transfers is a Nash equilibrium. Proves that for protocols with a sequential publishing and commitment of the assets transfers, following the prescribed protocol is a sub-game perfect equilibrium.

https://hal.archives-ouvertes.fr/hal-02414356/

**Comment by jamesmcgirk** [comment]
@bgits - are you still working on this one?

**Comment by bgits** [comment]
> @bgits - are you still working on this one?

I'm not working on this. Maybe @drvarun is working on it as he moved it to drafting?

**Comment by drvarun** [comment]
@bgits @jamesmcgirk Sorry, I think it was moved by mistake.

**Comment by cipherix** [comment]
Presented and approved. Moved to icebox for now.

**Comment by encore9870** [comment]
I'm closing all issues that are not actively being worked on. Reach out to me if you have questions!
