### ISSUE TITLE
Research Summary: Dynamic Curves for Decentralized Autonomous Cryptocurrency Exchanges

### ISSUE THREAD

**Issue by tjd233** [smartcontractresearchforum/research_content#77]
Point of interest:
Discusses the potential limitations of current AMMs, primarily potential issues with liquidity pools. They propose a new "Dynamic Curve" utilizing a price oracle to change the underlying relationship between the asset and LP to confirm the price of the asset stays identical to the market price. This could be a good follow up on my previous AMM summary, as well as Tina's. 

*NOTE* I will be out of town Monday 2/15 so I won't be able to discuss this. Feel free to move to Ice Box until 2/22.

Link to paper:
https://arxiv.org/abs/2101.02778

@visavishesh I'm assigning this to you. I will grab the other one I mentioned out of the Icebox.

**Comment by lpassos** [comment]
@visavishesh It seems I was assigned to this one, but I don't recall that. Can you please confirm?

**Comment by visavishesh** [comment]
glitch. removing you.

**Comment by lpassos** [comment]
Thanks :)

**Comment by jamesmcgirk** [comment]
@visavishesh - are you working on this one?

**Comment by encore9870** [comment]
I'm closing all issues that are not actively being worked on. Reach out to me if you have questions!
