### ISSUE TITLE
The Byzantine Generals Problem

### ISSUE THREAD

**Issue by bgits** [smartcontractresearchforum/research_content#78]
A commonly heard saying is that up until the invention of bitcoin the The Byzatine Generals Problem was an unsolved problem.

However the paper does propose solutions including a 99% fault tolerant consensus as described by Leslie Lamport on page 391.

We could use this as opportunity to compare the approaches described in the paper with POW and POS type consensus approaches.

The EF produced a python simulation based on it, we could convert it to an interactive notebook in something like observable: https://github.com/ethereum/research/blob/master/99fault/consensus.py

Paper: https://people.eecs.berkeley.edu/~luca/cs174/byzantine.pdf

**Comment by encore9870** [comment]
I'm closing all issues that are not actively being worked on. Reach out to me if you have questions!
