### ISSUE TITLE
Research Summary: "Attacking the DeFi Ecosystem with Flash Loans for Fun and Profit"

### ISSUE THREAD

**Issue by cipherix** [smartcontractresearchforum/research_content#79]
Paper: https://arxiv.org/abs/2003.03810

**Comment by jamesmcgirk** [comment]
Didn't we already cover this one?

**Comment by lpassos** [comment]
Yeah, I was about to say the same. In the past, we had two tickets about this paper, so, it could be the case this is the extra one.

**Comment by encore9870** [comment]
I'm closing all issues that are not actively being worked on. Reach out to me if you have questions!
