### ISSUE TITLE
Research Summary: Bitcoin Covenants Unchained

### ISSUE THREAD

**Issue by cipherix** [smartcontractresearchforum/research_content#80]
Paper:

https://arxiv.org/abs/2006.03918#:~:text=Covenants%20are%20linguistic%20primitives%20that,scripts%20of%20the%20redeeming%20ones.

**Comment by cipherix** [comment]
Link to draft:

https://docs.google.com/document/d/1pXoo1O9UT6DK5f1SGn3hOtZO86p2LaUJrvM2QKEIT3Y/edit?usp=sharing

**Comment by jamesmcgirk** [comment]
Per Friday's meeting, this to go before BitML

**Comment by jamesmcgirk** [comment]
made some tiny changes, only reason I'm pinging you is that I didn't have Edit access @cipherix ready for Engagement Review when you make them. Might want to standardize Bitcoin/bitcoin capitalization (I'd lean toward capitalized but defer to convention)

**Comment by jamesmcgirk** [comment]
Ready for publication?

**Comment by jamesmcgirk** [comment]
Begin GtM. Socials drafted, ready to go when BitML is published.
