### ISSUE TITLE
StableSwap - efficient mechanism for Stablecoin liquidity

### ISSUE THREAD

**Issue by bgits** [smartcontractresearchforum/research_content#82]
https://www.curve.fi/stableswap-paper.pdf

**Comment by cipherix** [comment]
any updates on this ticket @bgits?

**Comment by bgits** [comment]
I have been busy with another project I have not been able devote time this week. I expect to be able to wrap it up in the next week.

**Comment by cipherix** [comment]
Sounds good, thank you for the update

**Comment by visavishesh** [comment]
@bgits hey barry wanted to check and see if this is still in-progress?

**Comment by bgits** [comment]
> @bgits hey barry wanted to check and see if this is still in-progress?

It's WIP, I stopped to address another project but expect to resume in a few days.

**Comment by encore9870** [comment]
I'm closing all issues that are not actively being worked on. Reach out to me if you have questions!
