### ISSUE TITLE
Research Summary: Coding a DeFi arbitrage bot

### ISSUE THREAD

**Issue by tina1998612** [smartcontractresearchforum/research_content#83]
Google doc: https://docs.google.com/document/d/18sKWq9lhpCcc256eR2LCEPbJB-TJ3QWmwRrIn60nibs/edit#

Part 1: https://extropy-io.medium.com/coding-a-defi-arbitrage-bot-45e550d85089
Part 2: https://extropy-io.medium.com/arbitrage-bot-part-2-97e7b710dcf
 
Importance: DeFi arbitrage is a hot issue now, but few knows the underlying mechanism, so this type of article may drive traffic and raise discussions.

**Comment by jamesmcgirk** [comment]
@tina1998612 are you still interested in working on this one? If not, Leo would like to do it

**Comment by tina1998612** [comment]
I thought this article didn't pass other's review (no comment on GitHub issue) so I didn't know I can proceed xD" I'm still interested in covering this one if it's of the team's interest. Thanks:)

**Comment by jamesmcgirk** [comment]
@lpassos I'm afraid that Tina still wants to do this one, I had to reassign it to her

**Comment by jamesmcgirk** [comment]
@tina1998612 I've completed my first editorial pass and added some engagement team questions. Please let me know when you're done with this and I'll take another look.

**Comment by tina1998612** [comment]
@jamesmcgirk Done~

**Comment by jamesmcgirk** [comment]
@tina1998612 thank you! @zubepaul this one is ready for the engagement team to work its magic

**Comment by jamesmcgirk** [comment]
@tina1998612 you are clear to publish this one!

**Comment by jamesmcgirk** [comment]
Beginning our engagement campaign on 4/7

**Comment by tina1998612** [comment]
posted! https://www.smartcontractresearch.org/t/research-summary-coding-a-defi-arbitrage-bot/282

**Comment by jamesmcgirk** [comment]
Thank you! @tina1998612 We'll begin executing our go to market strategy on Wednesday

**Comment by jamesmcgirk** [comment]
@jamesmcgirk will reach out to author today

**Comment by ghettodev** [comment]
Socials posted: https://twitter.com/SCRForum/status/1382015967119560708

**Comment by jamesmcgirk** [comment]
Authors engaged. @jamesmcgirk to create discussion
