### ISSUE TITLE
About post: standards

### ISSUE THREAD

**Issue by lpassos** [smartcontractresearchforum/research_content#85]
About post for the "Standards" subcategory. https://www.smartcontractresearch.org/t/about-the-audits-category/48

**Comment by lpassos** [comment]
Suggestion:

Improvement proposals (IPs), request for comments (RFCs), approved standards within or across different blockchain networks, etc.

**Comment by lpassos** [comment]
@ghettodev and @jamesmcgirk Left a suggestion (one-liner) to be posted in the forum.

**Comment by ghettodev** [comment]
That section is mostly a placeholder example of what some subcategories could look like. The original thought was that we could use it as a location to discuss standards as they apply to Auditing. 

Maybe 'standardization' should be a tag instead? Might be weird to have multiple subcategories with the same name.

**Comment by lpassos** [comment]
@ghettodev Yeah, standards seems to be a bigger theme than security. I am in favor of removing this subcategory altogether. Audits & postmortems, however, make sense in keeping.

**Comment by ghettodev** [comment]
Agreed. The standards category has been removed. Once we begin to dig into the supporting standards in the space we can consider a new tag or something more complex.
