### ISSUE TITLE
Discussion post: Flashbots

### ISSUE THREAD

**Issue by visavishesh** [smartcontractresearchforum/research_content#9]
https://docs.google.com/document/d/1BgRIbht_hMj1i_f_PS4Dw64SNS1g8T6st_g8pLHSq2s/edit

**Comment by visavishesh** [comment]
https://docs.google.com/document/d/1BgRIbht_hMj1i_f_PS4Dw64SNS1g8T6st_g8pLHSq2s/edit

**Comment by ericjaurena** [comment]
Sure you're aware of this but just wanted to put it on your radar https://github.com/flashbots/mev-research
