### ISSUE TITLE
Tendermint: Byzantine Fault Tolerance in the Age of Blockchains

### ISSUE THREAD

**Issue by lpassos** [smartcontractresearchforum/research_content#92]
## Tendermint: Byzantine Fault Tolerance in the Age of Blockchains

Link: http://knowen-production.s3.amazonaws.com/uploads/attachment/file/1814/Buchman_Ethan_201606_Msater%2Bthesis.pdf

or a more concise (and probably more up-to-date ) resource:

https://docs.tendermint.com/master/introduction/what-is-tendermint.html#

## Why this is good for SCRF?

It focus on an area where we are currently lacking content; with Cosmos gaining more traction with time, explaining Tendermint brings value for those willing to learn it.

**Comment by visavishesh** [comment]
@cipherix do you have resources leo can use for this post?

**Comment by lpassos** [comment]
After further discussions with Lucas, we decided to do a summary on "Dissecting Tendermint", whose pdf can be found here:
https://arxiv.org/pdf/1809.09858.pdf

**Comment by lpassos** [comment]
WIP: https://docs.google.com/document/d/1nIPRj77IpqpcA0p_D5Vn6SC8q8VMjDtmxhLyljJhW4c/edit?usp=sharing

**Comment by lpassos** [comment]
@visavishesh and @cipherix Ready for review.

**Comment by zubepaul** [comment]
Go to Market prompt questions added to the draft summary

**Comment by zubepaul** [comment]
Go to Market prompt questions added to summary draft

**Comment by cipherix** [comment]
@lpassos just went through another review and left comments -- let me know what you think. If you could also provide answers to the GTM, that'd be much appreciated

**Comment by lpassos** [comment]
@cipherix Sure, will take a look again. Let me know of a time you in your calendar for us to synchronize on this once I give it another pass. Maybe a call on May 4th?

**Comment by cipherix** [comment]
Let's do it

**Comment by cipherix** [comment]
Final content-related comments have been addressed, moving it to Editorial Review @jamesmcgirk 

@lpassos, If you fill out GTM, that'd be great :)

**Comment by jamesmcgirk** [comment]
@cipherix really nice, I made a few tiny edits for you to approve/ignore

**Comment by zubepaul** [comment]
GTM meeting scheduled

**Comment by zubepaul** [comment]
GTM meeting completed. Go to market strategy is being finalized by @ericjaurena

**Comment by jamesmcgirk** [comment]
@lpassos this is ready to be published!
