### ISSUE TITLE
Research Summary: Flash Ecosystem: An In-depth Explanation

### ISSUE THREAD

**Issue by tina1998612** [smartcontractresearchforum/research_content#96]
Link to article: https://xord.com/publications/flash-ecosystem-an-in-depth-explanation

Google doc: https://docs.google.com/document/d/1JL-n8y0yTFOjzm-08Ls9Y6bwG3VQdi-Q7KDVP5gTf0k/edit#

**Comment by jamesmcgirk** [comment]
Tina said this is one is up for grabs

**Comment by tina1998612** [comment]
I took a deeper look into flashstake and discover that it’s a bit weird. The platform seems to create their token value out of nowhere.

- Users can only stake FLASH token to earn yields. 
- Their swap can only exchange other assets into FLASH (which means that their platform revenue depends on the demand of FLASH token
- The yield depends on how long u stake your FLASH, the longer u stake, the higher the yield. This is because the longer a user stakes, the circulating FLASH token is more valuable.
- The highest APY for staking is 50%, and there’s no future contract for FLASH to hedge the price fluctuation risk.
- Staking FLASH tokens also does not benefit the society like yield farms do (provide liquidity for DEXes).

If a user buys FLASH, her optimal strategy is to stake and get yield while having their token locked up. 
In this way, users do not benefit from this protocol, the platform does. The users may even be losing their money as the price of FLASH goes down. The only condition that is profitable for the users is when more people wants to buy FLASH in the future, which is exactly how the Ponzi scheme works.

So I am not sure if I should continue to write this research summary. Or I should write a discussion post to warn people the underlying risks of flashstake?

**Comment by jamesmcgirk** [comment]
Would be a nice one, moved it into the IB for someone else to pick up

**Comment by encore9870** [comment]
Interesting discussion. I'm closing all issues that are not actively being worked on. Reach out to me if you have questions!
