### ISSUE TITLE
Research Summary: Formal Analysis of Composable DeFi Protocols

### ISSUE THREAD

**Issue by tina1998612** [smartcontractresearchforum/research_content#97]
- [ ] draft  
- [ ] publish
- [ ] go to market

- Google doc: https://docs.google.com/document/d/1rcm4liRhV-uNSFNOHthMqbxMKPdKf3AKGTqqWALUpI8/edit#
- Link: https://arxiv.org/pdf/2103.00540.pdf
- It is in the Research Pulse.

**Comment by zubepaul** [comment]
Assinged as Engagement Team
